### ISSUE TITLE
Chronicle for off heap cache

### ISSUE THREAD

**Issue by ygokirmak** [OpenHFT/Chronicle-Queue#1]
Hi,

Is there any use case where chronicle used as a base for off-heap cache implementation. I have some feeling that we can use chronicle architecture to build an off-heap cache library. And I saw that you have started implementing HugeCollections that will be similar to what I am thinking...

What do you think? It is possible/feasible ?
And if it is possible what is the starting point do you have any advice?

regards

**Comment by peter-lawrey** [comment]
Chronicle Map is the best choice for an off heap map at this stage.
Closing.
