### ISSUE TITLE
StoreFileListener: Only add a task to the background releaser if that task might do something

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#1002]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea2), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
