### ISSUE TITLE
Cycle Rolling with Positive Epoch bug

### ISSUE THREAD

**Issue by ZiningYin** [OpenHFT/Chronicle-Queue#1015]
Replication: 
the roll cycle is FAST_DAILY
GMT Time is 2022-03-01-23:59:00
Epoch is 3600,000 (GMT+1hour)
Local Time is 2022-03-02-00:59:00 

The file generated will be for the cycle that is the day of 20220301.cq4. 
Expected file is 20220302.cq4

**Comment by RobAustin** [comment]
@ZiningYin would you be able to write a failing test for this use case?
