### ISSUE TITLE
TableStore attempts to write out of bounds when you write a lot of messages to it

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1025]
This is a regression, I think it was introduced by https://github.com/OpenHFT/Chronicle-Bytes/commit/6ad7e75e30ad072b165cb5302c7411fad14c1fb5.

**Comment by nicktindall** [comment]
Root cause is https://github.com/OpenHFT/Chronicle-Bytes/issues/342

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea2), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
