### ISSUE TITLE
Queue peek ?

### ISSUE THREAD

**Issue by eix128** [OpenHFT/Chronicle-Queue#1028]
Hi , i m trying to use your queue but i just want to read but dont remove the element from queue.
I could not find any example for that.

I want to remove element manually from the queue when some conditions meet.

        while (working.get()) {
            //final long index = tailer.index();
            // tailer.readDocument automatically removes the object from the queue
            tailer.readDocument(w -> {
                        System.out.println("msg: " + w.read(() -> "msg").text());
                final String param = w.read("param").text();
                final String requestIp = w.read("requestIp").text();
                final long requestTime = w.read("requestTime").readLong();
                final long responseTime = w.read("responseTime").readLong();
                final String returnCode = w.read("returnCode").text();
                try(Connection connection = DataSource.getConnection()) {
                    LogsStoreConnectionFacade.logAction( connection, param, requestIp, new Timestamp(requestTime), new Timestamp(responseTime), returnCode );
                 //remove the element when sql is success  (how to do it) ?
                } catch (SQLException throwables) {
                    //exception thrown so dont remove the element from queue

                }
            });
        }

**Comment by JerryShea** [comment]
You can read from the queue with a DocumentContext and then call rollbackOnClose() on the DC before you close it. That should rollback the read from the queue when you close the DC. But Your Mileage May Vary so you should try it out.

**Comment by eix128** [comment]
@JerryShea its okay but this operation is slower then just peek last element.
Why do we need 2 operation ? I just want to get last object on queue then when i do operations safe i will remove it manually.
Seems like Transaction.
I think this one is faster.
You are making fast queue so just adding 1 more method can be more good for your queue.

**Comment by JerryShea** [comment]
@eix128 you can't remove elements from the queue. I am closing this - please use stackoverflow for asking usage questions
