### ISSUE TITLE
Implement content-based limiting for ChronicleReader

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1031]
You should be able to specify a limiter that will stop the chronicle reader. E.g. EventDateLimiter that can halt reading when it reaches a certain date.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21.97](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21.97), [BOM-2.21.262](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.262)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.19](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.19), [BOM-2.22.133](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.133)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21.98](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21.98), [BOM-2.21.263](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.263)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea3](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea3), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea2), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
