### ISSUE TITLE
Cannot compile quick start example

### ISSUE THREAD

**Issue by ccnlui** [OpenHFT/Chronicle-Queue#1050]
I'm very excited to try this library, but I can't even get pass the quick start tutorial. Sorry if this is a beginner mistake.

I use maven to download the library as follow:

```xml
<!-- https://mvnrepository.com/artifact/net.openhft/chronicle-queue -->
<dependency>
  <groupId>net.openhft</groupId>
  <artifactId>chronicle-queue</artifactId>
  <version>5.23ea3</version>
</dependency>
```

Then I tried to create a queue:
```java
public class App
{
    public static void main( String[] args )
    {
        String basePath = "./getting-started";
        ChronicleQueue queue = SingleChronicleQueueBuilder.single(basePath).build();
    }
}
```

Compile as follow, then I get a compilation error!
```
$ mvn clean compile
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] <path>/App.java:[18,59] cannot access net.openhft.chronicle.core.util.Builder
  class file for net.openhft.chronicle.core.util.Builder not found
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.463 s
[INFO] Finished at: 2022-04-14T14:59:59-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project chronicleq: Compilation failure
[ERROR] <path>/App.java:[18,59] cannot access net.openhft.chronicle.core.util.Builder
[ERROR]   class file for net.openhft.chronicle.core.util.Builder not found
```

I tried:
- specifying a different chronicle-queue version
- download latest chronicle-core as a dependency (which helps me get passed this error but leads to another compilation error that says something missing from chronicle-wire, then I downloaded the latest chronicle-wire too but that leads to another compilation error again...)

Am I missing some libraries needed to run this very simple example? I'd really appreciate some explicit instructions on how to download all the required libraries just to run this quick start code.

I'd also appreciate if there's advice on the recommended build tools, to eliminate extra variability. Thank you!

System:
MacBook Pro Apple M1
OpenJDK Runtime Environment Temurin-18+36 (build 18+36)
OpenJDK 64-Bit Server VM Temurin-18+36 (build 18+36, mixed mode)
Apache Maven 3.8.5

**Comment by JerryShea** [comment]
@ccnlui it looks like maven is not bringing in the required dependencies for CQ - the `net.openhft.chronicle.core.util.Builder` class is in chronicle-core. I don't know why maven has not automatically brought in the transitive dependencies.

I just tried quick start with a maven archetype and I saw the same, but when I manually included chronicle-wire e.g.
```
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-wire</artifactId>
            <version>2.23ea4</version>
        </dependency>
```
then it brought in the other required dependencies.

Good luck with your evaulation! In future please ask questions on stackoverflow :)

**Comment by alamar** [comment]
@ccnlui You should also be able to add `<classifier>all</classifier>` to your queue dependency block to make it work.

**Comment by alamar** [comment]
@ccnlui Starting with `chronicle-queue` `5.23ea5` no classifier should be required, all dependencies should be resolved transitively. Thank you for noticing this.
