### ISSUE TITLE
Address // TODO: x.23 comments

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1052]

**Comment by RobAustin** [comment]
can this issue be closed ?

**Comment by alamar** [comment]
I think we should close it, even if there are any left, they would be only addressed in 2.24 now

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea7](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea7), [BOM-2.23ea42](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea42)
