### ISSUE TITLE
Index2Index documentation

### ISSUE THREAD

**Issue by DaanA32** [OpenHFT/Chronicle-Queue#1056]
Hi all,

The [how it works](https://github.com/OpenHFT/Chronicle-Queue/blob/ea/docs/How_it_works.adoc) documentation [explains how the index2Index is formatted](https://github.com/OpenHFT/Chronicle-Queue/blob/ea/docs/How_it_works.adoc#tiered-indexing) in the queue.
I don't quite understand how to use / read it from an external program (ie not using chronicle queue).
The example given is simple, it has only one entry on both the primary and final level index. It would be nice if you could explain how to use it in case there are more.

**Comment by RobAustin** [comment]
the index2Index is an internal data structure used by the chronicle queue, we suggest you don't attempt to access it directly as we may change how the queue indexes its entries in the future
