### ISSUE TITLE
is there still a prefetching function?  if not, can the performance be guaranteed?

### ISSUE THREAD

**Issue by lfjbb** [OpenHFT/Chronicle-Queue#1057]
is there still a prefetch, I can't find the code any more.  the PrefetchingMappedFileCache class is deleted.
if no prefetch,  can the performance be guaranteed?

**Comment by JerryShea** [comment]
@lfjbb please search for "pretoucher" in the documentation. Please ask questions on stackoverflow in future :)

**Comment by lfjbb** [comment]
> @lfjbb please search for "pretoucher" in the documentation. Please ask questions on stackoverflow in future :)

thanks
