### ISSUE TITLE
The binary compatibility tool does not check the package net.openhft.chronicle.queue.impl

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Queue#1060]
Packages matching "*impl*" and "*internal*" are not checked. Yet, there are public methods in the "*impl*" package.

The root problem is that public classes reside in an "impl" package (like `SingleChronicleQueueBuilder` ) and these should be migrated out and they should be split up into interfaces (in the public API) and implementing classes (in the internal package).

**Comment by minborg** [comment]
This can be fixed once https://github.com/OpenHFT/Binary-Compatibility-Enforcer-Plugin/issues/8 is fixed

**Comment by RobAustin** [comment]
@minborg is this issue fixed, can this issue now be closed ?

**Comment by minborg** [comment]
It should close automatically once merged to the EA branch:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/7457876/167136870-0fefe357-6c0c-44f7-97e4-2c336612e24f.png">

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea7](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea7), [BOM-2.23ea42](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea42)
