### ISSUE TITLE
Backward tailer not releasing the file when closed

### ISSUE THREAD

**Issue by ajax-lizogubenko-s** [OpenHFT/Chronicle-Queue#1073]
Chronicle queue version: 5.22.18

We are experiencing huge problems with files rollover.
We creating one utility tailer with SingleChronicleQueue.createTailer() perform some readText() operation with BACKWARD direction and then closing it with close() method. 
Unfortunately we can see that last file that was read by Tailer stays blocked:
<img width="1302" alt="Screenshot 2022-05-09 at 12 07 25" src="https://user-images.githubusercontent.com/91266605/167378319-fe20f1a2-8900-4207-98c0-196d905eb4bf.png">
So we can't remove old files, cause last one is being locked. And we need to remove old files

File being released only after application restart

UPD: looks like countExcerpts() has the same problem

**Comment by JerryShea** [comment]
@ajax-lizogubenko-s now that #1148 is fixed, can you re-try this with the latest version?

**Comment by nicktindall** [comment]
The problem with `countExcerpts()` will persist in x.23 because it uses `acquireTailer()`. It's fixed in x.24ea but we should backport the changes to stop using `acquireTailer()` to x.23 if we want it to not leave file handles open.

**Comment by JerryShea** [comment]
No response received from original poster, so closing as assuming fixed by #1148
