### ISSUE TITLE
Cache queue and tailer so ChronicleHistoryReader#readChronicle can be called repeatedly

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1102]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea8](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea8), [BOM-2.23ea68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea68)
