### ISSUE TITLE
ChronicleHistoryReader.withStartIndex

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1118]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea22](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea22), [BOM-2.23ea83](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea83)
