### ISSUE TITLE
Add support for recording the last index to be MSynced

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#1124]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea30), [BOM-2.23ea105](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea105)
