### ISSUE TITLE
Message missed during file roll over.

### ISSUE THREAD

**Issue by skaminen** [OpenHFT/Chronicle-Queue#1135]
Hi ,

We have a 2 process model. A Inbound process writes messages to chronicle que. The Outbound process is reading messages from chronicle que. Both inbound and outbound are running on same box. Both outbound and Inbound process makes sure all messages are processed by checking a sequence number in the message. We are noticing that sometimes the very first message after file rollover is missed by outbound process. If we copy chronicle files to a different box and read them to check, we see the missing message is in the files. The outbound process somehow did not get callback.

We are using below version of chronicle

<dependency>
  <groupId>net.openhft</groupId>
  <artifactId>chronicle-queue</artifactId>
  <version>5.21ea8</version>
</dependency>

Reads are done using below method. 

long curIndex = -1 ;
try (DocumentContext dc = tailer.readingDocument()) {
    if (dc.isPresent()) {
        Bytes bytes = dc.wire().bytes();
        wireMessage.readMarshallable(bytes) ;
        curIndex = dc.index() ;
    }
}
return curIndex ;

**Comment by JerryShea** [comment]
I would try on a more recent version as that version is old and there have been numerous fixes since then

**Comment by RobAustin** [comment]
closing, as this is likely fixed in a newer version, please reopen if this is not the case

**Comment by skaminen** [comment]
Thanks.

Looks like newer version has fixed the issue. no occurrences of the issue after the update.

Thanks,
