### ISSUE TITLE
symmetric replication

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [OpenHFT/Chronicle-Queue#114]
would it be possible for Chronicle-Queue to provide symmetric replication, as in Chronicle-Map?
example use case: http://stackoverflow.com/questions/27607568/fast-queue-on-top-of-chronicle-map
that is, HA queue fail over w/o need for master/slave role re-configuration on failure

**Comment by peter-lawrey** [comment]
bump. still planned.
