### ISSUE TITLE
When Tailers or Appenders roll to a new cycle they leave file handles open

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1148]
Queue has a `ReferenceCountedCache` which keeps a `MappedFiles` in it for each roll cycle that's currently loaded. When Tailers and Apenders get to the end of a cycle and roll to the new one a flush is triggered on that cache when the new cycle's `MappedFile` is created, unfortunately at that stage there are still a number of live references to previous cycle's `MappedFile`.

The stale handles for cycle N will be released when N+2 is acquired, but for a daily roll cycle that could be 24 hours away.

We need to trigger a further flush once the final references to the previous cycle are released. Which happens AFTER the new cycle is loaded.

This may be the root cause of #1073

**Comment by JerryShea** [comment]
This may also be root cause of #980

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.24](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.24), [BOM-2.22.157](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.157)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea32](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea32), [BOM-2.23ea112](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea112)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.25](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.25), [BOM-2.22.158](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.158)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea34](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea34), [BOM-2.23ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea121)
