### ISSUE TITLE
Pretoucher: enabling earlyAcquireNextCycle causes Tailers to skip over messages

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1157]
When a pre-toucher is running on a queue and `earlyAcquireNextCycle` is enabled, any Tailer reading from it can skip over messages when it hits the end of a roll cycle and sees the next one available.

This is trivially reproducible in https://github.com/OpenHFT/Chronicle-Queue/pull/1156/files and https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/pull/347

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.28](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.28), [BOM-2.22.162](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.162)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.37](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.37), [BOM-2.23.135](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.135)
