### ISSUE TITLE
Fix SingleChronicleQueueTest#mappedSegmentsShouldBeUnmappedAsCycleRolls

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1163]
This was un-ignored prematurely in #1152

This test should be reviewed in conjunction with other tests related to #1158

**Comment by JerryShea** [comment]
@alamar FYI I ran this test locally and it worked, so I un-ignored it. Unfortunately it was flaky in TeamCity so I re-ignored it; I'm afraid I didn't have the time to investigate.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea5](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea5), [BOM-2.24ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea17)
