### ISSUE TITLE
Deprecate Pretoucher

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1177]
And move to Queue Enterprise

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.36](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.36), [BOM-2.23.127](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.127)
