### ISSUE TITLE
Zero length file in log folder prevents correct functioning of the library on startup

### ISSUE THREAD

**Issue by smiklosovic** [OpenHFT/Chronicle-Queue#1205]
Hi,

I am from Apache Cassandra project and we hit this issue (see the stack trace).

It seems to me that this library does not correctly handle a case when there is an empty file to append to and it seems like it races.

We are using version 5.20.123

https://issues.apache.org/jira/browse/CASSANDRA-17933

**Comment by JerryShea** [comment]
@smiklosovic I believe that the fix for https://github.com/OpenHFT/Chronicle-Queue/issues/1291 would likely have made Chronicle Queue be able to withstand this and self-heal. Sorry for the delay in responding!
