### ISSUE TITLE
EventLoop gets stuck at entryCount in chronicle queue 5.22.24

### ISSUE THREAD

**Issue by chaitas90** [OpenHFT/Chronicle-Queue#1215]
This is how we are creating chronicle queue..

eventStore = SingleChronicleQueueBuilder.binary(GlobalConstants.CURRENT_DIR + GlobalConstants.PATH_SEPARATOR + EventBusConstants.EVENT_DIR + GlobalConstants.PATH_SEPARATOR+ eventType).rollCycle(RollCycles.MINUTELY).build();
appender = eventStore.acquireAppender();
                
This is thread dump of particular Eventloop that gets stuck at following method entryCount as follows:

Name: vert.x-eventloop-thread-1
State: RUNNABLE
Total blocked: 61,281  Total waited: 27,803
Stack trace:
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:1103)
app//net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:53)
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.storeForCycle(SingleChronicleQueue.java:580)
app//net.openhft.chronicle.queue.impl.single.StoreTailer.cycle(StoreTailer.java:1109)
app//net.openhft.chronicle.queue.impl.single.StoreTailer.moveToCycleResult0(StoreTailer.java:639)
app//net.openhft.chronicle.queue.impl.single.StoreTailer.moveToCycle(StoreTailer.java:614)
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.approximateExcerptsInCycle(SingleChronicleQueue.java:608)
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.exceptsPerCycle(SingleChronicleQueue.java:595)
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.countExcerpts(SingleChronicleQueue.java:713)
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.entryCount(SingleChronicleQueue.java:820)
app//com.mindarray.eventbus.EventEngine.lambda$start$15(EventEngine.java:594)
app//com.mindarray.eventbus.EventEngine$$Lambda$865/0x0000000801061a80.handle(Unknown Source)
app//io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
app//io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
app//io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137)
app//io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:72)
app//io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43)
app//io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98)
app//io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
app//io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
app//io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49)
app//io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$293/0x0000000800e83a80.run(Unknown Source)
app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

This is code where it is used ...

> _vertx.eventBus().<Void>localConsumer(EventBusConstants.EVENT_ENGINE_STATISTICS, event ->
                    vertx.eventBus().publish(Bootstrap.bootstrapType() == GlobalConstants.BootstrapType.COLLECTOR ? EventBusConstants.EVENT_REMOTE : EventBusConstants.EVENT_ENGINE_STATISTICS_RESPONSE,
                            CommonUtil.transformEvent(serializationUtil,new JsonObject().put(EventBusConstants.EVENT_TYPE, EventBusConstants.EVENT_ENGINE_STATISTICS).put(EventBusConstants.ENGINE_TYPE,eventType).put(RemoteEventProcessor.REMOTE_EVENT_PROCESSOR_UUID, Bootstrap.getRegistrationId())
                                  .put(HealthUtil.HEALTH_STATISTICS, new JsonObject().put("pending.events",**eventStore.entryCount()**)_ (**Eventloop Waiting Here**)
                                            
We use this eventstore object in single verticle only so single thread is used for accessing the same recyling of previous stores creating new store happens in single verticle or single thread..

Please let us know what can be done..

Thanks

**Comment by JerryShea** [comment]
@chaitas90 what do you mean by "get stuck"? Which version of CQ are you using?

**Comment by chaitas90** [comment]
> @chaitas90 what do you mean by "get stuck"? Which version of CQ are you using?

I am using it with [vert.x](https://github.com/eclipse-vertx/vert.x) and it is blocking my thread at 
app//net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.entryCount(SingleChronicleQueue.java:820)
CQ version is 5.22.24..
After restarting server it starts working as expected and after some time issue occurs again..

**Comment by JerryShea** [comment]
How long does it block for? If you grab a few stack traces is it always blocked at the same place? Your first stack trace said it was blocked at `SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:1103)`. I believe this is `                            wire.readFirstHeader(timeoutMS, TimeUnit.MILLISECONDS);` - please confirm that is true in your version. 

That line does not block, it goes around a loop for `timeoutMS`. If it doing this it is likely that something crashed and left a lock. Once `timeoutMS` has passed it will recover the lock.

**Comment by JerryShea** [comment]
See also https://github.com/OpenHFT/Chronicle-Queue/pull/1222

**Comment by JerryShea** [comment]
@chaitas90 Can you try this with the latest version - there is some better logging from #1222 

I suspect that another process died and left a lock on the file.

**Comment by JerryShea** [comment]
No response received, so closing. @chaitas90 please re-open if you find a problem
