### ISSUE TITLE
Inconsistent overlapSize calculation

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1220]
`overlapSize` was being calculated twice differently

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea1), [BOM-2.24ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea6)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.37](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.37), [BOM-2.23.135](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.135)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.29), [BOM-2.22.166](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.166)
