### ISSUE TITLE
Put esoteric/test/legacy roll cycles a little more out-of-reach

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1221]
The RollCycles enum contains definitions for a bunch of common roll cycles. It also includes some definitions for legacy roll cycles, test roll cycles and some specialised roll cycles for unusual configurations.

Currently if you're looking at the decompiled RollCycles class there's no indication of which ones you should probably use (it's explained in JavaDoc) and getting it wrong can have some unexpected results.

The plan is to leave the "common"/"sensible" set of roll cycles in the RollCycles enum and move the more specialised ones out to separate enums to make it clear that choosing them means you're going somewhat "off piste".

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea1), [BOM-2.24ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea6)
