### ISSUE TITLE
FileUtilTest sometimes takes a very long time to run

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1234]
It appears that `lsof` is blocking/hanging. See https://teamcity.chronicle.software/buildConfiguration/Chronicle_BuildAll_OpenHFTJava11Bumped/743865?buildTab=tests&status=all&orderBy=duration&order=desc

Suggest we consolidate FileUtil & MappedFileUtil (but use MappedFileUtil's approach of using `/proc/self/maps` to work around `lsof` hanging).

FileUtil was introduced in #636, has documentation and is part of the public API, but is not used anywhere in our other libraries

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea2), [BOM-2.24ea9](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea9)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.37](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.37), [BOM-2.23.135](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.135)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.29), [BOM-2.22.166](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.166)
