### ISSUE TITLE
SingleChronicleQueueBuilder should choose the implementation after config options are loaded from existing metadata

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Queue#1244]
Exisitng `metadata.cq4t` may have some enterprise-only features configured.
If we initialize a queue with `SingleChronicleQueueBuilder.binary(path).build()`, relying on reloading the config from disk, we may choose an incorrect queue implementation.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea3](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea3), [BOM-2.24ea10](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea10)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22.29), [BOM-2.22.166](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.166)
