### ISSUE TITLE
Calling startExceprt() twice results in weird state for IndexedExcerptAppender

### ISSUE THREAD

**Issue by jamie-walker** [OpenHFT/Chronicle-Queue#125]
If you call `startExcerpt()`, write some bytes, then call `startExceprt()` again (without calling `finish()`), you end up in a funny state.

In Chronicle 1.x the second call to `startExcerpt()` would move the position of the Excerpt back to the start and the already written bytes would be discarded.

I liked this behaviour so I was thinking a fix would be to add something like:

    if (!finished) {
        position(0);
    }

We just added the above workaround in our code but it would be easy for us to miss somewhere.

**Comment by peter-lawrey** [comment]
Queue v4 does have startExcerpt. Instead it use lambdas or try-with-resource semantics. to avoid this sort of issue.
