### ISSUE TITLE
ChronicleReader support named tailer

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1277]
To allow resumption

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea7](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea7), [BOM-2.24ea33](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea33)
