### ISSUE TITLE
Remove automatic roll shrinking code

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1280]
It is not sufficiently tested and, worse of all, Tailer will un-shrking a roll when opening it.

Let's keep it as an utility which may be called for archiving purposes for now.

**Comment by alamar** [comment]
See #1275

**Comment by alamar** [comment]
See also #1276

**Comment by alamar** [comment]
I'm not sure how to implement a stand-alone utility - currently, the implementation relies on knowing the end of stream position, later on we don't know such position and don't want to write extra code to iterate the queue and find it out.

Will submit complete removal of that code - may be reinstated once #1276 is taken care of in the future

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea9), [BOM-2.24ea43](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea43)
