### ISSUE TITLE
JDK 18/19 support

### ISSUE THREAD

**Issue by RoopeHakulinen** [OpenHFT/Chronicle-Queue#1286]
Are there any plans to support JDK 18 and later versions? 

We use only a subset of the APIs, but in our use case, JDK 18 seems to work fine. 

JDK 19 is not working at all.

**Comment by JerryShea** [comment]
We plan to support the [next LTS version of Java (21) soon after it is released](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Java-Version-Support.adoc). Until then, Javas 18, 19 etc are not officially supported, although we will from time to time merge in PRs to address compatibility issues, which I expect is why Java 18 is working OK for you.
If you need Java 19 support then it may be worth exploring the [support options](https://chronicle.software/support/), and we are always open to PRs from users.
