### ISSUE TITLE
headerRecovery proceeds regardless if lock was acquired

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1296]
In `SingleChronicleQueue#headerRecovery` we proceed with the header recovery regardless of if we were able to get an exclusive lock on the file. It doesn't look like this has ever happened because it would result in a NullPointerException in the finally block, but we should fix it regardless.

https://github.com/OpenHFT/Chronicle-Queue/blob/e28b18f033dbcadd970b00d12c423833154263ea/src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java#L1085-L1118

After line 1086 we should first check that `fileLock` is not null to confirm we were able to get the lock.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.42](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.42), [BOM-2.23.153](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.153)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea8](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea8), [BOM-2.24ea41](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea41)
