### ISSUE TITLE
"Not yet implemented " exception in queue.clear()

### ISSUE THREAD

**Issue by smiley886** [OpenHFT/Chronicle-Queue#1303]
To avoid reading and writing data directly from disk, I created a SingleChronicleQueue object as a cache, but when I call queue.clear(), it reports "UnsupportedOperationException: Not yet implemented " exception. Can you give me some hints?

**Comment by smiley886** [comment]
I didn't figure out how to clear the queue.

**Comment by JerryShea** [comment]
CQ is designed to be an append-only event store. I am not sure why that clear method exists - it should probably be removed. @peter-k-lawrey what do you think?

We don't have a mechanism to remove items from the queue.

You may want to look at Chronicle Map instead for your use case
