### ISSUE TITLE
Optimise normaliseEOFs

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1306]
`normaliseEOFs` runs from the first cycle to the (current - 1) cycle writing any missing EOFs. This can take a significant amount of time on a queue with many historic roll cycles present. It shouldn't be necessary if we ensure the previous roll cycle has an EOF prior to writing any entries to a new one.

We will still need to keep the corrective action for queues created by old versions that did not ensure this, but we only need to do that scan once.

-- Details to follow --

**Comment by alamar** [comment]
This may clash with earlyAcquire pretoucher, so you need to at least touch two last cycles. In case of crash you may need to go through more than two cycles.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.43](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.43), [BOM-2.23.157](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.157)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea10](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea10), [BOM-2.24ea46](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea46)
