### ISSUE TITLE
Chronicle Queue with jdk 16

### ISSUE THREAD

**Issue by rupinder10** [OpenHFT/Chronicle-Queue#1309]
I have been struggling with moving to jdk 16 from jdk8. Some test cases keep failing with jdk16 and 17.

The line of code in the tests where I run into a problem is:

`SingleChronicleQueueBuilder.binary(filepath);`

and the error is:

`java.lang.NoClassDefFoundError: Could not initialize class net.openhft.chronicle.wire.WireType
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:214)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:210)`

The gradle build has the following snippets for the relevant dependencies and the changes for jdk 16.

`localDependencies group: 'net.openhft', name: 'chronicle-queue', version: '5.19.2'`
`localDependencies group: 'net.openhft', name: 'chronicle-bytes', version: '2.19.1'`
`localDependencies group: 'net.openhft', name: 'chronicle-core', version: '2.19.0'`
`localRuntimeDependencies group: 'net.openhft', name: 'chronicle-wire', version: '2.19.0'`
`localRuntimeDependencies group: 'net.openhft', name: 'chronicle-threads', version: '2.19.0'`
`localRuntimeDependencies group: 'net.openhft', name: 'affinity', version: '3.2.2'`

After digging in I found this is an issue only with JDK 16 onwards. It works with DK 8, 9 and 11. The actual error is :
`java.lang.AssertionError: java.lang.NoSuchFieldException: address
	at net.openhft.chronicle.core.Jvm.getField(Jvm.java:369)
	at net.openhft.chronicle.core.Jvm.getField(Jvm.java:366)
	at net.openhft.chronicle.core.Jvm.getField(Jvm.java:366)
	at net.openhft.chronicle.bytes.NativeBytesStore.<clinit>(NativeBytesStore.java:49)
	at net.openhft.chronicle.bytes.BytesStore.from(BytesStore.java:52)
	at net.openhft.chronicle.wire.WireType.<clinit>(WireType.java:328)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:214)
	`

**Comment by JerryShea** [comment]
We support Java 8, 11 and 17 - the LTS versions.

You are welcome to provide a patch to help us support Java 16 :)

**Comment by rupinder10** [comment]
Thanks @JerryShea. But I get he same error with Java 17 too. OpenJDK 17. To be precise the version is "OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)"

My hunch is that I have to make some changes to support Java 17, if you say that is supported,  and I am looking for some guidance. 

I currently have this in my gradle file:

`implementation group: 'net.openhft', name: 'chronicle-queue', version: '5.19.2'`
`implementation group: 'net.openhft', name: 'chronicle-bytes', version: '2.19.1'`
`implementation group: 'net.openhft', name: 'chronicle-core', version: '2.19.0'`
`implementation group: 'net.openhft', name: 'chronicle-wire', version: '2.19.0'`
`implementation group: 'net.openhft', name: 'chronicle-threads', version: '2.19.0'`
`implementation group: 'net.openhft', name: 'affinity', version: '3.2.2'`

And if I change the versions, do I also have to make any other changes like -add-opens ? And does the Java 17 compatible version run with Java 8 and 11 or is it limited to Java 17 ?

**Comment by JerryShea** [comment]
@rupinder10 see https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc. You are using a very old version that won't work with Java 17
