### ISSUE TITLE
VanillaChronicle JVM Crash in 3.3.4

### ISSUE THREAD

**Issue by nyluke** [OpenHFT/Chronicle-Queue#131]
Seems this may have been the first write after midnight..

RAX=0x000000065a97e950 is an oop
net.openhft.lang.io.VanillaMappedBytes 
 klass: 'net/openhft/lang/io/VanillaMappedBytes'
RBX=0x000000000000001f is an unknown value
RCX=0x0000000000000020 is an unknown value
RDX=0x0000000672c7f6d0 is an oop
java.util.LinkedHashMap$Entry 
 klass: 'java/util/LinkedHashMap$Entry'
RSP=0x00007f20585dbf40 is pointing into the stack for thread: 0x00007f2065f2f800
RBP=0x00000000ce4f7a02 is an unknown value
RSI=0x00000006727bd010 is an oop
net.openhft.chronicle.VanillaChronicle$VanillaAppenderImpl 
 klass: 'net/openhft/chronicle/VanillaChronicle$VanillaAppenderImpl'
RDI=0x0000000000000016 is an unknown value
R8 =0x00007f1fe0000030 is an unknown value
R9 =0x0000000000000007 is an unknown value
R10=0x00007f1fe000000c is an unknown value
R11=0x00007f1fe000000c is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000000 is an unknown value
R14=0x0000000000000049 is an unknown value
R15=0x00007f2065f2f800 is a thread

Stack: [0x00007f20584dd000,0x00007f20585de000],  sp=0x00007f20585dbf40,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 5553 C2 Writer.put([BIIB)V (109 bytes) @ 0x00007f212152cb9f [0x00007f212152cae0+0xbf]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x600085]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x365
V  [libjvm.so+0x5feae8]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.so+0x639564]  jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x2b4
V  [libjvm.so+0x648481]  jni_CallVoidMethod+0x171

vm_info: Java HotSpot(TM) 64-Bit Server VM (24.71-b01) for linux-amd64 JRE (1.7.0_71-b14), built on Sep 26 2014 16:41:40 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)

time: Sat Jan 24 00:00:47 2015

**Comment by peter-lawrey** [comment]
The most common cause of this error has been closing the queue in one
thread while accessing it in another. We have attempted to prevent it
causing this error.
Can you describe what you are doing or provide a test to reproduce this?

**Comment by nyluke** [comment]
I'm not exactly sure since it was a running system that I was not monitoring. I don't believe I'm calling close() anywhere. I can only guess that some data came in at that time and there was an attempt to write it to the queue. Note that there may have been multiple threads writing to the same queue at the same time. The crash happens from time to time but so far I'm not able to reproduce it.

**Comment by peter-lawrey** [comment]
Ok. The indexed chronicle is single writer and you can instance for each
thread, however vanilla chronicle is safe for concurrent use. Which
chronicle are you using?

**Comment by nyluke** [comment]
I'm using VanillaChronicle because I need the rolling feature.

**Comment by lburgazzoli** [comment]
Would be possible to see how the appender are created and used? 

VanillaChronicle supports concurrent access but you can't share the same appender among threads, in that case the behavior is unpredictable.

**Comment by nyluke** [comment]
Ah, ok that's probably my issue then. I'll test with one appender per thread and provide an update.

**Comment by peter-lawrey** [comment]
If you call chronicle.createAppender() in each thread, it will give you a
ThreadLocal instance.

**Comment by nyluke** [comment]
I reproduced the issue with multiple threads using the same appender, so creating multiple appender instances on the same queue instead seems to fix the problem. Leaving the issue open in case you want to handle this. Thanks.

**Comment by nyluke** [comment]
Have you seen this one also? 

Stack: [0x00007fd7bfdfe000,0x00007fd7bfeff000],  sp=0x00007fd7bfefce60,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~StubRoutines::jbyte_disjoint_arraycopy

RAX=0x0000000702646196 is an unknown value
RBX=0x00000006ac6439a8 is an oop
net.openhft.chronicle.VanillaChronicle$VanillaAppenderImpl
 - klass: 'net/openhft/chronicle/VanillaChronicle$VanillaAppenderImpl'
RCX=0x0000000000000106 is an unknown value
RDX=0xfffffffffffffff0 is an unknown value
RSP=0x00007fd7bfefce60 is pointing into the stack for thread: 0x00007fd6d59d6000
RBP=0x00007fd7bfefce60 is pointing into the stack for thread: 0x00007fd6d59d6000
RSI=0x00007fd683c880a9 is an unknown value
RDI=0x0000000702646188 is an unknown value
R8 =0x0000000000000106 is an unknown value
R9 =0x0000000000010000 is an unknown value
R10=0x00007fd7e1042a20 is at begin+0 in a stub
StubRoutines::unsafe_arraycopy [0x00007fd7e1042a20, 0x00007fd7e1042a5b[ (59 bytes)
R11=0x00007fd683c87fb0 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000004 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x00007fd6d59d6000 is a thread

**Comment by peter-lawrey** [comment]
Do you have the stack trace in the dump?

The most common causes of this type of issue are;
- you run out of disk space or
- you close the queue in another thread while it is being used.

We are working on ways to resolve these issues. You may have found a new
situation so it is worth looking at more closely.

**Comment by nyluke** [comment]
That's actually all I have for the stack which is odd. But actually I think you're right that it was simply disk space.

**Comment by peter-lawrey** [comment]
We are adding a check to warn you if you are running out of space or even
stop the queue.

**Comment by peter-lawrey** [comment]
File rolling has been completely redone in Queue v4.
