### ISSUE TITLE
Instead of recovering header, rename file then create a new one

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1313]
Make sure concurrent creation is handled as well

see also https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/issues/415

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea10](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea10), [BOM-2.24ea46](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea46)
