### ISSUE TITLE
WriteAfterEOFException thrown by writingDocument() leaves queue lock locked

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1324]
When an attempt is made to write to an EOF'd roll cycle, `WriteAfterEOFException` is thrown and it leaves the write lock locked. While unlikely to occur, this shouldn't leave the queue in a non-writable state.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.45](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.45), [BOM-2.23.166](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.166)
