### ISSUE TITLE
Check if directory listing checks may be skipped

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1355]
Right now we skip table store listings if force flag is off, but we do not do the same for file system directory listings - need to check if that is possible.

See #1335

**Comment by alamar** [comment]
I believe the current state of affairs is as follows:
`FileSystemDirectoryListing` implementation is safe, slow option that ignores (non)force flag and always refreshes.
`TableDirectoryListing` implementation adds additional consistency check on top of queue to make sure it can take advantage of force flag to skip non-essential refreshes.
So if queue segment pinballing is expected, then the latter should be used to see the best performance.
Porting of force-skip to the former without corresponding additional check seems like a bad option.

See #1357
@JerryShea

**Comment by JerryShea** [comment]
The resolution to this problem (and #1336) was to modify `TableStoreDirectoryListing` to work for read-only queues. This also gives better performance for read-only queues.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea18](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea18), [BOM-2.24ea66](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea66)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.46](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.46), [BOM-2.23.177](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.177)
