### ISSUE TITLE
deprecate ChronicleQueue#acquireAppender

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1361]
This method call returns a thread local and some customers have been surprised by the implications.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea21](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea21), [BOM-2.24ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea72)
