### ISSUE TITLE
ExcerptTailer#readingDocument throws if you're reading backwards and you get to zero

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1370]
When reading backwards through a queue whose first index is 0, an exception is thrown by `ExcerptTailer#readingDocument()` when you attempt to read past index 0.

I would expect the behaviour to be the same as reaching the end of a queue in FORWARD direction, where readingDocument just returns a document for which `#isPresent()` is false.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea19](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea19), [BOM-2.24ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea69)
