### ISSUE TITLE
Deprecate queueLock for removal in x.25

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1377]
`SingleChronicleQueue#queueLock()` has been long superseded by replication heartbeat. Deprecate it for removal in x.25

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea19](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea19), [BOM-2.24ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea69)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea20](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea20), [BOM-2.24ea70](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea70)
