### ISSUE TITLE
ZippedDocumentAppender should cancel system.out.println

### ISSUE THREAD

**Issue by bwzhang2011** [OpenHFT/Chronicle-Queue#138]
when read ZippedDocumentAppender resource, at line 103 there exists the system.out.println sentence which I think need to be canceled or dropped. is it right ?

**Comment by peter-lawrey** [comment]
Sounds like a debug statement which should be removed. Can you issue a pull
request?

**Comment by BoundedBuffer** [comment]
Currently this is work in progress.
