### ISSUE TITLE
Ensure all logging around lock forcing/timeout is at WARN

### ISSUE THREAD

**Issue by rogersimmons** [OpenHFT/Chronicle-Queue#1380]
There has already been some change in this area. An example from earlier:
https://github.com/OpenHFT/Chronicle-Queue/blob/5ac5d1884d066e86cb6eae345d843cb0e079280d/src/main/java/net/openhft/chronicle/queue/impl/table/AbstractTSQueueLock.java#L118

Pls review to ensure all logging around lock forcing/timeout is at WARN

**Comment by JerryShea** [comment]
I believe this has been addressed by https://github.com/OpenHFT/Chronicle-Queue/commit/4f091992519bcc571245c0b6f3fedeea4f69359f
