### ISSUE TITLE
Remove unused throwExceptionIfClosed calls

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Queue#1386]
There are a number of commented out or unused sections of the code. Removing these can improve readability and maintainability.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea22](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea22), [BOM-2.24ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea72)
