### ISSUE TITLE
ReadOnly test fails on Windows

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Queue#1388]
f2efecb7 introduced a new test - `SingleChronicleQueueTest.createAppenderWillThrowWhenQueueIsReadOnly`. This test is failing on Windows 11 builds.

On Windows this test fails because the test is expecting an `IllegalStateException` to be thrown when trying to call `createAppender` when `readOnly=true` is specified in the invocation of the queue builder. However, on Windows `readOnly=true` is not accepted:

````java
    public SingleChronicleQueueBuilder readOnly(boolean readOnly) {
        if (OS.isWindows() && readOnly)
            Jvm.warn().on(SingleChronicleQueueBuilder.class,
                    "Read-only mode is not supported on Windows® platforms, defaulting to read/write.");
        else
            this.readOnly = readOnly;

        return this;
    }
````

This means that in this test on Windows `readOnly` is false and the test does not throw the exception as expected.

The suggested fix is to ignore this test on Windows but we should also have some further discussion about it.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea22](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea22), [BOM-2.24ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea72)
