### ISSUE TITLE
Refactor StoreAppenderContext.close

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Queue#1392]
Refactor `StoreAppenderContext.close` to reduce its complexity.

https://sonarcloud.io/project/issues?issues=AX4OKwQh1B2j6S6ysfp7&open=AX4OKwQh1B2j6S6ysfp7&id=OpenHFT_Chronicle-Queue

![image](https://github.com/OpenHFT/Chronicle-Queue/assets/109181/674304e8-42ce-4528-b8d2-882051f505c6)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea23](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea23), [BOM-2.24ea73](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea73)
