### ISSUE TITLE
Refactor ChronicleReader.execute

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Queue#1394]
Refactor `ChronicleReader.execute` method to simplify flow and remove Sonar warnings:

![image](https://github.com/OpenHFT/Chronicle-Queue/assets/109181/16a8b641-d4c8-4abc-9572-9e417c9a5080)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea23](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea23), [BOM-2.24ea73](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea73)
