### ISSUE TITLE
make SingleChronicleQueueBuilder#drainerPriority() default to null

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1397]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24ea23](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24ea23), [BOM-2.24ea73](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea73)
