### ISSUE TITLE
Thread ID larger than 16 bits leads to FileNotFoundException

### ISSUE THREAD

**Issue by arbitrage33** [OpenHFT/Chronicle-Queue#140]
Using 3.4.0 of the Chronicle Queue, when starting a chronicle if Kernel32.INSTANCE.GetCurrentThreadId() within WindowsJNAAffinity returns an integer larger than 65535 then you will receive an exception such as 
> Exception in thread "main" java.lang.AssertionError: java.io.FileNotFoundException: D:\Chronicle\MD\20150224\data-34788-0	at net.openhft.chronicle.VanillaChronicle$AbstractVanillaExcerpt.index(VanillaChronicle.java:409)
	at net.openhft.chronicle.VanillaChronicle$AbstractVanillaExcerpt.nextIndex(VanillaChronicle.java:423)

Whats quite nasty about this is that everything will work as expected until you hit the uint16 max value + 1'th kernel thread ID, whilst we are not using Windows for production if we did this would be very nasty as it cannot be easily remedied.

It would appear that when determining THREAD_ID_BITS in VanillaChronicle a call to Jvm.PID_BITS is made, whilst the pid's may max out at the specified value thread Id's can and will go higher (the Windows Kernel API call returns a 32bit DWORD) so im not sure if the fix is to increase the Windows value to also be 24 bits as per the Linux change or if other changes are required to separate pids/thread id's.

This pull request previously addressed this issue for Linux OS's
https://github.com/OpenHFT/Chronicle-Queue/pull/64

**Comment by peter-lawrey** [comment]
Queue v4 no longer uses the Thread id.
