### ISSUE TITLE
CPU usage has increased since version 5.24.ea26

### ISSUE THREAD

**Issue by GabryLig** [OpenHFT/Chronicle-Queue#1457]
I noticed that from this version (5.24.ea26) CPU usage has increased by twice.
![image](https://github.com/OpenHFT/Chronicle-Queue/assets/39622519/9e7c14d2-b7be-4ca0-ac99-227db02257ea)

- 5.24.ea26 - Red and Blue
- 5.24.ea25 - Purple

The code is the same for both

**Comment by tgd** [comment]
Hi, please can you share how you are pulling in the Chronicle dependencies? Are you depending on the chronicle-queue artifact directly or using the chronicle-bom?

**Comment by GabryLig** [comment]
Hi Tom, i'm using chronicle-queue artifact directly. Is it a problem to use it like this ? 
Thanks in advance

**Comment by tgd** [comment]
Hi Gabry, thanks for confirming. No its not an issue to not use the bom necessarily it just helps to ensure we are looking at exactly the same versions on our side.

Are you pulling in any other Chronicle dependencies explicitly such as Bytes, Core or Wire? If so please can you also confirm the versions of those.

**Comment by GabryLig** [comment]
No Tom, i'm pulling only chronicle-queue in pom.xml and the dependencies for version **5.24.ea25** are:

![image](https://github.com/OpenHFT/Chronicle-Queue/assets/39622519/6f4d529e-796b-40d8-815f-b1952a7ebb1a)

instead of these for version 5.24.ea26:

![image](https://github.com/OpenHFT/Chronicle-Queue/assets/39622519/554e42d0-938b-4f15-9ff0-82aae4d84ab1)

**Comment by tgd** [comment]
Hi Gabry, I have taken a look through the key changes in between 5.24ea25 and 5.24ea26. There is only one relevant change related to Queue between those versions and it is a only a logging change - https://github.com/OpenHFT/Chronicle-Queue/issues/1416

As it stands I can't see any reason for a performance degradation between these versions. Are you able to reproduce this consistently and do you have any test code to reproduce it?

If you need someone to work through this with you to we do offer support services through our [support page](https://chronicle.software/support/).

**Comment by GabryLig** [comment]
Hi Tom, but as you can see the  **5.24.ea26** are some dependencies more than 5.24ea25. I haven't a consistently tests to reproduce, Below the code that i'm using for polling the queue:


 try (ExcerptTailer tailer = this.queue.createTailer()) {

               Pauser pauser = Pauser.balanced();
                this.setEndPollInQueue(false);

                log.info("{} ({}) -> [{}][{}] Create consumer chunks", HLSUtil.ACRONYM_LOG_HLS, getRecordingId(), getDeviceName(), getNamespace());

                while (!this.isEndPollInQueue()) {
                    try (DocumentContext dc = tailer.readingDocument()) {
                        boolean found = (dc.isPresent());
                        if (found) {
                            //this.readAndSend(session, dc);
                            pauser.reset();
                        } else
                            pauser.pause();

                    }
                }
            }

**Comment by tgd** [comment]
Hi Gabry, I have just re-run some of our internal benchmarks and I cannot see a degradation in them. Thanks for sharing your code, the pauser you choose will play a large part in CPU usage - there are some detailed docs here: https://github.com/OpenHFT/Chronicle-Threads#pausers

If you need some extra help please use the support function on our [support page](https://chronicle.software/support/).

**Comment by GabryLig** [comment]
Hi Tom, thanks for the response. I used always this pauser (balanced) and the CPU worked good. I don't know , I'll investigate .

Thanks.

**Comment by GabryLig** [comment]
Problem solved

**Comment by tgd** [comment]
Thank you @GabryLig for letting us know.
