### ISSUE TITLE
Remove QueueLock

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1461]
The QueueLock was used to prevent writes to the queue while a back-fill was in progress. A better approach was implemented via the replication heartbeat, this indicates to potential writers that the replicator has completed all back-fills and it is safe to write. Writers can choose whether to only write when safe, or write at other times when they know it to be safe.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea0](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea0), [BOM-2.25ea0](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea0)
