### ISSUE TITLE
Remove ParseException from WireStoreSupplier#cycles signature

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1471]
I believe it is not thrown and it is also an abstraction leak.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea1), [BOM-2.25ea1](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea1)
