### ISSUE TITLE
Improve tailer.toEnd() performance for backwards tailers

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Queue#1483]
Improve performance of `tailer.toEnd()` for backwards tailers.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.49](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.49), [BOM-2.23.207](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.207)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea6](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea6), [BOM-2.25ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea23)
