### ISSUE TITLE
Docs: broken internal links 

### ISSUE THREAD

**Issue by j4sm1ne96** [OpenHFT/Chronicle-Queue#1489]
for example missing link on [this page](https://portal.chronicle.software/docs/queue/chronicle-queue/configuration/index-count.html) referring to an indexing section

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea7](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea7), [BOM-2.25ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea23)
