### ISSUE TITLE
Monitoring Index Depth

### ISSUE THREAD

**Issue by pjulien** [OpenHFT/Chronicle-Queue#149]
I have 3 completely independent ``ExcerptTailer``s all reading from the same ``VanillaChronicle`` queue.  The queue itself only has a single writer.

The 3 readers use a single thread each, each using its own isolated tailer to do its work.  I am trying to figure out the best way to monitor their progress.  

Currently I'm doing 

```
tardy = chronicle.lastWritterIndex() - lastConsumedIndex
```

And most of the time that seems to work.  However, when a reader gets too far behind the delta will have a difference in the billions/trillions.

This is because there are two components to the index.  The top 24 bits have the cycle number and the bottom 40 bits have the index in the cycle.

When the index laps, it looks like the difference is in the trillions.  For monitoring purposes, I think it would be valuable to have a good way of doing this.

**Comment by peter-lawrey** [comment]
bump.
we should have better support for this sort of calculations.

**Comment by RobAustin** [comment]
We only support Q4, but the same issue exists in Q4, So I will address it there.
For a given cycle I could provide the number of Excerpt in that cycle. You would then have to aggregate all the intermediate cycles, which means I will also have to tell you which cycles have been written to, between 2 indexes.

**Comment by RobAustin** [comment]
I've created the following method on RollingChronicleQueue

`    /**
     * The number of excerpts between the indexes, {@code index1} inclusive, {@code index2}
     * exclusive.
     *
     * When {@code index1} and {@code index2} are in different cycles which are not adjacent, this
     * operation can be expensive, as the index count for each intermediate cycle has to be found
     * and calculated. As such, and in this situation, it's not recommended to call this method
     * regularly in latency sensitive systems.
     *
     * @param index1 from index, the index provided must exist.  To improve performance no checking
     *               is  carried out to validate if and excerpt exists at this index.
     * @param index2 to index, the index provided must exist. To improve performance no checking is
     *               carried out to validate if and excerpt exists at this index.
     * @return the number of excerpts between the indexes, {@code index1} inclusive, {@code index2}
     * exclusive.
     * @throws java.lang.IllegalStateException if the cycle of {@code index1} or {@code index2} can
     *                                         not be ascertained
     */
    long countExcerpts(long index1, long index2) throws java.lang.IllegalStateException;`

**Comment by RobAustin** [comment]
and the following test case

```
 @Test
    public void testCountExceptsBetweenCycles() throws Exception {

        final Path dir = Files.createTempDirectory("demo");
        final RollCycles rollCycle = RollCycles.TEST_SECONDLY;
        final SingleChronicleQueueBuilder builder = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(rollCycle);
        final RollingChronicleQueue queue = builder.build();
        final ExcerptAppender appender = queue.createAppender();

        long[] indexs = new long[10];
        for (int i = 0; i < indexs.length; i++) {
            System.out.println(".");
            try (DocumentContext writingContext = appender.writingDocument()) {
                writingContext.wire().write().text("some-text-" + i);
                indexs[i] = writingContext.index();
            }

            // we add the pause times to vary the test, to ensure it can handle when cycles are
            // skipped
            if ((i + 1) % 5 == 0)
                Thread.sleep(2000);
            else if ((i + 1) % 3 == 0)
                Thread.sleep(1000);
        }


        for (int lower = 0; lower < indexs.length; lower++) {
            for (int upper = lower; upper < indexs.length; upper++) {
                System.out.println("lower=" + lower + ",upper=" + upper);
                Assert.assertEquals(upper - lower, queue.countExcerpts(indexs[lower],
                        indexs[upper]));
            }
        }

        // check the base line of the test below
        Assert.assertEquals(6, queue.countExcerpts(indexs[0], indexs[6]));

        /// check for the case when the last index has a sequence number of -1
        Assert.assertEquals(queue.rollCycle().toSequenceNumber(indexs[6]), 0);
        Assert.assertEquals(5, queue.countExcerpts(indexs[0],
                indexs[6] - 1));

        /// check for the case when the first index has a sequence number of -1
        Assert.assertEquals(7, queue.countExcerpts(indexs[0] - 1,
                indexs[6]));

    }
```
