### ISSUE TITLE
Allow a fast, less safe append-at-index

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1501]
`StoreTailer#writeBytesInternal` is very paranoid when validating the index it is passed, to ensure it doesn't append at a different index.

Rather than trusting the metadata written to the store file header, it scans through the store to be absolutely certain it's writing at the specified index. This is an expensive operation.

The write could be much faster if we trusted the value in the header, but that comes with risk of validating the specified index against a stale "last index" and performing a write where it should not. In certain circumstances, such as in replication where the sink handler knows it's the only writer to the queue, we can speed things up by using the header value instead of performing the scan.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea7](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea7), [BOM-2.25ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea23)
