### ISSUE TITLE
Tailers can skip unacquirable cycles

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1509]
When reading through a queue, if a cycle is encountered with an incomplete or invalid header, a tailer will pause (for, by default, 10s) waiting for the header to become valid.

The assumption is it has encountered a new roll cycle in the process of being initialised, and the actual wait time will be much shorter.

If a process dies abruptly while initialising a roll cycle it can leave a bad roll cycle that will hold up all readers/appenders for the full 10s, before an appender will go in and rename the file and replace it with a valid one.

[Some work was done recently](https://github.com/OpenHFT/Chronicle-Queue/pull/1368) to better handle missing roll cycles, when a Tailer failed to acquire a cycle it was assumed to be due to the file being missing, so it would skip forward to the next one.

If a Tailer fails to acquire a cycle because it's partly initialised that is indistinguishable from it failing to acquire one because it's missing from disk. In the former case, it's possible that while it was waiting 10s for the header to be complted, that roll cycle was replaced, populated and the following roll cycle was created (most likely in a replication scenario or one with very short roll cycles). In this scenario the tailer would skip over the replacement cycle and miss a bunch of excerpts.

This caused flappiness in UngracefulShutdownTest.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.30), [BOM-2.24.103](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.103)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea9), [BOM-2.25ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea23)
