### ISSUE TITLE
JDK 1.6 supported Chroncile Queue

### ISSUE THREAD

**Issue by pramodbms** [OpenHFT/Chronicle-Queue#152]
Hi,

The latest 3.4.2 chronicle queue is incompatible with jdk 1.6. 

If I have to use chronicle with jdk 1.6, what version should I be using? Also where can I find java docs for a older chronicle version?

**Comment by BoundedBuffer** [comment]
I'm not sure which version dropped 1.6 compatibility, but we only stopped supporting 1.6 recently. I know someone recently ( in the last 4 months or so ) issued a pull request, with some changes to provide support for 1.6. 

I'm currently only on my iphone ( so sorry for not being able to give you an exact answer ), but if you look through GitHub you should see the 1.6 compatibility pull request. 

Rob

**Comment by peter-lawrey** [comment]
Queue 3.x should work on Java 6. However we no longer provide free support for Queue v3.
