### ISSUE TITLE
VanillaChronicle AssertionError

### ISSUE THREAD

**Issue by nyluke** [OpenHFT/Chronicle-Queue#153]
I'm attempting to eliminate latency spikes in VanillaChronicle to more closely match the IndexedChronicle latency profile. Increasing the indexBlockSize and dataBlockSize from their defaults of 16MB and 64MB respectively appears to help, presumably because of less concurrent I/O. However at some point increasing these values eventually results in an AssertionError in a simple test that appends random byte arrays:

Exception in thread "main" java.lang.AssertionError
        at net.openhft.chronicle.VanillaIndexCache.append(VanillaIndexCache.java:203)
        at net.openhft.chronicle.VanillaChronicle$VanillaAppenderImpl.finish(VanillaChronicle.java:625)

Are there some optimal values to increase the size of the index and data files without causing a fault?

**Comment by peter-lawrey** [comment]
I would have said that 1 GiB is as far as you should need to go. The
optimal is likely to be less that this. The OS and the hardware you use all
play a part. Which OS and what sort of disk sub system do you use?

**Comment by nyluke** [comment]
CentOS 7
Intel SSD single disk (ext4)

**Comment by peter-lawrey** [comment]
We test with Centos 6 and ext4 with SSD.

Unless the producer is the source, the source has to wake up or busy wait
to detect if an excerpt has been added. When the source is used for
producing excerpts, it can handle new entries more efficiently in process.

**Comment by nyluke** [comment]
In this case I'm just adding excerpts in a loop as in:
        for (int i = 0; i < TOTAL; i++) {
            appender.startExcerpt(SIZE);
            appender.write(byteArrays[i], 0, SIZE);
            appender.finish();
        }

Would I need to detect whether the excerpt has been added here?

**Comment by peter-lawrey** [comment]
If you write these directly to the source instance it will know when you
perform the write.

If you write this to a file the source has to read it to detect if there is
any thing to replicate, this takes time and it sounds like it is taking too
much time.

**Comment by nyluke** [comment]
Ok, I'm not doing any replication so this should be just writing directly to the data files. Can I bypass the replication steps altogether?

**Comment by lburgazzoli** [comment]
@nyluke, could you please submit a PR with the failing test ? 

The methods that throws the assertion has been updated since its original design to reduce garbage creation and there may be a corner case not properly handled.

**Comment by nyluke** [comment]
Ok I submitted a PR for the AssertionError test. I also have a test using HdrHistogram to measure latency in IndexedChronicle vs VanillaChronicle if you'd like me to submit that.

**Comment by peter-lawrey** [comment]
That also sounds useful. Please add it.

**Comment by nyluke** [comment]
ok, committed on the same branch/PR

**Comment by lburgazzoli** [comment]
I've merged your test cases (disabled at the moment, need to find a way to test this issue faster).

I've fixed the AssertionError you experienced and fixed a performance issue I found while working on this fix: would you be so kind to confirm the AssertionError issue and if it improves latency?

**Comment by nyluke** [comment]
will do

**Comment by nyluke** [comment]
VanillaBlockSizeTest runs longer but still yields the AssertionError..

100000000 written
200000000 written
300000000 written
400000000 written
500000000 written
600000000 written
700000000 written
Exception in thread "main" java.lang.AssertionError
	at net.openhft.chronicle.VanillaIndexCache.append(VanillaIndexCache.java:203)
	at net.openhft.chronicle.VanillaChronicle$VanillaAppenderImpl.finish(VanillaChronicle.java:625)
	at net.openhft.chronicle.VanillaBlockSizeTest.testMaxSize(VanillaBlockSizeTest.java:56)
	at net.openhft.chronicle.VanillaBlockSizeTest.main(VanillaBlockSizeTest.java:68)

**Comment by lburgazzoli** [comment]
Looks like you do not have the latest snapshot/sources as line 203 is not more the location from where the assertion is thrown (and it should also contain some more details)

**Comment by nyluke** [comment]
Sorry about that, yes the AssertionError appears to be resolved. As for latency, I'm getting the following for 100,000,000 excerpts:

Indexed: Mean=933ns  Max=0.66s
Vanilla (defaults): Mean=2236ns  Max=0.75s
Vanilla (1 GB block sizes): Mean=1063ns  Max=0.68s

So far this looks a lot better, thanks!

**Comment by lburgazzoli** [comment]
can I close the issue?

**Comment by nyluke** [comment]
yes everything looks good thanks
