### ISSUE TITLE
toEnd doesn't work when the last roll cycle is empty

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1532]
If the last roll cycle in the queue is empty, `toEnd` is broken.

This is a result of the internal state of the Tailer being made inconsistent by the `approximateLastCycle2` scan.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.33](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.33), [BOM-2.24.105](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.105)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea10](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea10), [BOM-2.25ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea27)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.50](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.50), [BOM-2.23.215](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.215)
