### ISSUE TITLE
When a partial update occurs, we sometimes end up thinking the second last excerpt is the last excerpt

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#1538]
We cache the position/sequence pair of the last excerpt in the queue in the store file header.

It is updated non-atomically with an append.

If the program suffers an abnormal termination it can leave the cached position/sequence pair inconsistent with the actual last excerpt in the queue.

When the pair is updated we merely increment the sequence and write the new position, so this inconsistency is persisted until the end of the roll cycle, and could cause off-by-one entries to be written to the index.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23.50](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23.50), [BOM-2.23.215](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.215)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.34](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.34), [BOM-2.24.109](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.109)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea12](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea12), [BOM-2.25ea32](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea32)
