### ISSUE TITLE
Can't find 5.24 releases

### ISSUE THREAD

**Issue by andrm** [OpenHFT/Chronicle-Queue#1542]
Hi,

I see releases with versions "5.24.x" but I can't seem to find them on maven. 5.25eaX are there. Do I need another repository configuration for 5.24 ?

**Comment by tgd** [comment]
Hi @andrm 

https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc#ea-early-access

> Only EA releases are released to Maven Central. Releases of stable versions (e.g. x.23) are made to Chronicle’s nexus and are available to customers with a commercial agreement.

The above also covers x.24
