### ISSUE TITLE
Chronicle index(long) does not work

### ISSUE THREAD

**Issue by andreas-hess** [OpenHFT/Chronicle-Queue#155]
Hi

I try to build a class behaving like a queue based on chronicle. To do so I need to store the last
read index for re-start.

When I get the index (index()) before reading the first message it is 0 (zero).

Setting the index to 0 (zero) before reading the first message I get already message 2.

Am I missing something?

Using Chronicle-queue 3.4.2 on Linux (Red Hat 6.6)

Thanks
Andreas

**Comment by andreas-hess** [comment]
Create chronicle :

package bug;

import java.io.File;
import java.io.IOException;

import net.openhft.chronicle.Chronicle;
import net.openhft.chronicle.ChronicleQueueBuilder;
import net.openhft.chronicle.ExcerptAppender;

public class CreateChronicle {
    public static void main(String[] args) throws IOException {
        final Chronicle c2s = ChronicleQueueBuilder.indexed(new File(System.getProperty("java.io.tmpdir") + File.separator + "100msg")).build();

        final ExcerptAppender appender = c2s.createAppender();

        for (int i = 0; i < 10; i++) {
            appender.startExcerpt();
            appender.writeObject(String.valueOf(i));
            appender.finish();
        }

        appender.close();

        c2s.close();
    }
}

**Comment by andreas-hess** [comment]
Test :

package bug;

import java.io.File;
import java.io.IOException;

import net.openhft.chronicle.Chronicle;
import net.openhft.chronicle.ChronicleQueueBuilder;
import net.openhft.chronicle.ExcerptTailer;

public class ReadChronicle {
    public static void main(String[] args) throws IOException {
        works();
        bug();
    }

    public static void works() throws IOException {
        final Chronicle c2s = ChronicleQueueBuilder.indexed(new File(System.getProperty("java.io.tmpdir") + File.separator + "100msg")).build();

        final ExcerptTailer tailer = c2s.createTailer();

        while (tailer.nextIndex()) {
            System.out.print("Works index = " + tailer.index() + " : ");
            System.out.println(tailer.readObject());
        }

        tailer.close();

        c2s.close();
    }

    public static void bug() throws IOException {
        final Chronicle c2s = ChronicleQueueBuilder.indexed(new File(System.getProperty("java.io.tmpdir") + File.separator + "100msg")).build();

        final ExcerptTailer tailer = c2s.createTailer();

        tailer.index(0);

        while (tailer.nextIndex()) {
            System.out.print("Bug index = " + tailer.index() + " : ");
            System.out.println(tailer.readObject());
        }

        tailer.close();

        c2s.close();
    }
}

**Comment by lburgazzoli** [comment]
If you want to start from the beginning best is to use is tailer.toStart() or tailer.index(-1).
If you set it to 0 and then call nextIndex(), your tailer will point to the second excerpt.

**Comment by andreas-hess** [comment]
Thanks for the answer.

But why does index() return 0 at the beginning instead of -1 ?

**Comment by lburgazzoli** [comment]
When you create the tailer or move it to start, it does not point to any real data and -1 is an internal convention. Then by design a call to nextIndex is required to move the tailer to the next excerp which for the first iteration has index 0.

**Comment by andreas-hess** [comment]
Thanks again. So if I call index() before nextIndex() (sounds actully totaly logical) I get the index 
before the next message or -1 at the beginning.
If I want to start again from a known index this will do. 

Thanks
