### ISSUE TITLE
Improve the linearScan warning, and make it off by default

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#1555]
Reduce spurious log messages and improve the quality of information when logging does occur. With this change, the linearScan warning is disabled by default - it can be re-enabled with the `chronicle.queue.report.linear.scan.latency` system property, and the threshold for reporting can be changed by setting `linear.scan.warn.ns` - the default is 100Kns.

**Comment by JerryShea** [comment]
Closing this as I believe completed by #1556

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.37](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.37), [BOM-2.24.135](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.135)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.37](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.37), [BOM-2.24.136](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.136)
