### ISSUE TITLE
Improve configuration around readAfterReplicaAcknowledged() to allow a configurable number of inflight messages. 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#1564]
Relates to https://github.com/OpenHFT/Chronicle-Queue/pull/1566  and https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/pull/704

Improve configuration around readAfterReplicaAcknowledged() which can be used with replication to allow a configurable number of inflight messages. 

<img width="514" alt="image" src="https://github.com/OpenHFT/Chronicle-Queue/assets/6506056/87f9a61d-40a3-47f4-9a31-3ed074b7bce5">

<img width="526" alt="image" src="https://github.com/OpenHFT/Chronicle-Queue/assets/6506056/298f8635-14a7-457c-9f80-f7721e6c2ce8">

<img width="547" alt="image" src="https://github.com/OpenHFT/Chronicle-Queue/assets/6506056/caff9814-3ca2-4eb2-8c5d-d0af5723fd91">

The charts above shows the difference allowing inflight messages makes.

**API CHANGE**

we added the following

```
/**
     * Allows you to control the number of in flight messages that are allowed when setting {@code acknowledgedIndexReplicatedCheck},  By default, this is set to:
     * <p>
     * <p>
     * By providing a custom implementation of {@code acknowledgedIndexReplicatedCheck} you can control the number of in-flight messages that are allowed before the message is available to be read by the tailer.
     * And in addition, then acknowledgedIndexReplicatedCheck will be set to true.
     * <p>
     * below is the default implementation:
     * <pre>
     * boolean acknowledgedIndexReplicatedCheck(long index, long lastSequenceAck) {
     *      return index == lastSequenceAck;
     * }
     * </pre>
     * <p>
     * With this default implementation it will ensure tailer will not be able to read a message until it has been acknowledged that it has been full replicated.
     * <p>
     * However, if you wish to tolerate a number of in-flight or pending messages before the message.,
     * You can set this to a different implementation. For example, if you wish to tolerate one unacknowledged message, set {@code tolerateNumberOfUnAckedMessages} to 1, as shown below:
     * <pre>
     * boolean acknowledgedIndexReplicatedCheck(long index, long lastSequenceAck) {
     *     int tolerateNumberOfUnAckedMessages = 1;
     *     return index <= lastSequenceAck + tolerateNumberOfUnAckedMessages;
     * }
     * </pre>
     *
     * @param acknowledgedIndexReplicatedCheck as a custom implementation of {@code acknowledgedIndexReplicatedCheck}
     */
    default void acknowledgedIndexReplicatedCheck(AcknowledgedIndexReplicatedCheck acknowledgedIndexReplicatedCheck) {
        throw new UnsupportedOperationException("This method is not supported by this implementation");
    }
```

For a benchmark of this please see at https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/pull/704/files#diff-c099f655dcf641932ba5a714623534c6d2165d5f6a49619cd9dce61fc2e6ad96

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea15](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea15), [BOM-2.25ea52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea52)
