### ISSUE TITLE
Monitoring of TCP connection between source and sink

### ISSUE THREAD

**Issue by tomasherman** [OpenHFT/Chronicle-Queue#157]
It would be very useful to be able to monitor the state of tcp connection between source and sink. It's great that chronicle tries to reconnect should the tcp connection break, but users of chronicle queue need to be able to react to that. 

Perhaps a hook which is called during disconnect/reconnect would fix this?

**Comment by BoundedBuffer** [comment]
Sure - we have created the following JIRA - https://higherfrequencytrading.atlassian.net/browse/CHRON-115 <https://higherfrequencytrading.atlassian.net/browse/CHRON-115>

**Comment by lburgazzoli** [comment]
I've added support for connection listener in my branch https://github.com/lburgazzoli/Chronicle-Queue/tree/HFT-DEV, could you please give it a try ?

**Comment by tomasherman** [comment]
Hi,
sorry, i am not able to experiment much atm, we are having kind of a crunch time. But I appreciate the effort. I checked out the code a little bit though and the interface looks good to me.


-- 
Tomas Herman

On 12 Apr 2015 at 19:01:33, Luca Burgazzoli (notifications@github.com) wrote:

I've added support for connection listener in my branch https://github.com/lburgazzoli/Chronicle-Queue/tree/HFT-DEV, could you please give it a try ?

**Comment by lburgazzoli** [comment]
Can I close this issue?
