### ISSUE TITLE
Build out StoreAppender and StoreTailer test coverage to 90%+

### ISSUE THREAD

**Issue by james-mcsherry** [OpenHFT/Chronicle-Queue#1573]
In Chronicle-Queue StoreAppender and StoreTailer  have a test coverage of around 80% we would like to bring the coverage of those classes to 90%+.

**Comment by JerryShea** [comment]
See also https://github.com/OpenHFT/Chronicle-Queue/issues/821 - please deduplicate!

**Comment by james-mcsherry** [comment]
Closing as covered in #821
