### ISSUE TITLE
ChronicleReader suppress empty message

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1579]
If you try and read from a queue using a method reader interface as a filter then you get a blank line for each entry that is not handled by the interface even if you use `suppressDisplayIndex()`.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.36](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.36), [BOM-2.24.131](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.131)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.25ea17](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.25ea17), [BOM-2.25ea61](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea61)
