### ISSUE TITLE
FileNotFoundException on data file while reading

### ISSUE THREAD

**Issue by nyluke** [OpenHFT/Chronicle-Queue#160]
While writing to the queue in one process and reading from another, the ExcerptTailer fails on nextIndex() with a FileNotFoundException. It seems to be looking for a data file that doesn't exist yet.

```java.lang.AssertionError: java.io.FileNotFoundException: /opt/nebula/SS.2-mapdb_eol/bin/../db/stream/config/20150417/data-27717-1
	at net.openhft.chronicle.VanillaChronicle$AbstractVanillaExcerpt.index(VanillaChronicle.java:412) ~[chronicle-3.4.3.jar:na]
	at net.openhft.chronicle.VanillaChronicle$AbstractVanillaExcerpt.nextIndex(VanillaChronicle.java:426) ~[chronicle-3.4.3.jar:na]```

Note that I am creating the Chronicle with these settings:

```            chronicle = ChronicleQueueBuilder.vanilla(stream)
                    .dataBlockSize(1073741824)
                    .indexBlockSize(1073741824)
                    .build();```

I'm using the 3.4.3 release version. (This may be related to the fix for #153)

**Comment by peter-lawrey** [comment]
This happens if the index files is found, but the data file associated with
it is not.  This shouldn't be possible as it only writes to the index after
it has written to the data file.

Is it possible to write a unit test to reproduce this?

In the meantime we can add a workaround to handle this as if the entry is
not ready, but I would prefer to understand how this is possible to know if
doing this is a good idea or not.

Is the reader and writer on the same machine?  Using a network file system
is not supported.  If you want to distribute the data you need to use
replication.

**Comment by nyluke** [comment]
The reader and writer are on the same machine and the data is on a locally mounted SSD drive. This is a standard test of mine which did not produce this issue before 3.4.3, or at least before I started modifying the index and datafile sizes. I will try to build a unit test.

**Comment by peter-lawrey** [comment]
It should be possible to put the producer and consumer into different
ExecutorServices using different instance of a ChronicleQueue to simulate
interprocess communication.

You are setting very large sizes to reduce latency if I remember correctly?

**Comment by peter-lawrey** [comment]
Does this happen with smaller sizes? i.e. at which point does it start
happening?

**Comment by nyluke** [comment]
Correct, I saw much better latency with the large files. Testing now with the default file sizes and I'm so far not seeing the issue.

**Comment by peter-lawrey** [comment]
In Queue v4, all data and index will in one file but I don't see how
vanilla chronicle can get into this state and would like to know how this
is possible.

**Comment by lburgazzoli** [comment]
I've created a new [test case](https://github.com/lburgazzoli/Chronicle-Queue/commit/770adbafc8e96cd931812f269ff826f672799650) aimed to try to reproduce the issue but it does not fail so far, have I done something different compared to your set-up ?

**Comment by nyluke** [comment]
I have a similar test case that also is not yet reproducing the issue. The only obvious difference I can see with yours is that I have a single appender and multiple tailers, and that there are multiple processes. I’m guessing this may have something to do with the timing of the reads/writes but I still haven’t isolated it..

**Comment by nyluke** [comment]
Ok I'm still working on a perfect unit test here but this seems to be the result of having:

- one process with an appender the is actively writing
- another process with several tailers actively reading, with some that did not explicitly specify the block sizes in their QueueBuilder

I think we'll find generally that the reader(s) must always specify the block sizes that match the writer or else there will be corruption. Note that this may require separate processes instead of threads.

**Comment by peter-lawrey** [comment]
Yes. this is a limitation in Queue v3.  Each consumer must have the same
index and data chunk size of the producer.  This is not a problem if they
are not set as they will be the same by default.
In Queue v4, this limitation should be lifted.

**Comment by lburgazzoli** [comment]
can we close this ?

**Comment by peter-lawrey** [comment]
Probably. Go ahead and close it.
