### ISSUE TITLE
Move secondary index scanning to primary index loop

### ISSUE THREAD

**Issue by james-mcsherry** [OpenHFT/Chronicle-Queue#1604]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.26ea4](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.26ea4), [BOM-2.26ea31](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea31)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.24.38](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.24.38), [BOM-2.24.139](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.139)
