### ISSUE TITLE
Reading Null Enum throws Exception

### ISSUE THREAD

**Issue by greghall79** [OpenHFT/Chronicle-Queue#161]
Hi, we recently updated from chronicle 3.2.4 to 3.4.2 and a couple of our unit tests failed. We found the cause to be a change to BytesMarshallableSerializer.readSerializable to handle Enums where an expectedClass is provided. The new code does not handle Null entries and attempts a readCharSequence, throwing an exception.

We can revert to previous behaviour by replacing the use of readEnum(Class) with a cast of (Class)readObject but would you expect Null's to be handled?

**Comment by JerryShea** [comment]
Must have been fixed at some point because 3.6.1.8  does not exhibit this problem

**Comment by peter-lawrey** [comment]
I suggest trying Queue 3.6.2
