### ISSUE TITLE
writersWaiting has underflowed

### ISSUE THREAD

**Issue by kemalerden** [OpenHFT/Chronicle-Queue#166]
I do get this message in system.err from time to time using chronicle vanilla queue (possibly chronicle map - I'm using both). (chronicle version - 3.4.2, chronicle.map.version 2.1.4)

Does it mean there has been a problem writing the message? any suggestions how to fix/handle?

environment: windows
relevant code: (vanilla chronicle used hence below code called from multiple threads)

    Chronicle chronicle = ChronicleQueueBuilder.vanilla(new File("data/chronicle"), "journal-store").build();

    public void logRawMsg(final String message) {
        try {
            ExcerptAppender appender = this.chronicleQueue.createAppender();
            byte[] byteArray = message.getBytes(this.utf8);
            appender.startExcerpt(byteArray.length + 3);
            appender.writeObject(message);
            appender.finish();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

some logs:
```
16:55:36.607 [WorkQueueAsyncTaskExecutor-11] WARN  n.o.c.h.ChronicleHashErrorListeners$LoggingErrorListener - Grabbing lock held by processId: 134217728, threadId: 0
writersWaiting has underflowed
writersWaiting has underflowed
16:55:36.610 [WorkQueueAsyncTaskExecutor-12] WARN  n.o.c.h.ChronicleHashErrorListeners$LoggingErrorListener - Grabbing lock held by threadId: 0
16:55:36.610 [WorkQueueAsyncTaskExecutor-13] WARN  n.o.c.h.ChronicleHashErrorListeners$LoggingErrorListener - Grabbing lock held by threadId: 0
```

Thanks in advance

**Comment by peter-lawrey** [comment]
The problem is entirely in Chronicle Map as it is the only one which uses
the hash.
I have a JIRA for changing how the timeouts are calculated as well as
looking at other strategies.
At the moment, our resources are tied up with Chronicle Engine and
Enterprise as we have a contract deadline at the end of this month.

**Comment by peter-lawrey** [comment]
I would try Chronicle Map 3.x as this has many fixes.
