### ISSUE TITLE
Tailer is empty on single entry journal

### ISSUE THREAD

**Issue by pranasblk** [OpenHFT/Chronicle-Queue#167]
The journal contains 1 entry with index file flushed to the index file:
```
hexdump events.index
0000000 00 00 00 00 00 00 00 00 2f 01 00 00 00 00 00 00
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
2000000
```

But tailer return nexIndex() == false on very first invocation during replay:
```
try (ExcerptTailer tailer = chronicle.createTailer().toStart()) {
while (tailer.nextIndex() && ...) {
}
...
```

Note: The journal is populated with:
```
      appender.startExcerpt(length);
      appender.write(accessor.getBuffer(), 0, length);
      appender.finish();
```

**Comment by peter-lawrey** [comment]
The toStart () should be redundant.  Can you take it out to see if it is
the cause of the problem?

**Comment by pranasblk** [comment]
Hi Peter,

Thank you for the prompt reply.
I an trying to replay a journal from another process (after appender has finished writing).
I've updated the code:
```
while (run) {
        try (ExcerptTailer tailer = chronicle.createTailer()) {
          //tailer.index(index);
          while (tailer.nextIndex() && run) {
...
          }
}
```
But can reproduce issue again.

```
Constructing of Chronicle:     
      this.chronicle = ChronicleQueueBuilder
      .indexed(path.toFile(), "events")
      .build();
```

But still getting false for the journal with 3 entries:

```
Pranass-MacBook-Pro:T pb$ hexdump events.index
0000000 00 00 00 00 00 00 00 00 2f 01 00 00 5e 02 00 00
0000010 8d 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
2000000
Pranass-MacBook-Pro:T pb$ hexdump events.data
0000000 2f 01 00 00 66 00 01 00 00 00 00 00 00 00 c9 dc
0000010 dc b8 4d 01 00 00 17 01 ff ff ff ff ff ff ff ff
0000020 ff ff ff ff ff ff ff ff ff ff ff ff 00 00 00 41
0000030 41 41 42 42 42 43 43 43 44 44 44 45 45 45 20 20
0000040 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
*
0000120 20 20 20 20 20 20 20 20 20 20 20 20 20 20 00 2f
0000130 01 00 00 66 00 02 00 00 00 00 00 00 00 ca dc dc
0000140 b8 4d 01 00 00 17 01 ff ff ff ff ff ff ff ff ff
0000150 ff ff ff ff ff ff ff ff ff ff ff 00 00 00 41 41
0000160 41 42 42 42 43 43 43 44 44 44 45 45 45 20 20 20
0000170 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
*
0000250 20 20 20 20 20 20 20 20 20 20 20 20 20 00 2f 01
0000260 00 00 66 00 03 00 00 00 00 00 00 00 ca dc dc b8
0000270 4d 01 00 00 17 01 ff ff ff ff ff ff ff ff ff ff
0000280 ff ff ff ff ff ff ff ff ff ff 00 00 00 41 41 41
0000290 42 42 42 43 43 43 44 44 44 45 45 45 20 20 20 20
00002a0 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
*
0000380 20 20 20 20 20 20 20 20 20 20 20 20 00 00 00 00
0000390 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
8000000
```

Dependencies
```
  compile group: 'net.openhft', name: 'chronicle', version: '3.4.3'
```

**Comment by pranasblk** [comment]
The journal's content looks good, but the Tailer for Indexed Reader seems to be broken in 3.4.3.
Note:  I'm testing on Java 8
```
Pranass-MacBook-Pro:T pb$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by lburgazzoli** [comment]
Looks like you have found a bug.
However it does not seems to exist in VanillaChronicle, can you give it a try ?

**Comment by lburgazzoli** [comment]
Can you please post the full code of the appender ?

**Comment by pranasblk** [comment]
It is all good with Vanila. I can make complete simplified code to reproduce the problem during weekend.
I don't call ```clear()```.

**Comment by lburgazzoli** [comment]
it would be great

**Comment by pranasblk** [comment]
Luca, It looks like duplicate of CHRON-116. 
I've moved ahead with Vanila prototype and it works great so far.

**Comment by lburgazzoli** [comment]
That's great.

However having a test case for the bug on indexed chronicle would be really useful for us as I've tried to reproduce it without success (my first finding was wrong because I forgot a chronicle.clear() after chronicle creation).

**Comment by pranasblk** [comment]
Yes, it is the case - "I forgot a chronicle.clear() after chronicle creation”.
I’ve just followed sample examples from project’s main .md file and don’t see clear() as a mandatory step described.

Thanks!
Pranas
