### ISSUE TITLE
Test for randomly accessing next excerpt without calling finish().

### ISSUE THREAD

**Issue by alexkoon** [OpenHFT/Chronicle-Queue#17]
As requested on Group post, this is to raise an issue to have a test for randomly accessing the next excerpt without calling finish.

**Comment by peter-lawrey** [comment]
In Queue v3 this was harmless as finish() only checked you didn't read more data than you were allowed.

Queue v4 no long has a finish() method and it doesn't allow you to read too much.

Closing.
