### ISSUE TITLE
Throw an Error When File Deleted

### ISSUE THREAD

**Issue by mconaghan** [OpenHFT/Chronicle-Queue#179]
I have observed that a chronicle (queue) writer process continues without error when the underlying files it is writing to are deleted by another process - ideally the code should throw an exception to make this more obvious.

**Comment by lburgazzoli** [comment]
When you remove a file you only remove the name from the filesystem but the file won't be deleted until the latest file descriptor referring to it is closed.

**Comment by mconaghan** [comment]
OK - but the end result is that when the chronicle writer process terminates the file doesn't exist - so the chronicle writer process is writing data to a file that can no longer be accessed. I don't think it is possible for the Chronicle writer process to prevent the file from being deleted (on Linux anyway, probably could do it in Windows), in which case it would be useful to have some feedback on the fact that the Chronicle files are been removed / cannot be read.

**Comment by lburgazzoli** [comment]
I might be wrong but on UNIX there is no way to detect if the file on which you are writing to has been deleted by another process unless you explicit monitor the file like with File.exists() and IMHO it does not make much sense for a low latency application. 

If you have any suggestion on how to do so without impact on the performances I'd more than happy to raise a JIRA and implement it :-)

**Comment by peter-lawrey** [comment]
You could attach a directory watcher to see if a file is deleted from a
directory.

Under Linux, on a delete the file is detached from a directory and if this
is the last reference to this file it is cleaned up.
If the file exists in another directory or it is used by an application it
is still used and not actually removed from the disk. It can even continue
to grow after the only reference to the file is a program.

**Comment by mconaghan** [comment]
OK - thanks both for your comments. I am indeed going to add my own file watcher and a locking mechanism to try and prevent the file being deleted. I suspected you might be reluctant to add detection of file deletion this into the chronicle code base due to performance overhead!

**Comment by peter-lawrey** [comment]
Hello,
As far as Chronicle Queue is concerned, removing a file from a directory
while it is in use is not an error. E.g. a file can appear in two
directories via a hard link and if you remove it from one, you are not
actually deleting the file.  When you remove the file from a directory, it
is still not removed from the filesystem until the last program using it
closes the file.

Can you explain your use case in a bit more detail?  Why do you want to
delete files you are still using? Why would you want Chronicle Queue to
have an error when the program still runs correctly?

We could lock the files while in use preventing access from another program
but it sounds like you shouldn't be deleting those files in the first place.

Regards,
   Peter.

**Comment by mconaghan** [comment]
Hi Peter,

Normal use case is that the writer process stops, then the archive process runs - in which case none of this is an issue. This is about error case handling really: I'm trying to protect against the case where the archive process runs incorrectly before the writer process has stopped. As above I'm implementing a locking scheme that will hopefully prevent the archive process from doing any damage in this case (it'll see writer process still running and won't do anything), but if it did manage to delete/move the directory (or if someone logged in and did an rm -rf on my chronicle directory) then I would like it if the writer process flagged it up.

Also worth saying that when I tested something similar a few weeks ago, I observed that when I rm -f the chronicle directory, the writer continues to write, but the reader process doesn't get any of the data which is written after the rm. It (the reader process) also doesn't throw any error, presumably because it too still has a valid fie pointer - but again I'd like it to throw an error so that someone notices and can intervene promptly. Is this behavious what you would expect, or would you expect that the reader process should still pick up anything written to the file, after the rm, since both the writer and reader have valid file pointers?

Thanks,
Martin

**Comment by peter-lawrey** [comment]
>  I would like it if the writer process flagged it up.

currently it continues to read the entries as if you hadn't deleted the
files accidentally.  If you delete the files in such a way that chronicle
queue cannot read them i.e. because they are not open, then attempting to
call boolean index(toRead) will return false rather true.

I would expect the reader to be unaffected by deleting a file it has open.
The reader doesn't know about files it hasn't opened yet.

Would you be able to provide a unit test to show the problem you are seeing
and we can try to fix it.

Peter.

**Comment by mconaghan** [comment]
Hi,

Sure I'm going to re-test and try to provide a repro if I see the reader failing to pick up new data afetr the file is rm-ed.

Thanks,
Martin
