### ISSUE TITLE
Problem: Unable to add net.openhft/chronicle "3.5.1" as a dependency 

### ISSUE THREAD

**Issue by trevorbernard** [OpenHFT/Chronicle-Queue#180]
```
Could not transfer artifact net.openhft:third-party-bom:pom:3.4.20 from/to central (https://repo1.maven.org/maven2/): Checksum validation failed, expected a55111b4fbbd40553d263f664978c6ea9f9b96ed but is 995544ef2c57264c49e5fbd03307ebeebc5a47da
```

**Comment by lburgazzoli** [comment]
@BoundedBuffer can we re-release third-party-bom v3.4.20 ?

**Comment by BoundedBuffer** [comment]
sure - I’ll do it now

**Comment by lburgazzoli** [comment]
I've release 3.5.2 with third-party-bom 3.4.21 - no other changes.
It should be available on maven central in a few hours.

**Comment by trevorbernard** [comment]
I'm still having the same problems with 3.5.2.

```
Retrieving net/openhft/third-party-bom/3.4.20/third-party-bom-3.4.20.pom from central
Retrieving net/openhft/third-party-bom/3.4.20/third-party-bom-3.4.20.pom from central
Could not transfer artifact net.openhft:third-party-bom:pom:3.4.20 from/to central (https://repo1.maven.org/maven2/): Checksum validation failed, expected a55111b4fbbd40553d263f664978c6ea9f9b96ed but is 995544ef2c57264c49e5fbd03307ebeebc5
a47da
```
I rm -r ~/.m2/repository then try to fetch new deps with leiningen. As an interim step, I added :checksum :warn in my project.clj file.

```
lein deps :tree
 [cider/cider-nrepl "0.10.0-20150802.041105-17"]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [net.openhft/chronicle "3.5.2"]
   [net.openhft/affinity "2.2"]
     [net.java.dev.jna/jna-platform "4.1.0"]
     [net.java.dev.jna/jna "4.1.0"]
     [org.kohsuke.jetbrains/annotations "9.0"]
   [net.openhft/lang "6.6.11"]
     [com.sun.java/tools "1.8.0_45" :scope "system"]
     [net.openhft/compiler "2.2.0"]
     [org.ow2.asm/asm "5.0.3"]
     [org.xerial.snappy/snappy-java "1.1.1.6"]
   [org.slf4j/slf4j-api "1.7.12" :exclusions [[ch.qos.cal10n/*]]]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/tools.nrepl "0.2.10" :scope "test" :exclusions [[org.clojure/clojure]]]
 [refactor-nrepl "1.1.0"]
```

**Comment by lburgazzoli** [comment]
Sorry, my mistake it does not set dependency to third-party-bom 3.4.21, I'll do a new release

**Comment by lburgazzoli** [comment]
I've released a new version ( v3.5.3 ), It should be available on maven central in a few hours.

**Comment by BoundedBuffer** [comment]
this is strange, as no one else has reported this issue, none of our clients are seeing this issue, try setting this, in your setting.xml file.


<mirrors>

    <mirror>
        <id>Central</id>
        <url>http://repo1.maven.org/maven2</url>
        <mirrorOf>central</mirrorOf>
        
    </mirror>
 
</mirrors>

**Comment by lburgazzoli** [comment]
I've got the same warning but some build tool are more relaxed and do not stop if checksum mismatch

**Comment by BoundedBuffer** [comment]
Not sure if this helps. 

http://stackoverflow.com/questions/1765959/maven-checksum-failed

**Comment by trevorbernard** [comment]
@lburgazzoli issue resolved
