### ISSUE TITLE
read/write with direct reference for byte arrays?

### ISSUE THREAD

**Issue by puiuvlad** [OpenHFT/Chronicle-Queue#185]
Hi,

How can I use the read/write with direct reference feature with byte arrays? Here is my use case:

I have a pipe consisting of appender1, tailer1, appender2, and tailer2. An object O flows thru this pipe as follows:

1. Object O (multiple fields in a data structure) gets marshalled to appender1.
2. The data is read from tailer1 and unmarshalled into object O1.
3. Object O1 gets marshalled to appender2.
4. The data is read from tailer2 and unmarshalled into object O2 which is subsequently used.

The first optimization that I can think of is to avoid the time consuming unmarshalling/marshalling of the complex structure at steps 2 and 3, and replace it with marshalling a single byte array (by calculating the size of the byte array and storing it in the message 'header'). So basically I replace object O1 with a byte array.

The second optimization is to eliminate the copy at step 2 and instead marshalling into appender2 directly from tailer1.

I have tried using the following interface,

    public interface BytesRef extends Byteable {
        void setRef(byte[] ref);
        byte[] getRef();
    }

but I am getting "java.lang.IllegalArgumentException: type must be an interface, was class [B" Do you have any suggestion about how to do this?

Thanks,
Vladimir

**Comment by peter-lawrey** [comment]
Hello Vladimir,
   If you use our DataValue objects you can point them directly at an
Appender or Tailer.  This can be thought of as a (struct *) but in Java.
This means that you can write the data directly to a Queue without any
additional copies other than writing the data.
   Similarly if you want to read this data you can again reference it via a
generated off heap reference, or if you want to copy this data directly
from an tailer to an appender you can do this via a tailer.write(appender)
Optionally you can add an offset and length for a sub-set of data.

   You can use a byte[] in all these cases, but I don't see any benefit in
adding one in.

Regards,
   Peter.

**Comment by puiuvlad** [comment]
Hi Peter,

Did you mean appender.write(tailer)?

Thanks,
Vladimir

**Comment by peter-lawrey** [comment]
Correct, you want to write from the tailer to the appender.
