### ISSUE TITLE
3.4.3 VanillaChronicle crash on append

### ISSUE THREAD

**Issue by nyluke** [OpenHFT/Chronicle-Queue#188]
I'm seeing a crash after running load for a few hours. Will re-test with the latest version and try to gather more debug..

RAX=0x31373335313a3131 is an unknown value
RBX=0x00000005c00238c8 is an oop
net.openhft.chronicle.VanillaChronicle$VanillaAppenderImpl
 - klass: 'net/openhft/chronicle/VanillaChronicle$VanillaAppenderImpl'
RCX=0x000000000000012f is an unknown value
RDX=0xffffffffffffffff is an unknown value
RSP=0x00007fb5083a5ec0 is pointing into the stack for thread: 0x00007fb4b18d5800
RBP=0x00007fb5083a5ec0 is pointing into the stack for thread: 0x00007fb4b18d5800
RSI=0x00007fb003d2d019 is an unknown value
RDI=0x00000005c005dde0 is pointing into object: 0x00000005c005dcb0
[B
 - klass: {type array byte}
 - length: 65536
R8 =0x00007fb003d2cef8 is an unknown value
R9 =0x00000005c005dcb0 is an oop
[B
 - klass: {type array byte}
 - length: 65536
R10=0x00007fb515052600 is at begin+0 in a stub
StubRoutines::unsafe_arraycopy [0x00007fb515052600, 0x00007fb51505263b[ (59 bytes)
R11=0x000000000000012f is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x00007fb003d2d028 is an unknown value
R14=0x00000000b800bb96 is an unknown value
R15=0x00007fb4b18d5800 is a thread

Stack: [0x00007fb5082a7000,0x00007fb5083a8000],  sp=0x00007fb5083a5ec0,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~StubRoutines::jbyte_disjoint_arraycopy

**Comment by peter-lawrey** [comment]
Hello Luke,

How much free disk space do you have at this time?

Peter.

**Comment by nyluke** [comment]
About 10g free on the partition that has the data, though the root partition is almost full. Would that cause this?

**Comment by peter-lawrey** [comment]
Where we have seen this before is when the disk space runs out.
We have tried to add checks to prevent this and throw an exception instead
but you might have a version which is not checking (even if it is the
current one ;)

**Comment by peter-lawrey** [comment]
Closing as Queue v3 is not supported.
