### ISSUE TITLE
Second write is not persisted

### ISSUE THREAD

**Issue by WhiteTrashLord** [OpenHFT/Chronicle-Queue#189]
I tested with this code:

		try 
		{	
			Chronicle chronicle = ChronicleQueueBuilder.indexed("test").  build();
			
			// Obtain an ExcerptAppender
			ExcerptAppender appender = chronicle.createAppender();

			// Configure the appender to write up to 1000 bytes
			appender.startExcerpt(1000);
				
			appender.writeObject("TestMessage1");		
			appender.writeObject("TestMessage2");					
					
			// Commit
			appender.finish();					
			appender.close();
			
			// Obtain an ExcerptTailer
			ExcerptTailer reader = chronicle.createTailer();
			while(reader.nextIndex())
			{					
				// Read the object
				Object ret = reader.readObject();
				System.out.println(ret);		
				// Make the reader ready for next read
				reader.finish();					
			}
			
			Object ret = reader.readObject();
			System.out.println(ret);				
			reader.finish();		

			reader.close();
			chronicle.close();				
			
		} catch (IOException e) {		
			e.printStackTrace();
		}

When I run it a second time I don't see a second "TestMessage2".
Only "TestMessage1" is persisted.
Is this behaviour intended?

**Comment by peter-lawrey** [comment]
Hello WTL.
When you start/finish a message,  that is one message. This means if you
write two objects in a single message, that is how you need to read them.

Try

while(reader.nextIndex()) {
    Object ret = reader.readObject();
    System.out.println(ret);
    Object ret2 = reader.readObject();
    System.out.println(ret2);
    reader.finish ();
}

**Comment by WhiteTrashLord** [comment]
Thanks for your fast answer. With your code everything works as expected. I got it now that every message is a ByteBuffer.

Your design doesn't allow the deleting of messages, or?
It's save to delete old VanillaChronicle rolling files?

**Comment by peter-lawrey** [comment]
It is safe to delete/compress old log files provided you don't need them.
E.g. With an overnight job.

Only you know if this is the case or not.

Regards,
Peter.
