### ISSUE TITLE
Performance Test - Comparaision with Kafka

### ISSUE THREAD

**Issue by nxhoaf** [OpenHFT/Chronicle-Queue#190]
Hi there, 

I posted a question related to Chronicle Queue performance here: 
https://groups.google.com/forum/#!topic/java-chronicle/lYyJZAu1TXs

Could you please check it and advise ? 

Thank you, 
Hoa.

**Comment by peter-lawrey** [comment]
Hello Hoa,
   Yes the main problem is that you were multipling the number of messages
by the batch size.  This is why the test took twice as long when you
doubled the batch size. See my replies on that forum.

Regards,
   Peter.

**Comment by nxhoaf** [comment]
Hi Peter, 

Thank you for your reply. I updated the test based on your suggestion replied you on the forum also. 

Regards, 
Hoa.
