### ISSUE TITLE
Feature Request: Chronicle that reads from a GzipInputStream

### ISSUE THREAD

**Issue by psdillon** [OpenHFT/Chronicle-Queue#2]
The ability to read excerpts from a gzip'ed file would make it much easier to run batch processing (eg. reporting) over very large sets of chronicle data files, that are otherwise too large to store uncompressed.

Originally posted to mailing list here:

https://groups.google.com/forum/?fromgroups#!topic/java-chronicle/YFTWZbiMeu0

**Comment by peter-lawrey** [comment]
This will be parked onto the wish list. I don't think this will happen in the short term.
We have a better chance of supporting compressed entries in a queue.
