### ISSUE TITLE
Designing concurrent IndexedChronicle 

### ISSUE THREAD

**Issue by ygokirmak** [OpenHFT/Chronicle-Queue#20]
The current implementation of Chronicle has a single writer multiple reader architecture. ( I think we can create multiple readers without any problem )

I am trying to enhance IndexedChronicle in a way that multiple writers will be available... Current implementation fits messaging queue requirements but in order to use chronicle as a baseline for Cache implementation, concurrency should be provided... 

Lets discuss some design issues and try to make a draft architectural design.. I will coding it..

Current implementation has one write head and this write head advances at each write further.. 

I think IndexedChronicle will be a base for such implementation therefore I will talking over it.. 

We have indexCache and dataCache at the lowest layer. When we try to put some data to indexed chronicle, data is written to dataCache, and address of the data is written to indexCache.

Appender does not look for suitable cell before put operation because it always points to the first available place in dataCache.. 

indexCache and dataCache has a blocks of configurable size so when required a new blocked is mapped from file to memory... 

What if we want to write with two threads concurrently.. The basic solution should be defining a write lock and each appender acquires lock before writing but this will decrease the performance and blocks waiting threads...

We need more than one lock.. We may put locks for each dataBlock and if a writer wants to write to a block first it should get the lock.. Because we have several blocks, several threads can write different blocks at the same time.. This will increase random update/write performance.. But decrease sequential write of multiple threads... ( acquiring lock will bring some overhead )

But the problem of this approach is we don't have much blocks in early times of the cache.. There will be a warm up period where cache will have more performance.. 

The other approach would be slicing blocks into several concurrency blocks and creating locks for each concurency blocks... This will be a better solution because in that case we don't need to wait chronicle to become bigger to get high performance... Trade of is the space for locks.. They will be preserved in heap and the more locks we have the more heap we use...

These ideas are just questions in my mind.. Managing indexCache is another issue and I think we shouldn't consider it separately..  

Please write your comments, meanwhile I am looking for more accurate solutions..

regards.

**Comment by peter-lawrey** [comment]
At the moment Vanilla (Queue 3.x) and Single (Queue 4.x) support concurrent writers and readers.

There isn't plans for a concurrent indexed queue.
