### ISSUE TITLE
Problem while reading/writing empty message

### ISSUE THREAD

**Issue by michaljonko** [OpenHFT/Chronicle-Queue#204]
Hi,
I found some problems with store/restore messages from Chronicle. Problem occurs when I want to save empty message ie. new byte[0]. I have to create sequential low-latency storage also with empty messages store possibility.
Below you can find simple test I wrote. You can find there that *tailer.nextIndex()* returns false. Also if you will define emptyMessage as *emptyMessage[] = new byte[1];* then test will pass. ExcerptAppender looks like it is working well - it writes messages without exceptions/problems.

```java
    @Test
    public void emptyMessageTest() throws Exception {
        byte emptyMessage[] = new byte[0];
        int writeCycles = 20;
        String path = System.getProperty("java.io.tmpdir") + "emptymessage.test";
        ChronicleTools.deleteOnExit(path);
        try (Chronicle chronicle = ChronicleQueueBuilder.indexed(path).build()) {
            try (ExcerptAppender appender = chronicle.createAppender()) {
                for (int i = 0; i < writeCycles; i++) {
                    appender.startExcerpt(emptyMessage.length);
                    appender.write(emptyMessage);
                    appender.finish();
                }
            }
            try (ExcerptTailer tailer = chronicle.createTailer()) {
                assertThat(tailer.size(), is((long) writeCycles));
                for (int i = 0; i < writeCycles; i++) {
                    assertThat("Cannot move index for i=" + i, tailer.nextIndex(), is(true));
                    byte readMessage[] = new byte[tailer.length()];
                    tailer.read(readMessage);
                    assertThat(readMessage, is(emptyMessage));
                }
            }
        }
    }
```
What can I do to make it possible to write/read *new byte[0]* messages?

**Comment by peter-lawrey** [comment]
You are right that there is issues using zero length messages. Another
issue is that there can padding at the end of a message in the case of
vanilla chronicle.  There was once an assumption that messages wouldn't be
less than 8 bytes long though this limitation should be removed now.

The general pattern of use is to record. the length of the message first.

// to write.
appender.startExcerpt(emptyMessage.length+4);
appender.writeStopBit(emptyMessage.length); // uses one byte per 7 bits
appender.write(emptyMessage);
appender.finish();

// to read
byte readMessage[] = new byte[(int) tailer.readStopBit()];
tailer.read(readMessage);

This has the side effect that you won't have zero byte messages.

In Queue v4, we are looking to fix these issues, i.e. you won't have
padding either of messages or indexes. I will check that zero length
messages are supported also.

**Comment by michaljonko** [comment]
Thank you for quick replay.
You proposal looks fine but I would like to have not incremental storage for empty messages. Right now I'll try to make it as you wrote. I'm also still looking for v4 with fix :)
