### ISSUE TITLE
vanilla chronicle replication

### ISSUE THREAD

**Issue by kemalerden** [OpenHFT/Chronicle-Queue#209]
Hi,

**chronicle version : 3.5.3, windows and Linux (Red Hat 4.4.7-3)**

**please see update further below**

I'm probably doing something wrong but I can't get vanilla replication to work. I'm trying to achieve a mirror of the persisted chronicle store.

I've got a vanilla chronicle q fed by process A (persisted to file). 

process B reads directly from it and writes output to files - no issues here.

process C then creates a source (path as process A) and a sink and tries to process entries using the sink.

process A is stopped - chronicle q has 31 entries.

process B logs:
read-index=18377237346648094 count=31

process C logs:
**read-index=18377237346648074 count= 11**

the code for process C as follows:
         
       Chronicle source = ChronicleQueueBuilder.vanilla(new File("data/chronicle"), "journal-store").source()
            .bindAddress("localhost", 1234).build();
        Chronicle sink = ChronicleQueueBuilder
            .sink(ChronicleQueueBuilder.vanilla(new File("data/sink"), "journal-sink").build())
            .connectAddress("localhost", 1234).build();
        try {
            sink.clear();
            ExcerptTailer tailer = sink.createTailer().toStart();

            int i = 0;
            while (tailer.nextIndex()) {
                MyMessage message = new MyMessage();
                message.readMarshallable(tailer);
                System.out.println(tailer.index() + "  " + message.getControlEventId());
                tailer.finish();
                i++;
            }
            System.out.println("read-index= " + tailer.index() + "count= " + i);
        } finally {
            sink.close();
            source.close();
        }

I also get the following exception if I remove the sink.clear() call.

    Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:236)
	at net.openhft.chronicle.ChronicleQueueSink$StatefulExcerpt.doReadNextExcerpt(ChronicleQueueSink.java:380)
	at net.openhft.chronicle.ChronicleQueueSink$AbstractStatefulExcerpt.readNextExcerpt(ChronicleQueueSink.java:232)
	at net.openhft.chronicle.ChronicleQueueSink$StatefulExcerpt.doReadNextExcerpt(ChronicleQueueSink.java:349)
	at net.openhft.chronicle.ChronicleQueueSink$AbstractStatefulExcerpt.readNextExcerpt(ChronicleQueueSink.java:232)
	at net.openhft.chronicle.ChronicleQueueSink$AbstractStatefulExcerpt.readNext(ChronicleQueueSink.java:226)
	at net.openhft.chronicle.ChronicleQueueSink$AbstractStatefulExcerpt.nextIndex(ChronicleQueueSink.java:121)
	at com.hsbc.cibm.dml.hs.kcr.chronicle.tests.ChronicleTest.main(ChronicleTest.java:92)

**UPDATE**

net.openhft.chronicle.tcp.TcpConnection.read(ByteBuffer, int, int, int)

I've been getting different results on different runs so I've done some debugging and found this is related to how much data is being read from the tcp connection in the first call. If the read call from TcpConnection class can read as much as the message length in the first call everything works fine. Otherwise I get the exception above. This happens after all messages are read and the tailer is at the end (i.e. in the above code remove sink.clear() and call toEnd() rather than toStart() on second run.)

I've replaced classes locally and put some logging information. 

A successful run looks like below:

    doReadNextExcerpt limit=0
    rem= 0, threshold = 12
    position 0
    size 20
    **position after loop=9234**
    9234
    msg size from header = -126
     
    doReadNextExcerpt limit=9234
    rem= 9222, threshold = 12
    position 12
    size 20
    limit 9234
    **msg size from header = 9210**
    
    doReadNextExcerpt limit=9234
    rem= 0, threshold = 12
    position 9234
    size 20
    position after loop=24
    limit 24
    msg size from header = -128
    read-index= 18380535881531421, count= 0

An unsuccessful run however:

    doReadNextExcerpt limit=0
    rem= 0, threshold = 12
    position 0
    size 20
     **position after loop=3484**
    msg size from header = -126
     
    doReadNextExcerpt limit=3484
    rem= 3472, threshold = 12
      //rest of the excerpt is not read into the buffer here
    position 12
    size 20
    **msg size from header = 9210**

fails at this point with the exception above trying to re-position the buffer.

hope this helps.

**Comment by lburgazzoli** [comment]
Are you able to send a PR with a failing test case ?

**Comment by kemalerden** [comment]
Hi Luca,
Hope this helps:
just run Main multiple times and you should be able to reproduce issue.
https://github.com/kemalerden/chronicle-issue-209

**Comment by peter-lawrey** [comment]
Closing as Queue v3 is not supported.
