### ISSUE TITLE
Support for OpenJDK 6 and old Sun Java 6 versions

### ISSUE THREAD

**Issue by bgranvea** [OpenHFT/Chronicle-Queue#21]
Some JDKs don't have the Unsafe.copyMemory method. For example I get this exception on FreeBSD with OpenJDK 6:

java.lang.NoSuchMethodError: sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V
        at net.openhft.lang.io.NativeBytes.write(NativeBytes.java:227) ~[bench-1.0-SNAPSHOT.jar:na]
        at net.openhft.lang.io.AbstractBytes.write(AbstractBytes.java:626) ~[bench-1.0-SNAPSHOT.jar:na]

$ java -version
openjdk version "1.6.0"
OpenJDK Runtime Environment (build 1.6.0-b23)
OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode)

Java-Chronicle should provide a work around for such cases.

**Comment by peter-lawrey** [comment]
Currently we only offer free support for Java 8.
To support older versions would require paid support.
