### ISSUE TITLE
Vanilla Chronicle read byte array 

### ISSUE THREAD

**Issue by WilliamDunne** [OpenHFT/Chronicle-Queue#212]
While the vanilla queue offers by default writing byte arrays to the queue, the reader doesn't support such things. Nor does it work when casting a generic object to a byte array.

What would be the best way of reading a byte array directly from the reader?

**Comment by peter-lawrey** [comment]
I would do

tailer.read (bytes)

Assuming you know the length.

If not you can write the length first with

appender.writeStopBit(bytesLength);
appender.write (bytes);

And read

int len = (int) tailer.readStopBit ();
tailer.read (bytes, 0, len);

Using stop bit encoding means using one byte for every 7 bits. Ie 0 to 127
uses one byte.
