### ISSUE TITLE
Bulletproof way of knowing which directories can be removed?

### ISSUE THREAD

**Issue by metabrain** [OpenHFT/Chronicle-Queue#219]
Hello,

I'm having a bit of a problem trying to understand how to directory rotation works in chronicle-queue. I thought once a "newer" directory is created the old ones would stop being used. Is this correct? 

I thought so, but I had my doubts since I when I was debugging the internals I noticed that the *VanillaChronicle.indexCache.cyclePathMap* variable still has references to the old directories. Is this expected as well? As far as I searched, only get and put operations are performed on this map.

At what point can they be safely removed? Is there any "hook" I could bind to when they get "rotated"? Or do I have to take a more empiric approach and just assume nobody is using an older "rotated" directory once a newer one got created?

All this because I need to clear old "rotated" directories during runtime in order to avoid filling up the FS.

Cheers and thanks in advance,
Dan

**Comment by peter-lawrey** [comment]
Queue 4.x will have a StoreFileListener so you can get a callback when a file is added and when it is released.

**Comment by RobAustin** [comment]
Only the latest version of chronicle queue is supported, please retest using this version, 

    <artifactId>chronicle-queue</artifactId>
    <version>4.4.4</version>

VanillaChronicle.indexCache is code that is no longer in chronicle-queue v4. If you are having a similar issue in chronicle queue V4 please raise a new issue. thanks.
