### ISSUE TITLE
Confusing Chronicle meaning in FAQ

### ISSUE THREAD

**Issue by wenerme** [OpenHFT/Chronicle-Queue#225]
Chronicle is a Chronicle Instance or Chronicle File or Multi Chronicle Instance in same process or ... ?

e.g.

## Can I have multiple writers?

A given Chronicle(__Chronicle instance I guess__) should only have a single writer. It is not threadsafe for multiple threads to write to the same Chronicle(__Still a single instance ?__). Multiple writers in the same process will cause a performance degradation. If you still want to, you need to use some form of external locking. Either synchronized or ReentrantLock may be suitable.

You cannot safely write to the same Chronicle(__At least no a single instance ?__) from multiple processes.

----

There is a lot `Chronicle` in FAQ, it should be more clear.

**Comment by peter-lawrey** [comment]
I agree it should be clearer.

For IndexedChronicle this is true. You can only have one process writing
and you must use locking if you have multiple threads writing.

However for all other Chronicle queue implementations support concurrent
writers in multiple JVMS and even remote appender across multiple machines.

We plan to do the same with Queue v4.

Regards, Peter.

**Comment by peter-lawrey** [comment]
The FAQ has been rewritten.
