### ISSUE TITLE
Chronicle.toEnd() not reaching the end

### ISSUE THREAD

**Issue by vach** [OpenHFT/Chronicle-Queue#228]
Discussion for this issue is here : https://groups.google.com/forum/#!topic/java-chronicle/ypyARB8K3zs
And the code for reproduction is here : https://gist.github.com/vach/ae958621eb02c8430d76

**Comment by lburgazzoli** [comment]
Can you please test latest 3.6.0-SNAPSHOT ?

**Comment by vach** [comment]
I've just tried it with the 3.6.0-SNAPSHOT and it behaves the same way, only case when i get up to date state of the queue is when i do nextIndex() in the loop... 

more than that, i think if you append in first app, then in second app (where the end is not visible) if you do append as well i think it will overwrite the data written by first app... because after append if you show current index it still will be behind...

**Comment by lburgazzoli** [comment]
You need to call nextIndex, that is a requirement.

For indexed queues you can't append from two instances unless you implement
a simchronization logic

On Wednesday, 30 December 2015, Vachagan Balayan <notifications@github.com>
wrote:

> I've just tried it with the 3.6.0-SNAPSHOT and it behaves the same way,
> only case when i get up to date state of the queue is when i do nextIndex()
> in the loop...
>
> more than that, i think if you append in first app, then in second app
> (where the end is not visible) if you do append as well i think it will
> overwrite the data written by first app... because after append if you show
> current index it still will be behind...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenHFT/Chronicle-Queue/issues/228#issuecomment-168038203>
> .
>


-- 
lb

**Comment by vach** [comment]
I agree about append, but you should be able to read, and with current state of things, if i'm having app A that appends all the other apps must spin trough whole thing before they reach the last index... toEnd() doesn't work as expected. 

Or toEnd() works correctly only for app that appends and is currently aware of the last position. For all other apps it does not work... it will jump to the point where the position was when chronicle was instantiated in that app.

I've looked in the source code and everything goes down to lastWrittenIndex in IndexedChronicle... hence if i do this from any reader application no matter when chronicle was instantiated it will work as expected...

IndexedChronicle indexedChronicle = (IndexedChronicle) queue; // have to cast to see the method
indexedChronicle.findTheLastIndex(); // read again from actual memory
tailer.toEnd(); // now we see correct result

my point is that .toEnd() shall automatically do this.

**Comment by vach** [comment]
Just like it happens when you call nextIndex() and change made from different process is now visible, the same way toEnd() shall check the actual memory and not rely on the state inside its application...

**Comment by lburgazzoli** [comment]
The latest code does so, there is a test case also for this

On Wednesday, 30 December 2015, Vachagan Balayan <notifications@github.com>
wrote:

> Just like it happens when you call nextIndex() and change made from
> different process is now visible, the same way toEnd() shall check the
> actual memory and not rely on the state inside its application...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenHFT/Chronicle-Queue/issues/228#issuecomment-168047564>
> .
>


-- 
lb

**Comment by lburgazzoli** [comment]
see https://github.com/OpenHFT/Chronicle-Queue/commit/659285ae53e777bf2e450a62f866bcbc13f9f40e

**Comment by vach** [comment]
Exactly what i wanted to do via pull request, but currently when i navigate to source of the snapshot, i still see the old code... what shall i do to get the latest version? I'm using gradle but i suppose something similar will be for maven...

**Comment by lburgazzoli** [comment]
It should be on Sonatype OSS I hope

**Comment by vach** [comment]
I had to make gradle to lookup for update for that dependency. Its fixed thanks for quick solution :)
