### ISSUE TITLE
Chronicle does not work on Windows 10 x64

### ISSUE THREAD

**Issue by pranasblk** [OpenHFT/Chronicle-Queue#234]
The thread ID = 77136 in x64 i a valid one (see e.g. https://blogs.technet.microsoft.com/markrussinovich/2009/07/05/pushing-the-limits-of-windows-processes-and-threads/), but Chronicle Vanila impl appender  has platform specific assertion which fails running VanillaAppenderImpl (VanillaChronicle: 549) code when assertions are enabled:

```
  @Override
        public void startExcerpt(long capacity, int cycle) {
            checkNotClosed();
            try {
                appenderCycle = cycle;
                appenderThreadId = AffinitySupport.getThreadId();
                assert (appenderThreadId & THREAD_ID_MASK) == appenderThreadId : "appenderThreadId: " + appenderThreadId;
//...
}
```

with message
```
java.lang.AssertionError: appenderThreadId: 77136 
```

**Comment by pranasblk** [comment]
Reproduced on net.openhft:chronicle:3.4.3

**Comment by lburgazzoli** [comment]
this is because on windows the pid is assumed to be of 16 bits, you can change the default by setting the system property os.max.pid.bits to to an higher value (like 24)

**Comment by peter-lawrey** [comment]
Is there a standard way to detect what is the maximum number of bits
Windows will use for a PID or perhaps we should just assume it is 24-bit
for Windows 10?

**Comment by peter-lawrey** [comment]
Queue v4 doesn't use the thread ID. Closing as v3 not under free support.
