### ISSUE TITLE
v 3.6.0 build failure

### ISSUE THREAD

**Issue by vontikov** [OpenHFT/Chronicle-Queue#238]
git clone https://github.com/OpenHFT/Chronicle-Queue.git
git checkout chronicle-3.6.0
cd chronicle-queue
mvn install

...
Tests run: 24, Failures: 0, Errors: 2, Skipped: 2, Time elapsed: 26.073 sec <<< FAILURE! - in net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest
testAppendAndReadWithRolling2[0](net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest)  Time elapsed: 0.522 sec  <<< ERROR!
net.openhft.chronicle.bytes.IORuntimeException: java.lang.ClassCastException: net.openhft.chronicle.bytes.VanillaBytes cannot be cast to net.openhft.chronicle.bytes.MappedBytes
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.testAppendAndReadWithRolling2(SingleChronicleQueueTest.java:187)
Caused by: java.lang.ClassCastException: net.openhft.chronicle.bytes.VanillaBytes cannot be cast to net.openhft.chronicle.bytes.MappedBytes
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.testAppendAndReadWithRolling2(SingleChronicleQueueTest.java:187)

testAppendAndReadWithRolling2[1](net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest)  Time elapsed: 1.005 sec  <<< ERROR!
java.lang.ClassCastException: net.openhft.chronicle.bytes.VanillaBytes cannot be cast to net.openhft.chronicle.bytes.MappedBytes
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.testAppendAndReadWithRolling2(SingleChronicleQueueTest.java:187)

Running net.openhft.chronicle.queue.impl.single.IndexOffsetTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.openhft.chronicle.queue.impl.single.IndexOffsetTest
Running net.openhft.chronicle.queue.impl.single.AsyncChronicleQueueTest
[main] WARN net.openhft.chronicle.bytes.MappedFile - Took 40 us to acquire chunk 0
appender file=/tmp/AsyncChronicleQueueTest-6530929045178141973/20160129.chronicle
tailer=/tmp/AsyncChronicleQueueTest-6530929045178141973/20160129.chronicle
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.073 sec - in net.openhft.chronicle.queue.impl.single.AsyncChronicleQueueTest
Running net.openhft.chronicle.queue.impl.single.IndexTest
[main] WARN net.openhft.chronicle.bytes.MappedFile - Took 63 us to acquire chunk 0
appender file=/tmp/IndexTest-5155067311534385843/20160129.chronicle
[main] WARN net.openhft.chronicle.bytes.MappedFile - Took 41 us to acquire chunk 0
appender file=/tmp/IndexTest-1757049053290928097/20160129.chronicle
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in net.openhft.chronicle.queue.impl.single.IndexTest

Results :

Tests in error:
  SingleChronicleQueueTest.testAppendAndReadWithRolling2:187 » IORuntime java.la...
  SingleChronicleQueueTest.testAppendAndReadWithRolling2:187 » ClassCast net.ope...

Tests run: 38, Failures: 0, Errors: 2, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by peter-lawrey** [comment]
Can you try this with queue v4?
