### ISSUE TITLE
BufferUnderflowException while Reading Boolean Value

### ISSUE THREAD

**Issue by hfcarbonell** [OpenHFT/Chronicle-Queue#246]
We are using Chronicle 3.5.3 with an indexed chronicle source and sink within our project, with objects using the writeMarshallable/readMarshallable methods from the BytesMarshallable interface to serialize to/from the queues. We've had issues in production under high volumes where the sink queue's tailer is throwing a buffer underflow exception at the readBoolean call- which is the last serialized field on our object. We have not been able to replicate this behavior in a unit test or even in load tests on our UAT hosts but it's happened several times now in production. We see no sign of the issue on other client queues when it occurs so it seems to be a client side issue rather than the source's server.

It seems like the nio client underneath is either writing a partial entry (skipping the boolean value) on occasion or the tailer is returning nextIndex() as true before the entry is fully written.

ERROR. tailer position: 577 tailer remaining: 0 tailer capacity: 59927839 tailer available: 0
java.nio.BufferUnderflowException
        at net.openhft.lang.io.AbstractBytes.returnOrThrowEndOfBuffer(AbstractBytes.java:200)
        at net.openhft.lang.io.AbstractBytes.readByteOrThrow(AbstractBytes.java:595)
        at net.openhft.lang.io.AbstractBytes.readBoolean(AbstractBytes.java:642)
        at com.jpmchase.riskone.ppx.dto.PositionDTO.readMarshallable(PositionDTO.java:737)
        at testing.ReadQueue.main(ReadQueue.java:30)

**Comment by peter-lawrey** [comment]
If you attempt to read this entry more than once, is it still corrupt? i.e.
is it written incorrect or does it appear to be reading it incorrectly?

**Comment by peter-lawrey** [comment]
FYI We don't plan to release new version of Chronicle Queue 3.x, except for
clients under support.

We are providing free support for Chronicle Queue 4.x

**Comment by hfcarbonell** [comment]
Hi,

I created a test reader to debug the contents of the file and we had the same bufferunderflow exception. It appears to have not written the boolean values at all.

Thank you,

Hilary

**Comment by hfcarbonell** [comment]
Are there any production ready versions of V4.x? I looked in the repository but the latest I see is 3.6

**Comment by peter-lawrey** [comment]
We are actively working on Queue V4.1 which builds, but has known
limitations.  We plan to release it next week.

Replication for Queue v4.1 will be in Queue Enterprise. It will have single
master replication initially, and we plan to support multi-master
replication.

**Comment by peter-lawrey** [comment]
We suggest using v4.x as this is the supported version.
