### ISSUE TITLE
Document file format and protocol

### ISSUE THREAD

**Issue by chinosanta** [OpenHFT/Chronicle-Queue#25]
For interoperability purposes (e.g. having non-java producers or consumers, and/or porting to another language like C/C++) it would be great to have more documentation on what the file format is and what the protocols are for the producer, consumers, and replicator.  More specifically:

1. What is the format of the files (index, data)
2. How are Chronicles initialized
3. How is a new Excerpt written
4. How does a consumer read an Excerpt
5. How does a consumer wait for new Excerpts
6. Documenting signaling between producers / consumers (if any)
7. How does replication work

I would be willing to write this document up based on my investigations but I'd need help from Peter.

**Comment by peter-lawrey** [comment]
Queue v4 has been designed to be self describing.  As such it would still need some documentation, but would require far less.
Please open a new issue for Queue v4 if you are still interested.
