### ISSUE TITLE
ExcerptTailer VanillaChronicle starts reading from beginning

### ISSUE THREAD

**Issue by bartonneil** [OpenHFT/Chronicle-Queue#251]
Have been using Vanilla Chronicle (3.4.2) for over a year and just encountered a weird issue after a hard-reset on machine.  We currently store the last read index in a separate file, so that on re-start of our app we can set the index on the ExcerptTailer using tailer.index(value).  

This has always seemed to work fine with no issues.  After this hard-reset, I noticed that upon restart we set the value as expected, but the subsequent read started at the very beginning of the Queue, as though no value was specified.  

Any thoughts as to whether this is a known issue?

**Comment by peter-lawrey** [comment]
When you do tailer.index(value) to need to check that this is successful.
It returns false if it is not successful.

On a hard reset, it is possible the end of the file is corrupt or not
actually peristed to disk. In this situation, the file is truncated so you
can continue.  This can mean that the index you wrote is not available so
the tailer.index(value) should return false, and not move the tailer's
index.  It starts at the start by default.

**Comment by bartonneil** [comment]
Thanks Peter - appreciate the quick turnaround on the question

**Comment by bartonneil** [comment]
Hi Peter,

Follow up question, since this is a fairly hard scenario to duplicate. 

In the case where tailer.index(value) returns false, what is the recovery process?
a) decrement the index value and continue trying until we receive a "true"
b) start at the beginning and scan forward until we catch up to our known location?
c) is there a way to force rebuild the index?
d) something else?

Any thoughts?

Thanks,

Neil

**Comment by peter-lawrey** [comment]
if tailer.index(value) returns true, you should be able to call toEnd() to
get the last available entry.

There is no way to rebuild the index in VanillaChronicle, however
SingleChronicle (in Queue v4) will re-build the index as needed.

**Comment by bartonneil** [comment]
so, if tailer.index(value) return false, I should call toEnd() to get the last available entry..  Does that mean I can just start reading from that point forward?  or is there some other manual process that needs to be done to get past this corruption?

Sorry for the slew of questions, but this is an extremely hard scenario to reproduce, although has occurred more than once on site -- with people pulling the power out of the machine.  

The underlying system is supposed to be lights-out, so I am trying to determine whether this scenario is recoverable in code, by skipping entries, or if manual intervention is involved.

Thanks

**Comment by peter-lawrey** [comment]
It's hard to say exactly what would fix the problem without reproducing it.
You should be able to get a copy of the files after a failure and
investigate what would be the best action in that case.
You could use index || toEnd but we haven't tested this for all possible
cases.
If general we recommend using replication to protect against such failure.

Regards, Peter.

**Comment by peter-lawrey** [comment]
In Queue v4, we have support for restarted a consumer from where it was up to https://vanilla-java.github.io/2016/03/29/Microservices-in-the-Chronicle-world-Part-4.html
