### ISSUE TITLE
Chronicle-Queue doesn't release queue file handle on Windows 10

### ISSUE THREAD

**Issue by imalygin** [OpenHFT/Chronicle-Queue#252]
Here is a demo code I have

```
import net.openhft.chronicle.queue.ChronicleQueueBuilder;
import net.openhft.chronicle.queue.ExcerptAppender;
import net.openhft.chronicle.queue.ExcerptTailer;
import net.openhft.chronicle.queue.RollCycles;
import net.openhft.chronicle.queue.impl.RollingChronicleQueue;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;

import java.nio.file.Files;
import java.nio.file.Path;

public class Demo {

    public static void main(String[] args) throws Exception {
        Path dir = Files.createTempDirectory("demo");
        SingleChronicleQueueBuilder builder  = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(RollCycles.DAILY);
        RollingChronicleQueue queue = builder.build();

        ExcerptAppender appender = queue.createAppender();
        appender.writeText("random text");
        ExcerptTailer tailer = queue.createTailer();
        System.out.println(tailer.readText());
        tailer.close();
        queue.close();

        assert queue.file().delete(); // assertion fails
    }
}

```
It fails on the very last line, because Java still holds a handle for a queue file. Is it a bug or I'm missing something? I found [relevant Java issue](http://stackoverflow.com/questions/4179145/release-java-file-lock-in-windows), but I'm not sure if it's the case. 

I tried to close `appender` explicitly as well, but it fails with this exception:

```Exception in thread "main" java.lang.IllegalStateException: Attempting to release Appender in Thread[main,5,main] but already released```

So I guess `appender` shouldn't hold anything.

**Comment by peter-lawrey** [comment]
The issue is related.
It is possible to fix this with some hacking as we have did in queue V3.
We just need to make sure queue v4 does the same. As our clients only use
Linux for production it hasn't been a problem and until about a week ago no
one reported it for windows.
I would like to fix it but at the moment I don't have the bandwidth. I hope
to have time next week.

Regards, Peter.

**Comment by imalygin** [comment]
Thank you for the response, Peter. Even though we use Linux for production as well, my workstation has Windows installed and I'd love to have the same behavior as on Linux machine locally. It would really help with testing.

**Comment by peter-lawrey** [comment]
I agree. I have Jira.
https://higherfrequencytrading.atlassian.net/browse/QUEUE-39

**Comment by peter-lawrey** [comment]
bump, this still needs to be reviewed in v4. Some improvements have been made.

**Comment by RobAustin** [comment]
fixed see net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest#checkReferenceCountingAndCheckFileDeletion

**Comment by imalygin** [comment]
That's a great news, thank you!

**Comment by imalygin** [comment]
I'm not sure how to reopen this issue, but I found a use case for which the fix doesn't work unfortunately. 
If the file was created beforehand it still is not released. 

Here is the code demonstrating this issue:

``    public static void main(String[] args) throws Exception {
        Path dir = Files.createTempDirectory("demo");

        SingleChronicleQueueBuilder builder = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(RollCycles.DAILY);

        long index = writeString(builder);
        readAndDelete(builder, index);
    }

    private static void readAndDelete(SingleChronicleQueueBuilder builder, long index) {
        SingleChronicleQueue queue = builder.build();
        ExcerptTailer tailer = queue.createTailer();
        tailer.moveToIndex(index);
        System.out.println(tailer.readText());
        for (File file : queue.file().listFiles()) {
            // trying to delete mapped file
            assert file.delete();
        }
    }

    private static long writeString(SingleChronicleQueueBuilder builder) {
        RollingChronicleQueue queue = builder.build();
        ExcerptAppender appender = queue.acquireAppender();
        appender.writeText("random text");
        long index = appender.lastIndexAppended();
        queue.close();
        return index;
    }``

**Comment by imalygin** [comment]
It's reproducible on 4.5.11

**Comment by peter-lawrey** [comment]
You can't delete a file which is in use on windows. You need to make sure
the queue was been closed correctly.

**Comment by imalygin** [comment]
Sorry, my bad. I forgot to close the queue after read in this example. I have some failures related to file deletions in my production code, but first I need to find a legit way to reproduce it in a standalone example.

**Comment by alpert** [comment]
Hi.

@peter-lawrey said: It is possible to fix this with some hacking as we have did in queue V3.

In which exact version of V3 this fix is?

**Comment by peter-lawrey** [comment]
I would try the latest version.
