### ISSUE TITLE
RollCycles.SECONDLY is commented out. Why? 

### ISSUE THREAD

**Issue by imalygin** [OpenHFT/Chronicle-Queue#257]
I'd like to write some test that would verify a behavior of roll cycles in my application, but a test that waits up to a minute till the next roll cycle is quite time consuming considering the fact that all the tests I have take 5 minutes to run. SECONDLY roll cycle would be very handy here, but unfortunately it's commended out and from the git blame it's not obvious if there is any good reason for that. 

Could you please tell me if it was commented for a reason? And, if it was, is there any way to force the roll even if roll period is not finished yet?

**Comment by peter-lawrey** [comment]
In latest version it is called TEST_SECONDLY and we have some tests for
rolling every second.

Peter.

**Comment by imalygin** [comment]
Sorry for the duplicate.
