### ISSUE TITLE
RollCycles.SECONDLY is commented out. Why? 

### ISSUE THREAD

**Issue by imalygin** [OpenHFT/Chronicle-Queue#258]
I'd like to write some test that would verify a behavior of roll cycles in my application, but a test that waits up to a minute till the next roll cycle is quite time consuming considering the fact that all the tests I have take 5 minutes to run. SECONDLY roll cycle would be very handy here, but unfortunately it's commended out and from the git blame it's not obvious is there a good reason for that. 

Could you please tell me if it was commented for a reason? And, if it was, is there any way to force the roll even if roll period is not finished yet?

**Comment by imalygin** [comment]
ok, I think I figured out how to force the roll cycle:

`val lastIndexAvailable : Long = ...
 val rollCycle : RollCycles = ...
  tailer.moveToIndex(rollCycle.toIndex(rollCycle.toCycle(lastIndexAvailable ) + 1, 0))`

So, if one winds index forward and adds a message, it's being added to a file from the next roll cycle. Is it the way it's supposed to work or I'm just lucky to get the behavior I need?

**Comment by imalygin** [comment]
Actually, this approach doesn't help much. Indeed, I fast-forwarded  tailer, but appender keeps on working with a file created for a current roll cycle. So I'm falling back to the original questions:
- Is there any way to consistently force roll? 
- Could you please return SECONDLY roll cycle?

**Comment by peter-lawrey** [comment]
I would only add to the current release which has TEST_SECONDLY already.

If you want to control rolling you should  provide a custom TimeProvider.
There is a SetTimeProvider for setting the time. See units tests where this
is used. This allows you to control exactly when the day/minute/second
rolls over by controlling the time.

Note: RollCycle is an iterface so say you want a TEN_MINUTELY cycle you can
add your own.

Regards, Peter.

**Comment by imalygin** [comment]
Thank you, Peter. TEST_SECONDLY works perfectly fine for me. I just missed that you've returned in the latest release (I used 4.3.2).

**Comment by peter-lawrey** [comment]
The problem has been that people take examples in unit tests and use it for
production without realising these are settings are only for testing
purposes.
