### ISSUE TITLE
UTFDataFormatException: malformed input around byte

### ISSUE THREAD

**Issue by uranium** [OpenHFT/Chronicle-Queue#26]
Test case:

Producer writes string consisting of 65632 characters 'a', and consumer tries to read it, but fails with:
java.lang.IllegalStateException: java.io.UTFDataFormatException: malformed input around byte 65535 ( to get other byte ordinals instead of 65535 - one can experiment with some characters other than 'a' whose UTF-8 encoding has more bytes ).

Produced string can be read with readUTFΔ from source Chronicle without any problem, but not from sink Chronicle.
This is what net.openhft.chronicle.tools.ChronicleReader shows near the end of sink data chronicle:
aaaa 8*\0c 1*\0^A 1*\0\xe0\x80^Daaaaa ...

Failing unit test: uranium/Java-Chronicle@656b350a452c2f3fd385a73f563d498b9dc39742

**Comment by peter-lawrey** [comment]
A test has been added for 1 MB strings for Queue v4.

Closing.
