### ISSUE TITLE
Tailer is rewinded unexpectedly if case of manual advance of index

### ISSUE THREAD

**Issue by imalygin** [OpenHFT/Chronicle-Queue#262]
I'm trying to read from a set of index files with possible gaps and here is another issue I encountered. After it reads all the available data, after I move index forward tailer unexpectedly starts over and returns data from the very beginning. 

Here is the demo of this issue:

```
package org.imalygin;

import net.openhft.chronicle.queue.ChronicleQueueBuilder;
import net.openhft.chronicle.queue.ExcerptAppender;
import net.openhft.chronicle.queue.ExcerptTailer;
import net.openhft.chronicle.queue.RollCycles;
import net.openhft.chronicle.queue.impl.RollingChronicleQueue;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import net.openhft.chronicle.wire.DocumentContext;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

public class Demo {

    private final ExcerptAppender appender;
    private final ExcerptTailer tailer;
    private final List<String> stringsToPut;
    private final RollCycles rollCycle;

    private Demo() throws IOException {
        Path dir = Files.createTempDirectory("demo");
        rollCycle = RollCycles.TEST_SECONDLY;
        SingleChronicleQueueBuilder builder = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(rollCycle);
        RollingChronicleQueue queue = builder.build();

        appender = queue.createAppender();
        tailer = queue.createTailer();

        stringsToPut = Arrays.asList("one", "two", "three");
    }

    private void writeStrings() throws Exception {
        DocumentContext writingContext = appender.writingDocument();
        writingContext.wire()
                .write().bytes(stringsToPut.get(0).getBytes());
        writingContext.close();

        Thread.sleep(2000);

        writingContext = appender.writingDocument();
        writingContext.wire().write().bytes(stringsToPut.get(1).getBytes());
        writingContext.close();

        Thread.sleep(2000);
    }

    private String readNextString() {
        DocumentContext readingContext = tailer.readingDocument();
        String res = null;
        if(readingContext.wire() != null) {
            res = readingContext.wire().read().text();
            readingContext.close();
        }
        return res;
    }

    private void moveIndexForward() {
        tailer.moveToIndex(rollCycle.toIndex(rollCycle.toCycle(tailer.index()) + 2, 0));
    }

    public static void main(String[] args) throws Exception {

        Demo demo = new Demo();

        // writes two strings immediately and one string with 2 seconds delay
        demo.writeStrings();

        System.out.println(demo.readNextString());
        demo.moveIndexForward();
        System.out.println(demo.readNextString());
        demo.moveIndexForward();
        // supposed to retun null, retuns 'one'        
        System.out.println(demo.readNextString());
    }

}

```

**Comment by peter-lawrey** [comment]
There is a know issue if you skip an entire cycle without writing anything.

Normally this is a daily or hourly cycle, so you have to not write anything
for a whole hour or day.

Never the less it is a bug and it should be fixed.

**Comment by imalygin** [comment]
Thank you for the confirmation, Peter.

**Comment by RobAustin** [comment]
@imalygin thanks for your test, I taken some of the work you did above and have rewritten it as this test case. We will fix this test shortly... regards Rob

` @Test
    public void testTailerWhenCyclesWhereSkippedOnWrite() throws Exception {

        final Path dir = Files.createTempDirectory("demo");
        final RollCycles rollCycle = RollCycles.TEST_SECONDLY;
        final SingleChronicleQueueBuilder builder = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(rollCycle);
        final RollingChronicleQueue queue = builder.build();
        final ExcerptAppender appender = queue.createAppender();
        final ExcerptTailer tailer = queue.createTailer();

        final List<String> stringsToPut = Arrays.asList("one", "two", "three");


        // writes two strings immediately and one string with 2 seconds delay
        {
            try (DocumentContext writingContext = appender.writingDocument()) {
                writingContext.wire()
                        .write().bytes(stringsToPut.get(0).getBytes());
            }
            try (DocumentContext writingContext = appender.writingDocument()) {
                writingContext.wire()
                        .write().bytes(stringsToPut.get(1).getBytes());
            }
            Thread.sleep(2000);
            try (DocumentContext writingContext = appender.writingDocument()) {
                writingContext.wire().write().bytes(stringsToPut.get(2).getBytes());
            }
        }

        System.out.println(queue.dump());

        for (String expected : stringsToPut) {
            try (DocumentContext readingContext = tailer.readingDocument()) {
                if (!readingContext.isPresent())
                    Assert.fail();
                String text = readingContext.wire().read().text();
                System.out.println("read=" + text);
                Assert.assertEquals(expected, text);

            }
        }


    }
`

**Comment by RobAustin** [comment]
see https://github.com/OpenHFT/Chronicle-Queue/commit/ac09506c55d1107806c8b13cac8feea6ef9b0c5d
