### ISSUE TITLE
Hitting sys.out.println in SCQIndexing

### ISSUE THREAD

**Issue by devinrsmith** [OpenHFT/Chronicle-Queue#265]
Hitting the following line:

```java
                if (posN != position)
                    System.out.println("posN: " + posN + " position: " + position);
//                    assert posN == position;
```

I'm assuming this shouldn't be happening?

**Comment by peter-lawrey** [comment]
Correct. It is something we are working on fixing now. It's a debug string
which was left in until it's fixed.

**Comment by peter-lawrey** [comment]
This should be fixed in the next release.
