### ISSUE TITLE
Chronicle-Queue requires read/write access to underlying files - no ability to open a chronicle for read-only

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#266]
As per https://groups.google.com/forum/#!topic/java-chronicle/yA5J5NXS2Jo

cheers

**Comment by belu** [comment]
That would be a nice feature.

**Comment by JerryShea** [comment]
BTW this is very easy to implement - have patched the Chronicle Queue that we are using - see https://github.com/JerryShea/Chronicle-Queue/commit/d8752397da6adbd108a852b40c649b70b1b051ab
