### ISSUE TITLE
Header in Header AssertionError when Rolling to a New Cycle

### ISSUE THREAD

**Issue by jasonblome** [OpenHFT/Chronicle-Queue#268]
I'm using the [Read|Write]BytesMarshallable interfaces to serialize to a queue that rolls every hour. When attempting to read from this queue at the index after it rolls to a new file, I get the AssertionError at the bottom of the following log:

> [DEBUG 20160710-10:14:00.006] [SingleChronicleQueueBuilder] File released /tmp/20160710-1413.cq4
[DEBUG 20160710-10:15:00.010] [SingleChronicleQueueBuilder] File released /tmp/20160710-1414.cq4
[INFO 20160710-10:15:02.156] [RollingCycleTest] Wrote 232600 messages
[DEBUG 20160710-10:15:02.185] [SingleChronicleQueueExcerpts$StoreTailer] moveToIndex: 1755f57 1068
[INFO 20160710-10:15:02.914] [RollingCycleTest] Could not read data at index: 65552 1755f55 1755f5500010010 you cant put a header inside a header, check that you have not nested the documents.
java.lang.AssertionError: you cant put a header inside a header, check that you have not nested the documents.
	at net.openhft.chronicle.wire.AbstractWire.writeHeader(AbstractWire.java:215) ~[chronicle-wire-1.7.0.jar:?]
	at net.openhft.chronicle.queue.impl.single.StoreRecovery.writeHeader(StoreRecovery.java:28) ~[chronicle-queue-4.4.4.jar:?]
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.newIndex(SCQIndexing.java:176) ~[chronicle-queue-4.4.4.jar:?]

Am I incorrectly using the ExcerptTailer in this case, or is there an issue with handling the rolling when tailing this file? 

Below is a simple test case for replicating the issue using a MINUTELY RollCycle :

`public class RollingCycleTest {
    private static final Logger LOGGER = LogManager.getLogger();

    private static class TestBytesMarshallable implements WriteBytesMarshallable, ReadBytesMarshallable {
        private static final Random rando = new Random();
        String _name;
        long _value1;
        long _value2;
        long _value3;

        public TestBytesMarshallable() {
            _name = "name_" + rando.nextInt();
            _value1 = rando.nextLong();
            _value2 = rando.nextLong();
            _value3 = rando.nextLong();
        }

        @Override
        public void writeMarshallable(BytesOut bytes) {
            bytes.writeUtf8(_name);
            bytes.writeLong(_value1);
            bytes.writeLong(_value2);
            bytes.writeLong(_value3);
        }

        @Override
        public void readMarshallable(BytesIn bytes) throws IORuntimeException {
            _name = bytes.readUtf8();
            _value1 = bytes.readLong();
            _value2 = bytes.readLong();
            _value3 = bytes.readLong();
        }
    }

    @Test
    public void testRollCycle() throws InterruptedException {
        final ChronicleQueue queue = ChronicleQueueBuilder.single("/tmp").timeoutMS(5).rollCycle(RollCycles.MINUTELY).build();
        final ExcerptAppender appender = queue.acquireAppender();
        final long endTime = System.currentTimeMillis() + TimeUnit.MINUTES.toMillis(2);
        int numWritten = 0;

        while (System.currentTimeMillis() < endTime) {
            for (int i = 0; i < 100; i++) {
                appender.writeBytes(new TestBytesMarshallable());
                numWritten++;
            }

            LOGGER.info("Wrote: {}", numWritten);
            TimeUnit.MILLISECONDS.sleep(50);
        }

        LOGGER.info("Wrote {} messages", numWritten);
        long numRead = 0;
        final TestBytesMarshallable reusableData = new TestBytesMarshallable();
        final ExcerptTailer currentPosTailer = queue.createTailer().toStart();
        final ExcerptTailer endPosTailer = queue.createTailer().toEnd();
        while (currentPosTailer.index() < endPosTailer.index()) {
            try {
                currentPosTailer.readBytes(reusableData);
            } catch (AssertionError e) {
                LOGGER.info("Could not read data at index: {} {} {} {}",
                        numRead,
                        Long.toHexString(currentPosTailer.cycle()),
                        Long.toHexString(currentPosTailer.index()),
                        e.getMessage(),
                        e);
                return;
            }
            numRead++;
        }

        LOGGER.info("Wrote {} Read {}", numWritten, numRead);
    }
}
`

Any insight would be appreciated.

Thanks!
Jay

**Comment by peter-lawrey** [comment]
This was a very useful test, and I have made a number changes.  This is the
test I have added.

https://github.com/OpenHFT/Chronicle-Queue/blob/master/src/test/java/net/openhft/chronicle/queue/RollingCycleTest.java

**Comment by jasonblome** [comment]
Thanks for the quick reply on this!

What is the release policy? Would this get published into maven central version 4.4.5?

**Comment by peter-lawrey** [comment]
I am looking to release 4.5.0 early this week.

**Comment by RobAustin** [comment]
@peter-lawrey - I assume this is now released, current version is 
-   <version>4.5.2-SNAPSHOT</version>

results from the test now look ok ( running for 10 seconds ) - so closing this issue. 

Connected to the target VM, address: '127.0.0.1:53136', transport: 'socket'
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 1900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 2900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 3900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 4900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 5900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 6900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 7900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 8900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 9900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 10900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 11900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 12900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 13900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 14900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 15900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 16900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17600
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17700
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17800
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 17900
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 18000
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 18100
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 18200
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 18300
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 18400
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote: 18500
[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote 18500 messages

[main] INFO net.openhft.chronicle.queue.ChronicleQueueTestBase - Wrote 18500 Read 18500
Disconnected from the target VM, address: '127.0.0.1:53136', transport: 'socket'
