### ISSUE TITLE
net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.StoreSupplier.checkDiskSpace

### ISSUE THREAD

**Issue by lzqdename** [OpenHFT/Chronicle-Queue#292]
net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.StoreSupplier.checkDiskSpace
there is a bug with this function.

###
SingleChronicleQueueBuilder builder = SingleChronicleQueueBuilder.binary("./" + "/trades");
then ,after we enter "net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.StoreSupplier.checkDiskSpace",

private void checkDiskSpace(File path) throws IOException {			
			final Path root = path.getParentFile().toPath().getRoot();
			if (root != null && root.getFileSystem() != null) {------------------->root is null!!!

root is null,you can fix it with  path=path.getAbsoluteFile();

**Comment by peter-lawrey** [comment]
Often if you issue a pull request we can merge this faster. I will look into this now.

**Comment by RobAustin** [comment]
@peter-lawrey you said ( in the comment above ) that you were fixing this now, I assume this issue is now fixed, so Im going to close this issue, if not please raise this issue again.
