### ISSUE TITLE
ClassAliasPool never using set ClassLoader

### ISSUE THREAD

**Issue by danielshrem** [OpenHFT/Chronicle-Queue#297]
Hi,

while trying to work around a ClassNotFound exception during reads from a queue (OSGI issues) i came across another issue relating to ClassLookup, ClassAliasPool. i tried to use the ClassLookup.create method passing it the the class loader instance we wanted. but we noticed its never used,  forName0 method (which is supposed to call it) is never called since the parent is never null (ClassAliasPool  L103).
Also we noticed that ClassAliasPool ctor's are private, having no way to create an instance with a null parent so at least it will be called (which a bad idea anyway).

is this how its supposed to be used? i think its a bug since i saw forName0 reverts to the parent in case the set class loader throws a ClassNotFoundException. so i think dropping the parent null check at L103 and just returning the result of forName0 should fix this issue.

Best Regards,

Daniel.

**Comment by danielshrem** [comment]
for now i managed to fix my issues by using ClassLookup.addAlias and adding all the classes i need. but that seems a bit too specific.

**Comment by RobAustin** [comment]
@danielshrem - thanks for raising this issue, please note that ClassAliasPool is in chronicle-core, so this issue should really be raised there, I'll take a look at this issue now. Also, we always welcome pull requests for issues like this, so please don't hesitate to submit them if you want to contribute. We welcome your suggestion of the fix. thank you.

**Comment by danielshrem** [comment]
your right, sorry for the misplacement. also next time ill also post a proper pull req.
thanks a lot for responding, we like this project a lot, and hope it will grow.

**Comment by danielshrem** [comment]
i created a proper PR, under chronicle-core, that fixes this issue

https://github.com/OpenHFT/Chronicle-Core/pull/18

cheers

Daniel.
