### ISSUE TITLE
Intermittent FileNotFound Exception on Windows (3.6.2)

### ISSUE THREAD

**Issue by erfil** [OpenHFT/Chronicle-Queue#298]
Looks like our appender is corrupting the index file intermittently.
We run with os.max.pid.bits=24

Data file created: data-28164-0
Corresponding index value written: 7,927,461,244,078,915,588
which is 7,209,984 and offset = 4
Note that 28,164 << 8 = 7,209,984

No idea how this could happen. Any suggestions are welcome.

Unfortunately we are not in a position to upgrade to version 4 at this stage.

**Comment by erfil** [comment]
Found the issue. Apologies. Had a rogue process started without the os.max.pid.bits parameter come in and put a "bad" message into the queue.

**Comment by peter-lawrey** [comment]
In queue v4 we use one file per cycle so this isn't an issue.
