### ISSUE TITLE
Incorrect ExcerptTailer reads after switching TailerDirection

### ISSUE THREAD

**Issue by malesch** [OpenHFT/Chronicle-Queue#299]
The index reading position of the ExcerptTailer (SingleChronicleQueue, Version 4.5.15) can get messed up when switching the TailerDirection.

Explanation with 4 integer values (values 0-4) inserted into the queue. 
`idx` indicates their index position in the queue:
```
Value |  Idx
------+------
  0   |   52
  1   |   53
  2   |   54
  3   |   55
```
The following table shows all steps with the operation (`read` for reading a value from the queue 
and `toggle` for changing the read direction of the Tailer), the return value and the tailer state _after_ performing operation:
```
Op      | Return value |  Tailer state
--------+--------------+----------------------------
read          0           direction=FORWARD,  idx 53
read          1           direction=FORWARD,  idx 54
toggle        -           direction=BACKWARD, idx 54
read          2           direction=BACKWARD, idx 53
read          1           direction=BACKWARD, idx 52
toggle        -           direction=FORWARD,  idx 52
```
In the next `read` operation it would be expected to get the value '0' back (the value at index position 52), however the following happens:
```
read          2           direction=FORWARD,  idx 53
```
Other example operations afterwards:
```
read          3           direction=FORWARD,  idx 54
toggle        -           direction=BACKWARD, idx 54
read          2           direction=BACKWARD, idx 53
```

**Comment by RobAustin** [comment]
Ive created the following test cases net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest#testIncorrectExcerptTailerReadsAfterSwitchingTailerDirection  ( which is check into the latest snapshot )

{code}
stored => sequence-number=52, value=0
stored => sequence-number=53, value=1
stored => sequence-number=54, value=2
stored => sequence-number=55, value=3
Return-value=0, seq=52, next-seq=53(35x0),direction=FORWARD
Return-value=1, seq=53, next-seq=54(36x0),direction=FORWARD
Return-value=2, seq=54, next-seq=53(35x0),direction=BACKWARD
Return-value=1, seq=53, next-seq=52(34x0),direction=BACKWARD
Return-value=0, seq=52, next-seq=53(35x0),direction=FORWARD
Return-value=1, seq=53, next-seq=54(36x0),direction=FORWARD

{code}

**Comment by RobAustin** [comment]
@malesch could you re-test your code with the latest snapshot an let me know if my fix, fixes your issue.

There was a bug in the way the internal state machine was handling a change from backwards to forwards. Which is now fixed in the latest snapshot.

**Comment by RobAustin** [comment]
essentially ( slightly over simplified ), when reading messages forwards, once you have read a message. The cursor ( that is, the point in the code that the user reads the bytes of the message from ) is in the correct position for you to read the next message, however if you are reading messages backwards, then once you have read the message the cursor has to be moved from the end of the last message to the start of the next message, This operation does not have to be performed for reading forwards, except in the case where you have just change from reading backwards to reading forwards, the code was not doing this, but this has now been fix.

I'm going to close this issue, ( if this fix does not address your issue please re-raise the issue ), regards - Rob

**Comment by malesch** [comment]
@RobAustin I quickly checked my test case and it looked fine here. Thanks a lot!
