### ISSUE TITLE
RollCycleMultiThreadTest fails intermittently

### ISSUE THREAD

**Issue by amichair** [OpenHFT/Chronicle-Queue#310]
While running a full 'mvn clean install', the build sometimes fails, maybe once in 5-10 runs. Here is a console excerpt of the failed test:

```
Running net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadTest
index=8000000000000000
index=42e700000000
Read a document êDay 3 data
index=8000000000000000
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE! - in net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadTest
testRead2(net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
        at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadTest.testRead2(RollCycleMultiThreadTest.java:172)

```
(the first lines are from testRead1, and only the last `index=8000000000000000` line is from testRead2. It looks like the tailer isn't seeing the data written by the appender. I'm not sure if this is a bug in the queue or in the test itself - is it guaranteed that a tailer on a separate thread immediately sees what is written by an appender?

(running on an SSD btw, in case disk speed matters.)

**Comment by peter-lawrey** [comment]
It's a guarentee we can make AFAIK.

**Comment by peter-lawrey** [comment]
Before a new cycle is created, the trailer/appender must poll to find if the cycle has been created, however to prevent the busy loop creating an aggressive amount of garbage this check was limited to once per milli-second. So if the file didn't exist when the trailer first checked it doesn't check again for a milli-second.

**Comment by RobAustin** [comment]
@amichair are you still finding this is and issue ( in the latest version ) ?

**Comment by RobAustin** [comment]
test now passes in the latest version.

**Comment by amichair** [comment]
Sorry for the delay, we put chronicle on hold for a while due to the various leaks and stability issues we encountered. Looks like there's recent progress there so we may give it another go...

Anyway, I just updated and ran the tests 15 times in a row with success. It's hard to tell for sure with intermittent failures, but you can consider the fix confirmed :-)
