### ISSUE TITLE
Pretoucher logic handles low update rates poorly.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#313]

**Comment by scottkidder** [comment]
I think this specific issue with the Pretoucher has been resolved.

**Comment by dpisklov** [comment]
@peter-lawrey is this resolved? Can we close this?

**Comment by peter-lawrey** [comment]
Not that i know of. Best to ask Rob.

**Comment by dpisklov** [comment]
@RobAustin Rob? :)

**Comment by RobAustin** [comment]
It’s possible but I have no evidence of this.

**Comment by dpisklov** [comment]
Shall we close this and if the issue occurs we just create a new one?
