### ISSUE TITLE
TreeMap encoding Issue

### ISSUE THREAD

**Issue by riadmaouchi** [OpenHFT/Chronicle-Queue#321]
The wire serialization fail for TreeMap (as object field). 

It throws a runtime exception:

`java.lang.ClassCastException: java.util.TreeMap cannot be cast to java.util.function.Supplier`

This not happened for SortedMap or NavigableMap

**Comment by peter-lawrey** [comment]
Can you provide a simple unit test to demonstrate this, and we will fix it?

**Comment by riadmaouchi** [comment]
Thank you for your feedback.

```
private interface Service {
        void onEventWithTreeMap(EventWithTreeMap event);

        void onEventWithSortedMap(EventWithSortedMap event);
}
```

```
private static class EventWithSortedMap extends AbstractMarshallable {
        final SortedMap<String, String> sortedMap;

        private EventWithSortedMap(SortedMap<String, String> sortedMap) {
            this.sortedMap = sortedMap;
        }
}
```

Please find below a success test using sorted map in event 

        // Given
        ChronicleQueue chronicleQueue = SingleChronicleQueueBuilder.binary(eventQueuePath).build();
        final Service service = chronicleQueue.acquireAppender()
                .methodWriter(Service.class);

        // When
        service.onEventWithSortedMap(new EventWithSortedMap(new TreeMap<>()));

        final MethodReader reader = chronicleQueue.createTailer()
                .methodReader(serviceImpl);

        // Then
        assertThat(reader.readOne()).isTrue();

Please find below a failing test using tree map in event 

```
private static class EventWithTreeMap extends AbstractMarshallable {
        final TreeMap<String, String> treeMap;

        private EventWithTreeMap(TreeMap<String, String> treeMap) {
            this.treeMap = treeMap;
        }
}
```

```
        // Given
        ChronicleQueue chronicleQueue = SingleChronicleQueueBuilder.binary(eventQueuePath).build();
        final Service service = chronicleQueue.acquireAppender()
                .methodWriter(Service.class);

        // When
        service.onEventWithTreeMap(new EventWithTreeMap(new TreeMap<>()));

        final MethodReader reader = chronicleQueue.createTailer()
                .methodReader(serviceImpl);

        // Then
        assertThat(reader.readOne()).isTrue();
```

**Comment by peter-lawrey** [comment]
Added https://github.com/OpenHFT/Chronicle-Wire/issues/40
ᐧ

**Comment by peter-lawrey** [comment]
I believe the fault is in Chronicle Wire.
ᐧ

**Comment by scottkidder** [comment]
This can be closed as it appears the issue was fixed in https://github.com/OpenHFT/Chronicle-Wire/commit/c91e7cf17913f294b387f7d2203a92728b105d98

**Comment by dpisklov** [comment]
Fixed
