### ISSUE TITLE
Can't currently build master: bom references non-existant artifacts.

### ISSUE THREAD

**Issue by andrm** [OpenHFT/Chronicle-Queue#322]
Can you please publish the dependencies?

[ERROR] Failed to execute goal on project chronicle-queue: Could not resolve dependencies for project net.openhft:chronicle-queue:bundle:4.5.23-SNAPSHOT: Failed to collect dependencies at net.openhft:chronicle-wire:jar:1.7.21 -> net.openhft:chronicle-threads:jar:1.7.3: Failed to read artifact descriptor for net.openhft:chronicle-threads:jar:1.7.3: Could not find artifact net.openhft:chronicle-bom:pom:1.13.45-SNAPSHOT in snapshots

**Comment by RobAustin** [comment]
the snapshot dependencies are already deployed by team city ( to maven central ) upon a successful build. You should not be trying to build the snapshot version of the code, but rather use the latest release.

**Comment by peter-lawrey** [comment]
We do publish the SNAPSHOTS but we don't support them. We only use them for allowing clients a pre-release check.
We suggest using release versions, or creating your own SNAPSHOT versions.

**Comment by andrm** [comment]
Thanks, I understand. I was trying to do create a test for the problem I was having, and wanted to know if it may be fixed already. Plus I thought it is easier for you to look at and integrate it if it's against master.

**Comment by andrm** [comment]
I apologize, just discovered how SNAPSHOTS work with maven.
