### ISSUE TITLE
Using a negative number for epoch fails.

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Queue#328]
failing test at #325

**Comment by peter-lawrey** [comment]
I have fixed this test over the range of -14 to +14 hours.

Note: epoch is when time starts relative to GMT+0 `System.currentTimeMillis()`.  In GMT-5, midnight is 5 hours after in GMT. i.e. epoch would be TimeUnit.HOURS.toMillis(5)  (i.e. positive)
