### ISSUE TITLE
Problem: Could not find artifact net.openhft:chronicle-bom:pom:1.13.45-SNAPSHOT

### ISSUE THREAD

**Issue by trevorbernard** [OpenHFT/Chronicle-Queue#329]
When updating to `chronicle-queue 4.5.22`, I was unable to pull down the latest code because of: `Could not find artifact net.openhft:chronicle-bom:pom:1.13.45-SNAPSHOT`

**Comment by andrm** [comment]
That's a mistake (IMHO) onm the 4.5.22 BOM. As a work-around you need to enable SNAPSHOTs in maven (or any other build system). If you use a local cache like artifactory you need to enable SNAPSHOTs in the cache repos as well there.

Pointers:
http://stackoverflow.com/questions/7713996/is-there-a-way-to-make-maven-download-snapshot-versions-automatically
http://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by peter-lawrey** [comment]
We should be releasing with a SNAPSHOT bom. We haven't found a way to
prevent this automatically, and the current process has been error prone.
If anyone knows a way to prevent a release with a SNAPSHOT bom, that would
be helpful.
ᐧ

**Comment by peter-lawrey** [comment]
BTW https://issues.apache.org/jira/browse/MRELEASE-949
ᐧ

**Comment by trevorbernard** [comment]
v4.5.24 solved the problem
