### ISSUE TITLE
Running Samples

### ISSUE THREAD

**Issue by rupinder10** [OpenHFT/Chronicle-Queue#351]
Running the samples InputMain and OutputMain. I ran the InputMain and submitted 3 messages. Those showed up fine when running OutputMain.

Then I ran InputMain the next day which created another cq4 file because of the rolling setup. I submitted two more messages. Running OutputMain threw a surprise. Instead of getting all the 5 messages from day 1 and day 2, I only see the 3 messages from day 1. What am I not understanding right ?

**Comment by MartyIX** [comment]
(I'm not sure if it helps to further diagnose the issue but I find https://github.com/OpenHFT/Chronicle-Queue#dumping-a-chronicle-queue-cq4-file-as-text-to-the-command-line useful)
