### ISSUE TITLE
How to read last N records from Chronicle Queue?

### ISSUE THREAD

**Issue by MartyIX** [OpenHFT/Chronicle-Queue#356]
Hi,

I have the following code to read from Chronicle queue (it's written in Kotlin but that does not matter):

    val queue = ChronicleQueueBuilder.single(path).build()
    val tailer = queue.createTailer()

    tailer.toEnd()

    // // This code is wrong
    //    val lastIndex = tailer.index()
    //
    //    val shift = lastIndex - 10
    //    if (shift > 0) {
    //        tailer.moveToIndex(lastIndex)
    //    }

    while (true) {
        val text = await(tailer)

        if (prefix == null) {
            println(text)
        } else {
            if (text.startsWith(prefix)) {
                // Would be nice without additional allocation ...
                println(text.substring(prefix.length + 1))
            }
        }
    }

How can I modify the commented code to read last 10 records from the queue and continue on? 

**Rationale:** It is useful in situations where the queue is used for displaying logs. You want to see a few previous logging statements and see new logging statements as they come.

I have asked the same question here: https://stackoverflow.com/questions/44757663/how-to-read-last-n-records-from-chronicle-queue but nobody seems to know.

Thank you

Regards,
Martin

**Comment by RobAustin** [comment]
Create a tailer. Set the direction backwards on the tailer. Call toEnd(). And read 10 messages ( this will read the last  messages in reverse so ignore them ). Then change the direction to forward. Now you will read the last 10 messages.

**Comment by peter-lawrey** [comment]
Can you say what the issue Is? This will work if you are not near the start
of a cycle. Also you can write two strings or any format to an excerpt
which would allow you the option to read just the prefix and optionally
read the object following if you wish. Note this might be a lot simpler if
the use the method reader/writer approach.

**Comment by MartyIX** [comment]
I have re-run my code with the latest version (4.6.6) and it works as expected. So it seems I encountered some bug in 4.5.5 that is fixed now.

Thanks you both!
