### ISSUE TITLE
BufferOverlow in SourceTcp$VanillaSerssionHandler (3.6.x)

### ISSUE THREAD

**Issue by erfil** [OpenHFT/Chronicle-Queue#360]
In the write method:
` 
int minSize = Math.min(size, writeBuffer.remaining());
bytes.read(writeBuffer, size);
writeBuffer.flip();
connection.writeAll(writeBuffer);
writeBuffer.clear();`

should probably be:
`bytes.read(writeBuffer, minSize);`

Any chance of fixing that?

**Comment by epickrram** [comment]
I’m sorry we don’t provide free support to chronicle queue 3, we only investigate and fix issues on the latest trunk version of our open source libraries, this is unless you hold a support contract.

If you would like further information on our various support contracts please email sales@chronicle.software.

**Comment by peter-lawrey** [comment]
Hello,

Can you issue a PR, ideally with a test case?

Thank you, Peter.
ᐧ
