### ISSUE TITLE
Request to add 'nextSynchronous' support to V4

### ISSUE THREAD

**Issue by paulbandler** [OpenHFT/Chronicle-Queue#363]
Chronicle Queue version 3 supports a '`nextSynchronous(Boolean)`' method on its appender to request that on completion of the current excerpt the memory mapped file be forced (fsync'd) to disk.  This feature is missing from Chronicle Queue version 4, blocking any possibility of replacing V3 with V4 in an existing deployment.  While the OpenHFT 'recommended' approach to guaranteed writes is to use replication, this is not an attractive option in an environment that provides for remote replication of persistent storage with its disk infrastructure.

**Comment by RobAustin** [comment]
Q4 does not support in the open-source version- "an environment that provides for remote replication of persistent storage with its disk infrastructure." without using queue replication. If you are interested we could explore some options with you, if so please contact sales@chronicle.software
