### ISSUE TITLE
Messages get skipped when using try-with-resource without consuming message

### ISSUE THREAD

**Issue by manstillman** [OpenHFT/Chronicle-Queue#367]
When calling tailer.readingDocument() the 'start' variable of the DocumentContext is set correctly, but 'readPosition' is moved to the next message. If no message is consumed (e.g. dc.wire().getValueIn().object() is never called), 'start' is moved to 'readPosition' during the call for close() when exiting the try-with-resource. This causes the message to be skipped.

I discovered this when trying to implement a check for whether any queue is present or not:

       try (DocumentContext dc = tailer.readingDocument()) {
            return dc.isPresent();
        }

Similarly, running something like 

       int i = 0;
       try (DocumentContext dc = tailer.readingDocument()) {
            i++;
        }
       try (DocumentContext dc = tailer.readingDocument()) {
            i++;
        }
       try (DocumentContext dc = tailer.readingDocument()) {
            i++;
        }
       System.out.println(i + "messages skipped");

causes 3 messages to be skipped.

Is this expected behavior (i.e. this construct should only used for consuming messages)? How would we then e.g. check for whether the queue is present or not, and so on?

I am using chronicle-queue version 4.5.27, but as far as I can see the same code is used in the latest version on GitHub, only that it's moved to the binary reader class and moved to the chronicle-wire package.

Thanks for making great open-source software!

**Comment by TerryW9** [comment]
Hi manstillman,

Thank you for your question and for pointing this issue out to us.

We will look into it and get back to you as soon as possible.

Best Regards,
Terry

**Comment by peter-lawrey** [comment]
Hello,
   This is expected behaviour to not require you to consume part or any of
the message so that simple schema changes and filtering can be supported.
You can check whether an index is available without actually reading it
using the following.

   // note: the tailer will not move forward again until you change
the direction to FORWARD   try (DocumentContext dc =
tailer.direction(TailerDirection.NONE).readingDocument()) {
        return dc.isPresent();
   }

   or

  return tailer.moveToIndex(tailer.index());

Regards,
  Peter
ᐧ

**Comment by manstillman** [comment]
Thanks for the quick reply!

Very interesting. I appreciate the usefulness of these patterns (for filtering on header level, etc). However, there seems to possibly be a bug during initialization/for the first message of the day.

When I try the following, the first message in the queue still gets skipped:

        ExcerptTailer tailer = SingleChronicleQueueBuilder.binary(path).build().getTailer();
        try (DocumentContext dc =
                tailer.direction(TailerDirection.NONE).readingDocument()) {
            System.out.println("Test");
        }
        Object object;
        try (DocumentContext dc =
                tailer.direction(TailerDirection.FORWARD).readingDocument()) {
            ValueIn valueIn = dc.wire().getValueIn();
            object = valueIn.object();
        }

(Here 'object' becomes the second message in the queue.)

This seems to be the case only for the first message in the queue. Doing this after the first message has been consumed, everything works as expected (no messages are skipped when calling the try-with-resource using direction NONE).

Please just let me know if you want any other info.

Ps.
tailer.moveToIndex(tailer.index()); works fine for the purpose of checking if the queue is present, not affecting consumption at all. :)

**Comment by epickrram** [comment]
Thanks for the bug report, this was non-intuitive behaviour. 
Fixed in fd47f887f8364e77139e5cf941567a589298d016
