### ISSUE TITLE
Length of chronicle queue

### ISSUE THREAD

**Issue by rupinder10** [OpenHFT/Chronicle-Queue#368]
Is there a way to get the length of the queue ? I mean the number of messages in the queue. I ask because I am moving from the old Chronicle to Chronicle Queue and there was a size() method that returned the count of messages. But I have not found the equivalent in Chronicle Queue.

**Comment by TerryW9** [comment]
Hi Rupinder,

Thank you for the question.

We will try to get an answer for you as soon as possible.

Best Regards,
Terry

**Comment by epickrram** [comment]
Hi Rupinder, you could use the following function to count the number of entries in the queue:

```
    private static long countEntries(final ChronicleQueue queue) {
        final ExcerptTailer tailer = queue.createTailer();
        tailer.toStart().direction(TailerDirection.FORWARD);
        long entryCount = 0L;
        while (true) {
            try (final DocumentContext ctx = tailer.readingDocument()) {
                if (!ctx.isPresent()) {
                    break;
                }

                entryCount++;
            }
        }
        
        return entryCount;
    }
```

**Comment by epickrram** [comment]
Hi Rupinder,
so that you don't have to read all the entries in the queue in order to get a count, I've added a method `SingleChronicleQueue.entryCount()`, which should calculate the number a little more efficiently.

**Comment by rupinder10** [comment]
Thanks you. That is exactly what I was hoping for. Thanks. When do we
expect a new stable release next ?

**Comment by epickrram** [comment]
I expect we'll be releasing within the next week or two.
