### ISSUE TITLE
Roll-cycle should be determined from existing queue files

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Queue#369]
When building a new queue instance, if there are existing queue files, the builder should initialise its rollCycle from the queue file header.

**Comment by peter-lawrey** [comment]
Can you review other parameters to see if these should be overridden by the
queue header?
ᐧ

**Comment by epickrram** [comment]
Will do..

**Comment by epickrram** [comment]
Looks like the only thing that would be sensible to validate is that the WireType of the queue matches the header. However, reading the header requires the WireType in order to supply a Wires object, so it's not possible to check this with the current header format.
