### ISSUE TITLE
Latest commit compilation fails on tests

### ISSUE THREAD

**Issue by archenroot** [OpenHFT/Chronicle-Queue#371]
326966] bytes remaining
>
  SingleCQFormat2Test.testWritingIndex:1710 expected:<...!!data
msg-16
...
[327139] bytes remaining
> but was:<...!!data
msg-16
...
[589283] bytes remaining
>
  SingleCQFormat2Test.testWritingThreeMessages:299->checkFileContents:404 expected:<...r Hello World
...
[327056] bytes remaining
> but was:<...r Hello World
...
[527760] bytes remaining
>
  SingleCQFormat2Test.testWritingTwentyMessagesTinyIndex:1162->checkFileContents:404 expected:<...: Bye for now
...
[326504] bytes remaining
> but was:<...: Bye for now
...
[527208] bytes remaining
>
  SingleCQFormat2Test.writeMarshallable:1437 expected:<...
  writePosition: 43[8,
  roll: !SCQSRoll {
    length: !int 86400000,
    format: yyyyMMdd,
    epoch: 0
  },
  indexing: !SCQSIndexing {
    indexCount: 8,
    indexSpacing: 1,
    index2Index: 0,
    lastIndex: 0
  },
  lastAcknowledgedIndexReplicated: -1,
  recovery: !TimedStoreRecovery {
    timeStamp: 0
  },
  deltaCheckpointInterval: 0
}
# position: 377, header: 0
--- !!data #binary
symbol: Symbol
side: Buy
limitPrice: 1.2345
quantity: 1e6
# position: 438, header: 1
--- !!data #binary
newOrder: !Order {
  symbol: Symbol2,
  side: Sell,
  limitPrice: 2.999,
  quantity: 10e6
}
...
# 32715]4 bytes remaining
> but was:<...
  writePosition: 43[2,
  roll: !SCQSRoll {
    length: !int 86400000,
    format: yyyyMMdd,
    epoch: 0
  },
  indexing: !SCQSIndexing {
    indexCount: 8,
    indexSpacing: 1,
    index2Index: 0,
    lastIndex: 0
  },
  lastAcknowledgedIndexReplicated: -1,
  recovery: !TimedStoreRecovery {
    timeStamp: 0
  },
  deltaCheckpointInterval: 0
}
# position: 377, header: 0
--- !!data #binary
symbol: Symbol
side: Buy
limitPrice: 1.2345
quantity: 1e6
# position: 432, header: 1
--- !!data #binary
newOrder: !Order {
  symbol: Symbol2,
  side: Sell,
  limitPrice: 2.999,
  quantity: 10e6
}
...
# 32716]4 bytes remaining
>

Tests in error: 
  SingleChronicleQueueTest.testFromSizePrefixedBlobs:3364 » BufferOverflow
  SingleChronicleQueueTest.after:105 » IllegalState Bytes not released properly ...
  SingleChronicleQueueTest.testFromSizePrefixedBlobs:3364 » BufferOverflow
  SingleChronicleQueueTest.after:105 » IllegalState Bytes not released properly ...
  SingleCQFormatTest.testNoHeader:112 » Internal a fault occurred in a recent un...

Tests run: 279, Failures: 8, Errors: 5, Skipped: 15

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Enterprise Root Parent Pom ......................... SUCCESS [  0.121 s]
[INFO] Third Party BOM (Bill of Materials) ................ SUCCESS [  0.232 s]
[INFO] Root Parent Pom .................................... SUCCESS [  0.004 s]
[INFO] Java Parent Pom .................................... SUCCESS [  0.663 s]
[INFO] OpenHFT/Chronicle BOM (Bill of Materials) .......... SUCCESS [  0.004 s]
[INFO] OpenHFT/Chronicle-Core ............................. SUCCESS [ 28.022 s]
[INFO] OpenHFT/Chronicle-Threads .......................... SUCCESS [  5.000 s]
[INFO] OpenHFT/Chronicle-Network .......................... SUCCESS [ 20.924 s]
[INFO] OpenHFT/Chronicle-Bytes ............................ SUCCESS [ 34.291 s]
[INFO] OpenHFT/Chronicle-Wire ............................. SUCCESS [01:29 min]
[INFO] OpenHFT/Chronicle-Queue ............................ FAILURE [02:07 min]
[INFO] OpenHFT/Chronicle-Values ........................... SKIPPED
[INFO] OpenHFT/Chronicle-Map .............................. SKIPPED
[INFO] OpenHFT/Chronicle-Engine ........................... SKIPPED
[INFO] OpenHFT/Chronicle-Websocket-Jetty .................. SKIPPED
[INFO] OpenHFT ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:06 min
[INFO] Finished at: 2017-08-10T16:23:06+02:00
[INFO] Final Memory: 63M/1425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project chronicle-queue: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/zangetsu/proj/java-libraries/OpenHFT/Chronicle-Queue/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :chronicle-queue

**Comment by epickrram** [comment]
Thanks @archenroot , taking a look.

**Comment by epickrram** [comment]
Ah, seems there are some changes in flight in the dependent repositories. This might take a bit longer to resolve.
