### ISSUE TITLE
UDT instead of UDP

### ISSUE THREAD

**Issue by eix128** [OpenHFT/Chronicle-Queue#376]
There is a project named , UDT
http://udt.sourceforge.net
also
https://github.com/JohannesBuchner/udt-java

With this library , you can directly use UDP as reliable and it works neat!
Maybe you can add 
UdtTransportAndNetworkConfig

for future and faster data transfer

**Comment by peter-lawrey** [comment]
Looks like a good suggestion. How does it compare with Aeron?
ᐧ

**Comment by eix128** [comment]
UDT is Supercomputing 2009 Bandwidth Challenge Winner
http://udt.sourceforge.net
