### ISSUE TITLE
moveToIndex() should be a no-op is StoreTailer is already at index

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Queue#382]

**Comment by RobAustin** [comment]
In addition, if 

abs(newIndex - oldIndex) < approx 70 message and in the same cycle, just do the linearScan rather than a full index lookup

**Comment by epickrram** [comment]
Linear scan forwards is easy, because the record header allows cheap scanning. If newIndex < oldIndex, then I need to do a byte-by-byte scan to try to identify the header record of the entry previous to oldIndex. This seems error prone (i.e. there must be some 4-byte data sequences that will satisfy `Wires.isData()`, even if they are not an actual header), so I suggest we only do the linear scan if newIndex > oldIndex.

**Comment by RobAustin** [comment]
I agree
