### ISSUE TITLE
Access to teamcity.higherfrequencytrading.com:8081/nexus/content is too slow

### ISSUE THREAD

**Issue by rmohta** [OpenHFT/Chronicle-Queue#383]
`teamcity.higherfrequencytrading.com:8081/nexus/content` seems to have been configured if the project version has Snapshot. For example, see below. Access to this Nexus repo is too slow (10min + just to download jars) and takes forever to compile the project for first time

> http://teamcity.higherfrequencytrading.com:8081/nexus/content/repositories/snapshots/org/openjdk/jmh/jmh-core/1.19/jmh-core-1.19.pom
> http://teamcity.higherfrequencytrading.com:8081/nexus/content/repositories/snapshots/org/hsqldb/hsqldb/2.4.0/hsqldb-2.4.0.pom

**Comment by RobAustin** [comment]
this repo is only available to clients that have signed  a support contract. If you are interested please contact sales@chronicle.software
