### ISSUE TITLE
Maven chronicle-bom missing chronicle-queue 4.6.25

### ISSUE THREAD

**Issue by aweisberg** [OpenHFT/Chronicle-Queue#384]
Doesn't seem to have an artifact uploaded to maven central. I ended up using 1.13.59 which has all the necessary artifacts for chronicle-queue present.

One reason this is important is that the license listed for chronicle-queue is lgpl in 1.13.59. Can't include it in an Apache project.

**Comment by dpisklov** [comment]
Cronicle doesn't publish Queue to maven central, reasons are described on this page: https://github.com/OpenHFT/Chronicle-Queue#download 
User is free however to git clone whatever version tagged and build locally. We distribute Chronicle Queue under Apache 2.0

**Comment by aweisberg** [comment]
OK that is a shame. We were going to use it in Apache Cassandra (https://issues.apache.org/jira/browse/CASSANDRA-13983), but we have to be able to distribute Cassandra via maven. I'm not sure maintaining our own artifacts for all the chronicle libraries is going to fly.

It's a little weird going to the trouble of re-licensing to Apache, but then not publishing artifacts to maven central so it can be used in compatible projects.

**Comment by dpisklov** [comment]
Sorry I didn't realise you work on Cassandra project. I will discuss your query with Commercial director and get back to you on this. Can you give me your email address to contact you directly?

**Comment by aweisberg** [comment]
I tried to send you an email at firstname.lastname@chronicle.software I didn't get a bounce so hopefully it arrived.

**Comment by dpisklov** [comment]
I even replied - did you not get my reply?

**Comment by aweisberg** [comment]
I did thanks. Missed it coming through.

**Comment by dpisklov** [comment]
@aweisberg hi Ariel, I've got the go ahead and will be releasing latest queue to maven central. I dropped you a question on an email, could you please check?

Thanks
