### ISSUE TITLE
Possible to write a partially serialised object

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#390]
The below code implements a typical pattern to write to a chronicle i.e. get the writing DocumentContext in a try-with-resources and close it when finished writing.
```
public class BinaryMethodWriterInvocationHandler ...
    ...
    @Override
    protected void handleInvoke(Method method, Object[] args) {
        try (@NotNull DocumentContext context = appender.writingDocument()) {
            Wire wire = context.wire();
            handleInvoke(method, args, wire);
            wire.padToCacheAlign();
        }
    }
```
If our thread is interrupted during the serialisation (which in this case happens during handleInvoke) then a java.nio.channels.ClosedByInterruptException is thrown during the close of the context. As the close seems to perform most of its function still, it appears to the chronicle (and any readers) that a valid object has been written although the object is only partially written.

See net.openhft.chronicle.queue.impl.single.NotCompleteTest#testInterruptedDuringSerialisation

**Comment by peter-lawrey** [comment]
We could have a common pattern for rolling back a message if an exception
is thrown.

**Comment by JerryShea** [comment]
Yes - agree. Although with try-with-resources the catch is run after the resource is closed. I think we need something like
```
        @NotNull DocumentContext context = appender.writingDocument();
        try {
            Wire wire = context.wire();
            handleInvoke(method, args, wire);
            wire.padToCacheAlign();
        } catch (Throwable t) {
            context.setRollback();
        } finally {
           context.close();
        }
```
which unfortunately is not as concise

**Comment by peter-lawrey** [comment]
For the most part, we should offer a higher level interface which means
this try/catch/finally block shouldn't need to be written by end users (or
not often)
ᐧ

**Comment by RobAustin** [comment]
@JerryShea I'm keen not to have a list of git issue that we never address, can you work on this or close is as a point of discussion.

**Comment by JerryShea** [comment]
@RobAustin, there is still a problem when we detect this situation and recover from it, but only with lazy indexing. I have a test for it, just not a fix yet. Will work on this week.
@peter-lawrey, agree with you about the higher level interface. Instead of the current pattern
```
        try (@NotNull DocumentContext context = appender.writingDocument()) {
           //  do something with context;
        }
```
I suppose we should support an API something like this
```
appender.writingDocument().writeWithContext(context -> {
           //  do something with context;
});
```
Any comments?

**Comment by peter-lawrey** [comment]
The problem with lambdas is structuring them so they don't create garbage.
There are tricks to make them non capturing but it would be useful to see
some real examples.

**Comment by JerryShea** [comment]
So, BinaryMethodWriterInvocationHandler could look something like this:
```
appender.writingDocument().writeWithContext(context -> {
    Wire wire = context.wire();
    handleInvoke(method, args, wire);
    wire.padToCacheAlign();
});
```
But the lambda may well have to moved in to a field as it captures this.handleInvoke in the above example.
The writeWithContext method would do the following:
```
void writeWithContext(Consumer<DocumentContext> toRun) {
    try {
        toRun.apply(context);
    } catch (Throwable t) {
        context.setRollback();
        Jvm.rethrow(t);
    } finally {
        context.close();
    }
}
```
And so any exception that occurred during writing would mean that the context would rollback the write. Some exceptions may mean that it is not possible to rollback the write (e.g. if we can no longer write to the chronicle) and so in this case, timedStoreRecovery will have to kick in next time it read from or written to.

**Comment by peter-lawrey** [comment]
Can you include the full non gc code as you may find this is more
complicated than having a rollback.

**Comment by peter-lawrey** [comment]
We could have an option to the context where a success method must be
called or the message is rolled back.

**Comment by JerryShea** [comment]
So we have 3 options:
1. higher level interface so the user doesn't have to worry about try/catch/finally. This is a bit of effort and a bit of change to the API
2. add a setRollback method to DocumentContext so the user can use the try/catch/finally pattern
3. add an option to context where a success (commit?) method must be called otherwise rollback
The easiest and lowest risk of these is 2. so I have implemented that with https://github.com/OpenHFT/Chronicle-Wire/commit/0ffaeb16d9541bac3bc0ab102ea52612d223a942

**Comment by RobAustin** [comment]
@JerryShea. Looks good, suggestion - rename setRollback() to rollbackWhenClosed() or perhaps  just rollback()

**Comment by peter-lawrey** [comment]
Note: we have the MethodReader / Writer as a higher level interface and
this should use any solution we come up with.

**Comment by JerryShea** [comment]
@peter-lawrey - yes - see https://github.com/OpenHFT/Chronicle-Wire/commit/6ece62bc75cd325319148ae55de5142c5053f0ff

**Comment by JerryShea** [comment]
Have documented this behaviour in a test and added doco.
