### ISSUE TITLE
Fix and test SCQIndexing#indexable condition

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#396]
indexable is called from `SingleChronicleQueueExcerpts.StoreTailer#inACycleFound:`
```
if ((index & indexSpacingMask) == 0)
    indexEntry(bytes);
```
```
private void indexEntry(@NotNull Bytes<?> bytes) throws StreamCorruptedException {
    if (store.indexable(index)
```
And `indexSpacingMask` is:
```
indexSpacingMask = queue.rollCycle().defaultIndexSpacing() - 1;
```
But in SCQIndexing#indexable condition is negated:
```
public boolean indexable(long index) {
    return (index & (indexSpacing - 1)) != 0;
}
```

**Comment by peter-lawrey** [comment]
This should be commented out (as it doesn't do anything) until it has
decent tests in place (as this functionality doesn't have any it appears)
ᐧ
