### ISSUE TITLE
Regression on moveToIndex

### ISSUE THREAD

**Issue by bdelbosc** [OpenHFT/Chronicle-Queue#401]
Hi,
I think there is a possible regression with 190a05ce2581a1cffa9aeaf3377be46ed2e0f5a8 introduced in 4.6.25 and still present on 4.6.41, 
I observe in some custom code that a tailer that is moving to a position P using `moveToIndex`, then performs some `readDocument` is not able to go back to the same position P, `moveToIndex` returns `true` but next `readDocument` is not done from the expected position.
Please tell me if I have missed some important changes or if you need a unit test.
Regards
ben

**Comment by RobAustin** [comment]
@bdelbosc  can you provide a failing test, thanks

**Comment by bdelbosc** [comment]
https://gist.github.com/bdelbosc/0a240b1afa6cef54a20ba80d587af3dd

**Comment by dpisklov** [comment]
That should've been fixed by #393 - can you check?

**Comment by RobAustin** [comment]
@bdelbosc  can you retest using the latest snapshot

**Comment by bdelbosc** [comment]
Ok if I apply e74360ef392801a01e167ec2c4183bc70253b6ec to 4.6.41 it fixes the problem.
I am not able to build 4.6.42 or snapshot version (http://nexus.chronicle.software/content/repositories/snapshots: Not authorized)
and I don't understand why the problem is present in 4.6.41 while the fix is supposed to be part of 4.6.38.
Do you have an idea for a release date with this fix ? in the meantime I will align my code to 4.6.24.

Thanks for your fast feedback and to @fmunch for reporting this in the first place ;)

**Comment by dpisklov** [comment]
4.6.38 definitely has e74360e in it, I can see it in the tag. I just ran your supplied unit test using 4.6.38 tag and it passes. Guess you can close the issue now.

**Comment by bdelbosc** [comment]
indeed yes e74360ef392801a01e167ec2c4183bc70253b6ec fix the provided unit test and it works since 4.6.38,
but it looks like there is another regression I do have custom tests that continue to fails since 4.6.25 including 4.6.41
still investigating ...

**Comment by dpisklov** [comment]
@bdelbosc ok let us know if you find some other issue.

**Comment by bdelbosc** [comment]
Here is a test that fails since 4.6.25 and it is not fixed in 4.6.41:
https://gist.github.com/bdelbosc/0a240b1afa6cef54a20ba80d587af3dd#file-testlibchronicleregressionbis-java

**Comment by epickrram** [comment]
Hi @bdelbosc this should be fixed on the latest snapshot version. Please re-test and let me know if this works for you. If so, I will release a new version.

**Comment by fmunch** [comment]
@bdelbosc FYI I still had a failing test in 4.6.39 too : [TestQueuingPattern](https://github.com/nuxeo/nuxeo-mqueues/blob/solocal-fork/nuxeo-mqueues-core/src/test/java/org/nuxeo/ecm/platform/importer/mqueues/tests/TestQueuingPattern.java). I will try again with the latest snapshot asap.

**Comment by bdelbosc** [comment]
Hi, I confirm that cherry-picking  f318ec7 in 4.6.41 fix the unit test and my custom tests (@fmunch it also fixes TestPatternBoundedQueuingChronicle#producerAndBuggyConsumers).
Thanks
