### ISSUE TITLE
Optimise jumping to the end of the queue for appenders  

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#402]
In the header we store the lastPosition ( which is the approximate address of the end of the queue )

Problem

Appenders that have not written for a while are having to scan down the queue to get to the end, there is some code that attempts to resolve this by detecting if the appenders are far away from the end, then just jumping tot the end, but this code looses the sequence number of the end of the queue. However, because we loose the sequence number we are currently over conservative before invoking this jump to the end. Because we are over conservative, apparently we are still spending a lot of time ( I don’t have the sats to hand ) linear scanning to  the end of the queue.

So, The problem is that we don’t know the sequence number of the end of the queue atomically with the lastPosition.

This proposal attempts to resolve this :

How about we introduce another LongValue into the queues header, lets call it the seqAndLastPosition that stores the sequence number in the lower bits and the ( lower bits of the address in higher bits, this would be done much in the same way that we store the index, containing both the cycle and seq number ), or to put it another way, this LongValue will store the end of the lastPosition in the same place that the index stores it’s cycle number.

When ever we store the lastPostion, we should also store the seqAndLastPosition.

so to get the the lastPosition and the sequence number of the approximate end of the queue, first we read the lastPosition, then we read the seqAndLastPosition, if the last bits of the lastPosition, match the higher bits of seqAndLastPosition we can be sure that these are atomic, however, if they don’t match we just retry, until they do match.

Hence we don’t have to any more linear scan too far down the queue or jump to the end without knowing what the sequence number of this address is !

**Comment by RobAustin** [comment]
@JerryShea can you review my implementation, especially around net.openhft.chronicle.wire.AbstractWire#tryMoveToEndOfQueue and uncomment this code in that method if you are happy with it, with the current code, commented out, this new code should have no effect, until you have finished your review

```
     // headerNumber(newHeaderNumber);
     // bytes.writePosition(lastPositionValue);
```

Also, 

 - Could you review its impact on lazy indexing as currently this approach is turned off if lazy indexing, and I'm not sure it should be.

- Could you profile it to see if it has a positive impact on preformance

**Comment by RobAustin** [comment]
@JerryShea to get the best performance I should ensure that both LongValues are on the same cache line, I have an idea of how to do this an retain backwards compatibility by copying then using the writePosition at the bottom of the header ensuring its next to the encodedSequence, @peter-lawrey  is keen to introduce a single type that encapsulates both these longValues.

**Comment by peter-lawrey** [comment]
I am looking to add TwoLongValue which will have two adjacent longs and
handle reading and writing both in a thread safe manner.

**Comment by RobAustin** [comment]
Thanks

**Comment by RobAustin** [comment]
@peter-lawrey I'll create the TwoLongValue now and add its use to chronicle queue

**Comment by peter-lawrey** [comment]
After review we can add a SCQ type so old file formats are ok but the new
files use a TwoLongValue field to improve the jumping to the end
performance.

**Comment by JerryShea** [comment]
Rob, I've done some basic reviewing and have parameterised this new functionality so we can test it more easily. The good news is that if I run the ContendedWriterTest from #404, we see some positive results in the test scenarios that this change is aimed at - see below, you can see that the slow-writing thread (thread1) looks better in all the below tests when we turn on -DenableFastForwardHeaderNumber=true:
Before
```
twoThreadsWritingLargeMessagesFastAndSmallMessagesSlow
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,150 / 1,150  1,410 / 5,370  12,320 - 16,520
thread1 progress=false writePause=0 between=5: 50/90 99/99.9 99.99 - worst was 467 / 705  5,110 / 15,990  85,980 - 85,980
twoThreadsWritingLargeMessagesFastAndSmallMessagesSlowAndDeferred
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,080 / 1,150  1,740 / 5,110  9,180 - 11,800
thread1 progress=true writePause=0 between=5: 50/90 99/99.9 99.99 - worst was 467 / 803  8,650 / 38,800  73,400 - 73,400
twoThreadsWritingLargeMessagesOneFastOneSlow
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,150 / 2,160  2,560 / 7,470  11,800 - 13,370
thread1 progress=false writePause=1 between=5: 50/90 99/99.9 99.99 - worst was 1,540 / 1,800  8,650 / 69,210  90,180 - 90,180
twoThreadsWritingLargeMessagesOneFastOneSlowAndDeferred
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,080 / 1,150  2,160 / 6,160  12,850 - 20,450
thread1 progress=true writePause=1 between=5: 50/90 99/99.9 99.99 - worst was 1,540 / 2,690  15,470 / 57,670  180,360 - 180,360
```
With enableFastForwardHeaderNumber
```
twoThreadsWritingLargeMessagesFastAndSmallMessagesSlow
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,080 / 1,150  1,280 / 4,590  6,950 - 12,850
thread1 progress=false writePause=0 between=5: 50/90 99/99.9 99.99 - worst was 451 / 639  2,420 / 11,800  19,400 - 19,400
twoThreadsWritingLargeMessagesFastAndSmallMessagesSlowAndDeferred
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,150 / 1,150  1,280 / 4,330  9,700 - 12,850
thread1 progress=true writePause=0 between=5: 50/90 99/99.9 99.99 - worst was 467 / 639  2,290 / 11,800  16,520 - 16,520
twoThreadsWritingLargeMessagesOneFastOneSlow
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,150 / 2,160  2,290 / 5,640  10,220 - 16,520
thread1 progress=false writePause=1 between=5: 50/90 99/99.9 99.99 - worst was 1,540 / 1,740  4,000 / 18,350  38,800 - 38,800
twoThreadsWritingLargeMessagesOneFastOneSlowAndDeferred
thread0 progress=false writePause=1 between=0: 50/90 99/99.9 99.99 - worst was 1,080 / 1,150  1,280 / 4,850  9,700 - 10,220
thread1 progress=true writePause=1 between=5: 50/90 99/99.9 99.99 - worst was 1,540 / 1,740  4,590 / 27,790  38,800 - 38,800
```

**Comment by RobAustin** [comment]
Thanks Jerry.

**Comment by RobAustin** [comment]
The was a later discussion around this

Joan

the problem was around, 

    at net.openhft.chronicle.queue.impl.single.RollCycleEncodeSequence.toLowerBitsWritePosition(RollCycleEncodeSequence.java:78)

the two version differ in the following respect.


new version

private long toLowerBitsWritePosition(long index) {
    return index >> cycleShift;
}

older version which is the version that you are using.

private int toLowerBitsWritePosition(long index) {
    return toCycle(index);
}

private int toCycle(long number) {
    return Maths.toUInt31(number >> cycleShift);
}
The problem  with the initial implementation was that it was calling toCycle() and although the shift was correct, cycle has an side effect of ensuring that the data only fits into the lower 31 bytes.
we should apply this restriction with toLowerBitsWritePosition() 

for a high level overview of why we are doing this see https://github.com/OpenHFT/Chronicle-Queue/issues/402 otherwise I'm happy to go over this on the phone will you,
