### ISSUE TITLE
shouldAllowDirectoryToBeDeletedWhenQueueIsClosed with read/write not working

### ISSUE THREAD

**Issue by cinquedea** [OpenHFT/Chronicle-Queue#411]
There is a SingleChronicleQueueTest.shouldAllowDirectoryToBeDeletedWhenQueueIsClosed test which is working without any problems as it is now.
However if you extend the test with write/read operations then data file remains locked by java process. It looks like problem is in tailer close procedure as appenders are closing correctly (without data file locking).

```
@Test
    public void shouldAllowDirectoryToBeDeletedWhenQueueIsClosed() throws IOException {
        final File dir = DirectoryUtils.tempDir("to-be-deleted");
        try (final SingleChronicleQueue queue =
                     builder(dir, wireType).
                             testBlockSize().build()) {
            try(final DocumentContext dc = queue.acquireAppender().writingDocument()){
                dc.wire().write().bytes("foo".getBytes());
            }
            try(final DocumentContext dc = queue.acquireTailer().readingDocument()){
                dc.wire().read().bytes();
            }
        }

        Files.walk(dir.toPath()).forEach(p -> {
            if (!Files.isDirectory(p)) {
                assertTrue(p.toString(), p.toFile().delete());
            }
        });

        assertTrue(dir.delete());
    }
```

**Comment by epickrram** [comment]
Hi @cinquedea 
what OS/Java version are you running on? I can modify the test as per your comment, and it still passes for me.

**Comment by cinquedea** [comment]
Hi @epickrram 

It's 1.8.0_152 x64 / Windows 10 Enterprise version 1607, build 14393.1884

I did a few more checks and it seems like data file release is happening asynchronously to close() call and it depends on wire type. If I put Thread.sleep(1000) (i7-5600U@2.6GHz if it helps) before delete then it's all good, with sleep(500) BINARY is failing but BINARY_LIGHT is green.

**Comment by cinquedea** [comment]
I've also noticed that in some tests (e.g. checkReferenceCountingAndCheckFileDeletion) you're doing waitFor(mappedFile::isClosed, "mappedFile is not closed"). It helps as well. Would it be possible to make that waiting part of the queue close procedure?

**Comment by epickrram** [comment]
Some of the references will only be closed on garbage collection.

Can you try adding:

`GcControls.waitForGcCycle();`

after the `try` block, but before the file delete operation?

**Comment by cinquedea** [comment]
@epickrram 

GcControls.waitForGcCycle(); doesn't help.

I believe I understand what's causing that difference in behavior between appender and tailer release. In first case it's happening sync. just in close method but in tailer case the current code resorts to queue based release with StoreComponentReferenceHandler. 
I've replaced it with a regular release and it works fine though obviously async release might've been done for a reason. I've create a branch with test + fix could you please take a look if it's going to work?
https://github.com/cinquedea/Chronicle-Queue/tree/deleteDirectoryAfterRead

**Comment by epickrram** [comment]
I've added the manual release to the StoreTailer's close() method. Please test and make sure it solves your problem. Can you also resolve/accept the stack-overflow question if so.

**Comment by cinquedea** [comment]
I'm not sure if it's going to work unless you remove context.wire(null); as we're setting null in that call and hence the next if check always false (release not happening)

**Comment by epickrram** [comment]
That's the trouble with not having a failing test :)

Should be fixed in  https://github.com/OpenHFT/Chronicle-Queue/commit/f099d543573f5b1df8fcc18d3d612a15a1fee6b3

**Comment by cinquedea** [comment]
thanks, looks good)
