### ISSUE TITLE
Reason for following exception: You can't know the index for an entry...

### ISSUE THREAD

**Issue by WolfAlexander** [OpenHFT/Chronicle-Queue#416]
Hi. 

What does the following error represent and what can be the reason for it?

```
java.lang.IllegalArgumentException: You can't know the index for an entry which hasn't been written. start: 711060, at: 713390, header: 0, toPos: 713390 
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScanByPosition(SCQIndexing.java:457) ~[chronicle-queue-4.6.59.jar:?] 
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.sequenceForPosition(SCQIndexing.java:541) ~[chronicle-queue-4.6.59.jar:?] 
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.sequenceForPosition(SingleChronicleQueueStore.java:321) ~[chronicle-queue-4.6.59.jar:?] 
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.resetPosition(SingleChronicleQueueExcerpts.java:321) ~[chronicle-queue-4.6.59.jar:?] 
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:272) ~[chronicle-queue-4.6.59.jar:?] 
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:343) ~[chronicle-queue-4.6.59.jar:?] 
        at net.openhft.chronicle.wire.MarshallableOut.writeDocument(MarshallableOut.java:95) ~[chronicle-wire-1.10.3.jar:?] 
```

**Comment by RobAustin** [comment]
It looks like chroncle-queue’s indexes are messed up

which version are you using ? Could you write a simple unit test that reproduces this problem.

**Comment by WolfAlexander** [comment]
Chronicle queue 4.6.59

I cannot reproduce the problem, but our client can. We could not found any correlation with any other events that happened at that time in the system.

**Comment by RobAustin** [comment]
If you be interested in getting a support contract please contact sales@chronicle.software, otherwise we will fix this issue on a best efforts basis and especially without a unit test its unlikely to be given a very high priority.   Thanks for raising this issue, and if we are able to reproduce it we will definitely fix it.

**Comment by WolfAlexander** [comment]
Thank you. 

It might be that we are defining chronicle queue package version manually and do not define any other packets (wire, bytes etc). We will try with chronicle-bom instead - maybe some versions of chronicle queue, wire, bytes etc are not really compatible and it get it wrong when we define only chronicle-queue version.

**Comment by RobAustin** [comment]
yes - we always recommend you use the chronicle-bom, I’d be interested to know if this makes a difference.

**Comment by WolfAlexander** [comment]
That did not solve the problem.

**Comment by dpisklov** [comment]
@WolfAlexander That can be a symptom of multithreaded use of appender. Please ensure you don't share appenders between threads as they are not thread-safe. One must acquire appender per thread (they are thread local).

**Comment by peter-lawrey** [comment]
Sharing an appender between threads should be fixed in the latest versions.
It now uses a ThreadLocal object to hold state.
ᐧ

**Comment by WolfAlexander** [comment]
I believe that appenders are not shared, but we will check again.

We are running chronicle-bom, version 1.13.59 which is a bit old. Which version would you recommend to run? 1.15.17?

**Comment by dpisklov** [comment]
@WolfAlexander 
1.15.24 bom might be a good choice.
Let us know if you still see this issue with latest BOM.

**Comment by JerryShea** [comment]
Do you have multiple writers to the same queue, and do you see TimedStoreRecovery happening? TimedStoreRecovery logs at warn level if it has to recover so you should be able to see easily.

**Comment by WolfAlexander** [comment]
As functionality - no, no multiple writers to same queue. We will try to check TimedStoreRecovery in logs.

It looks like the problem was in using SAN (Storage area network) drives. It works in the beginning, but then fails after a while. When writing chronicle queues to same machine - everything works fine. Does it (usage of SAN for chronicle queues) give you any idea about why we got the exception?

**Comment by dpisklov** [comment]
Chronicle doesn't support any network file systems (SAN included), because
they may not fully support memory mapping of the files. We strongly advise
customers and users to only every place chronicle queue files on local
disk. (on a separate note, we recently discovered that performance on XFS
is inferior comparing to ext4...)

**Comment by WolfAlexander** [comment]
Now we know why and we will make sure that network file systems are not used. Thank you for fast replies!
