### ISSUE TITLE
Issue with Tailer behaviour over cycle roll

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Queue#417]
User-reported issue replicated in `ChronicleRollingIssueWithDirectionsTest`.

**Comment by epickrram** [comment]
The issue here seems to be that if an `ExcerptTailer` is uninitialised (i.e. created from a queue before any appends have been made to said queue), **and** the `TailerDirection` is `BACKWARD`, then the Tailer will roll forwards to the first document in the queue.

This is a bug, and has been fixed. 

The reporter's implementation of the `peek()` method was flawed, as it attempted to consume a message using `TailerDirection.NONE`.

Correct `peek()` implementation should do something like:

```
void peek(ExcerptTailer tailer, Consumer<ExcerptTailer> receiver) {
    long oldIndex = tailer.index();
    tailer.direction(TailerDirection.FORWARD);
    try (DocumentContext context = tailer.readingDocument()) {
        if (context.isPresent()) {
            if (oldIndex == 0) {
                oldIndex = context.index();
            }

            receiver.accept(tailer);
        }
    }
    tailer.moveToIndex(oldIndex);
}
```

though a peek-style operation is not a supported use-case.

**Comment by cmunger** [comment]
Tested your fix and implementation suggestion on my production code base, working fine, thanks a lot. Happy new year !
