### ISSUE TITLE
Allow queue cycle files to be pre-created before they are required.

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Queue#418]
The current implementation will produce undesirable results if a `.cq4` file is created by some other process before it is needed by a reader or writer.

**Comment by JerryShea** [comment]
Please see https://github.com/OpenHFT/Chronicle-Queue/commit/7cd09f3c23d1520e9ce93771ced936d2351d3580 and https://github.com/OpenHFT/Chronicle-Queue/commit/77823f663039eef7bd255f713147d91ee0655f7c which fixes tailing for empty files (done for customer issue #63)
