### ISSUE TITLE
Move duplicated metadata from the cq4 header into the table store

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#423]
- Move wireType, roll, lastAcknowledgedIndexReplicated,deltaCheckpointInterval, lastIndexReplicated, sourceId to avoid duplication
- store writePosition field as a write position across cycles
- consider moving indexing with the view to always expect index2index to be at pos 0 in the cq4 file
- also consider storing index separate from data?

**Comment by RobAustin** [comment]
@dpisklov cool, could you add any more detail, if required - thanks

**Comment by peter-lawrey** [comment]
1) Identify the quick wins we feel should take less than a week
2) After that review the riskier to implement changes
3) Ensure we can support named tailers in the future.
4) look at merging the two table stores and what tools we would need to add to support it.
5) Ensure all our tooling still works with the new format.
6) Test with queue enterprise, FIX and services.

**Comment by dpisklov** [comment]
Will need to test:
- Reading files created with earlier versions of a queue
- Reading new cq4 files without metadata - one file or many files (created with different roll cycle)
- Dump

**Comment by dpisklov** [comment]
So I implemented most of it and tested with Services (which includes FIX) and Queue Enterprise. Also there's a new tool introduced to unlock the queue:
```
$ bin/unlock_queue.sh <queue_path>
```
What's left:

1. Add timezone to metadata - awaiting #511 
2. More risky changes:
2.1. Move SCQIndexing to metadata tablestore - fairly low risk, for now we can leave index2index as a separate field in SCQStore pointing to index2index location. Alternatively we can consider including index2index into the header in its entirety (might be the most optimal way of doing it)
2.2. Consider making writePosition cycle-agnostic and more it to metadata as well.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.13 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.13), BOM-1.16.170 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.170)
