### ISSUE TITLE
Look at running Chronicle Queue with JEP

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#428]
JEP allows Python to run from Java.
https://github.com/ninia/jep

Need to create a working example of reading and writing messages from Chronicle Queue.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.42](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.42), [BOM-2.20.67](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.67)
