### ISSUE TITLE
Look at how Queue and Avro can work together.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#429]
Document some working examples.

**Comment by RobAustin** [comment]
see https://avro.apache.org

**Comment by MartyIX** [comment]
https://github.com/MartyIX/avro/commit/dac2dc74c01f7ee108bc35014d74449dce1f3903 - This is a very simple demonstration. It has rough edges though:

* EncoderByteArrayOS 
* Creating `BinaryDecoder` as its implementation is no re-usable by design.
* ...

**Comment by dpisklov** [comment]
@MartyIX thanks for the inspiration, I used your example and slightly adjusted it to create a sample

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.149](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.149)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
