### ISSUE TITLE
Dump queue should show all messages written with bytes

### ISSUE THREAD

**Issue by chipFraser** [OpenHFT/Chronicle-Queue#433]

**Comment by RobAustin** [comment]
@chipFraser can you add a description and more detail of what is required here - please

**Comment by RobAustin** [comment]
@chipFraser you referring to net.openhft.chronicle.queue.DumpQueueMain?

**Comment by RobAustin** [comment]
@EmmaChronicle  and @chipFraser if so, I think the best solution will be for us to write a DumpQueueMain for Chroncile-Services as this is able to understand the type of the DTO's written based on the information in the services.yaml config.

**Comment by RobAustin** [comment]
Alternatively and a simpler solution would be to provided a additional argument to DumpQueueMain, so that the user can provide the .class of the data. Which would be much simpler to implement and can go into the Chronicle-Queue project. @peter-lawrey I welcome your thoughts.

**Comment by chipFraser** [comment]
A similar requirement may be required for  ChronicleReaderMain and YamlTester as well ?

**Comment by RobAustin** [comment]
ChronicleReaderMain works with bytes so closing.
