### ISSUE TITLE
Fixed the version badges which have stopped working

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#450]
Could you investigate the version badges, at time of writing, it appears to be broken ( on all projects not just queue ), see image below:
 
<img width="307" alt="screen shot 2018-03-28 at 12 21 24" src="https://user-images.githubusercontent.com/6506056/38026111-c777f7c0-3282-11e8-9ea5-2e227a060781.png">

**Comment by dpisklov** [comment]
heroku app that we are using for the badges is down, in issues (https://github.com/jirutka/maven-badges/issues/20) people suggest instead using this:

https://shields.io/

**Comment by tomshercliff** [comment]
This looks to be working fine again now so closing - can re-open if it happens again and discuss options.
