### ISSUE TITLE
Read only chronicle unable to make use of caching mechanism

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#453]
... and leads to poor performance when tailing from a queue with missing .cq4 files. This is because of using the FileSystemDirectoryListing instead of TableDirectoryListing.

For example, if you have an hourly rolling queue, and nothing has been written to it in the last hour, then there will not be a .cq4 file present for the current hour and trailing from this queue with a readOnly queue will exhibit this performance problem.

**Comment by JerryShea** [comment]
See https://github.com/JerryShea/chronicle_tailers_jmh

**Comment by JerryShea** [comment]
To solve this, we could put optionally store the directory-listing.cq4t file somewhere else (@RobAustin suggested tmpfs)

**Comment by dpisklov** [comment]
As discussed with Rob, currently there's no way to get any new data in a queue which has no metadata file - the latter will be restored on the first write attempt. Hence the readonly mode without metadata is only used a stop-gap solution where performance is likely to be irrelevant anyway, so I'll close this for now - @JerryShea if you disagree let me know we can discuss this further
