### ISSUE TITLE
Log Compaction

### ISSUE THREAD

**Issue by longshorej** [OpenHFT/Chronicle-Queue#454]
First off, I want to say thanks for Chronicle Queue!

We're using it for a project and one feature we wished it had is log compaction. Our model has a key (i64) for each item that we add to the queue. The process of log compaction would be removing any items for which a newer one exists on the queue with the same key. The main purpose is to save disk space.

I'm wondering if there's any interest in adding this feature to Chronicle Queue, and what an implementation could look like (if it's technically possible/reasonable). We'd be happy to work on such a feature and contribute it back to the project if desired.

Thanks for any thoughts and discussion you can offer.

**Comment by dpisklov** [comment]
Chronicle Queue is append-only by design. The only way to achieve what
you're after is read the existing queue backwards, writing entries with the
key you haven't seen yet. However that should be an offline operation -
after which you delete original queue and replace it with a new one you
just created.

Although that's possible, are you sure queue is right for use case? By what
you described, you'd better off with Chronicle Map...

**Comment by longshorej** [comment]
Thanks for the info @dpisklov. It sounds like the feature is in conflict with the design of Chronicle Queue then. FWIW, Kafka has an implementation of this concept: http://cloudurable.com/blog/kafka-architecture-log-compaction/index.html

> Although that's possible, are you sure queue is right for use case? By what you described, you'd better off with Chronicle Map...

I agree that a map better fits our use-case, but in our situation we're trying to reduce operational overhead. To that end the inefficiency of using a queue in this manner is something we can afford.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.107 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.107), BOM-1.15.284 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.284)

**Comment by huntc** [comment]
Is there any more info on log compaction given the release back in 4.6? For example, does it rely on an app making its own decision on when to remove a file belonging to Chronicle Queue?

**Comment by dpisklov** [comment]
@huntc  There's no log compaction available in the Chronicle-Queue and there's no plan to introduce anything similar.
Unfortunately the issue was closed without adding wontfix label so our release job picked this up as fixed, I'll delete the misleading comment...

**Comment by huntc** [comment]
Thanks for the clarification!
