### ISSUE TITLE
Since queue won't write a excerpt when being interrupted, there is no point starting it.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#463]
Jerry can you review as you made the original change in close()

**Comment by JerryShea** [comment]
LGTM!

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.104 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.104), BOM-1.15.267 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.267)
