### ISSUE TITLE
Remove retries on setFirstAndLastCycle to reduce latencies

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#464]

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.105 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.105), BOM-1.15.272 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.272)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.105 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.105), BOM-1.15.274 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.274)
