### ISSUE TITLE
fixed possible dangling file reference to queue-lock.cq4t on queue.close()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#465]
Apparently ( reported by one of our clients ) the following test net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest#testCleanupDir fails of windows because it leave the queue-lock.cq4t in the directory and then the test is not able to then delete the directory. On the mac this problem is NOT reproducible but fails on windows.

```
   @Test
    public void testCleanupDir() {

        File tmpDir = getTmpDir();
        try (final RollingChronicleQueue queue =
                     builder(tmpDir, wireType)
                             .build()) {
            final ExcerptAppender appender = queue.acquireAppender();

            try (DocumentContext dc = appender.writingDocument()) {
                dc.wire().write("hello").text("world");
            }


        }
        DirectoryUtils.deleteDir(tmpDir);
        Assert.assertFalse(tmpDir.exists());
    }

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.107 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.107), BOM-1.15.284 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.284)
