### ISSUE TITLE
Queue gets detached if the tailer is readonly and it encounters file without EOF (even if there're more files to follow)

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#469]

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.107 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.107), BOM-1.15.284 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.284)
