### ISSUE TITLE
JVM crashes if trying to create tailer in readOnly mode from the directory with truncated file

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#470]

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.0), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)
