### ISSUE TITLE
Large number of file handles open

### ISSUE THREAD

**Issue by NickWard** [OpenHFT/Chronicle-Queue#472]
Further information emailed.

**Comment by RobAustin** [comment]
We have been unable to find any issue with the file handles, we have updated the docs with the following:

https://github.com/OpenHFT/Chronicle-Queue#file-handles-and-flushing-data-to-the-disk

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.6.109 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.6.109), BOM-1.15.300 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.300)
