### ISSUE TITLE
C++ Chronicle Queue

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#473]
Added as a place holder

- This work should be carried out in its own repo.
- Initially we will create a C++ Queue ( Lite ), the exact functionality of which is yet to be decided.

**Comment by lburgazzoli** [comment]
that’s awesome guys.

**Comment by shuckc** [comment]
If of interest, I ported it to C - https://github.com/TeaEngineering/libchronicle

**Comment by RobAustin** [comment]
We are planning to do this, it won't be open source, if you are interested in evaluating a beta version please contact sales@chronicle.software. I'm going to close this issue as it has now moved to the following project - https://github.com/ChronicleEnterprise/Chronicle-Queue-CPP

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.44 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.44)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
