### ISSUE TITLE
Calling pretouch() now also pre rolls as well as pre-touching

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#484]

**Comment by RobAustin** [comment]
we added call to

``` net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts.StoreAppender#earlyAcquireNextCycle
```

this can cause the EOF to be written to the previous cycle, causing the current cycle file to roll.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.0), BOM-1.16.3 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.3)
