### ISSUE TITLE
Fixed flaky test SingleChronicleQueueTest.testReadingDocumentWithFirstAMoveWithEpoch

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#485]
see http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=256815&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleQueue4_Snapshot

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.2 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.2), BOM-1.16.19 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.19)
