### ISSUE TITLE
Large messages causing crash in different ways

### ISSUE THREAD

**Issue by jooybar** [OpenHFT/Chronicle-Queue#487]
In the documentation there is no mention of message size limitation.
Here is a sample code which cause a break on Linux:
```java
import net.openhft.chronicle.core.UnsafeMemory;
import net.openhft.chronicle.queue.ChronicleQueue;
import net.openhft.chronicle.queue.ChronicleQueueBuilder;
import net.openhft.chronicle.queue.ExcerptAppender;
import sun.misc.Unsafe;

public class CQAppenderTest {
	static final int ITER = 2;
	static final int SIZE = 50 * 1000 * 1000;
	public static void main(String[] args) {
		ChronicleQueue queue = ChronicleQueueBuilder.single("queueDir").build();
		final ExcerptAppender appender = queue.acquireAppender();
		byte[] array = new byte[SIZE];
		long startTime = System.currentTimeMillis();
		for (int i = 0; i < ITER; i++) {
			appender.writeBytes(b -> {
			    long address = b.addressForRead(b.writePosition());
			    Unsafe unsafe = UnsafeMemory.UNSAFE;
			    unsafe.copyMemory(array, Unsafe.ARRAY_BYTE_BASE_OFFSET, null, address, array.length);
			    b.writeSkip(array.length);
			});
		}
		long estimatedTime = System.currentTimeMillis() - startTime;
		System.out.println("time = " + estimatedTime);
	}
}
```
And here is the error message:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fddf138f172, pid=25577, tid=0x00007fddf2791700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x803172]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# ~/smallTests/CQTest/hs_err_pid25577.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```
Also, I have tried to write message with `appender.writeDocument`. Although it works with 50MB message, it fails with 100MB message size:
```
Exception in thread "main" java.lang.IllegalArgumentException: pos: 100131612, store.writePosition()=131584 queue.blockSize()=67108864
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.position(SingleChronicleQueueExcerpts.java:495)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.access$2000(SingleChronicleQueueExcerpts.java:66)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$HeaderWriteStrategyOriginal.onContextOpen(SingleChronicleQueueExcerpts.java:841)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:332)
	at net.openhft.chronicle.wire.MarshallableOut.writeDocument(MarshallableOut.java:95)
	at CQAppenderTest.main(CQAppenderTest.java:22)
```

**Comment by peter-lawrey** [comment]
That's to be expected.  The default chunk size is 64 MB with 16 MB of overlap. If you write natively more than 16 MB you are going to be writing to random memory.

**Comment by RobAustin** [comment]
hence, you could increase your block size see net.openhft.chronicle.queue.ChronicleQueueBuilder#blockSize(int) , [ but you should make sure that your largest message size is no larger than 1/4 of your block size]

**Comment by peter-lawrey** [comment]
A related issue is https://github.com/OpenHFT/Chronicle-Bytes/issues/66 as write(bytes) and read(bytes) can also fail in some cases.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.2 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.2), BOM-1.16.19 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.19)

**Comment by skaminen** [comment]
Looks like when we configure Hourly roll, the message size no larger than 1/4 of your block size is not honored. Below is a modification of above code that results in core dumped.

public class CQAppenderTest2 {
	
	static final int ITER = 100;
	static final int SIZE = 64 * 1024;
	static final int BLOCK_SIZE =  SIZE*4;

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		ChronicleQueue queue = ChronicleQueueBuilder.single("queueDir")
				.blockSize(BLOCK_SIZE)
				.rollCycle(RollCycles.HOURLY) // defining hourly roll causes this code to core dump.
				.wireType(WireType.FIELDLESS_BINARY)
				.build();
		final ExcerptAppender appender = queue.acquireAppender();
		byte[] array = new byte[SIZE];
		long startTime = System.currentTimeMillis();
		for (int i = 0; i < ITER; i++) {
			appender.writeBytes(b -> {
			    long address = b.address(b.writePosition());
			    Unsafe unsafe = UnsafeMemory.UNSAFE;
			    unsafe.copyMemory(array, Unsafe.ARRAY_BYTE_BASE_OFFSET, null, address, array.length);
			    b.writeSkip(array.length);
			});
		}
		long estimatedTime = System.currentTimeMillis() - startTime;
		System.out.println("time = " + estimatedTime);

	}

}

`18:55:49.814 [main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 0 chunk in queueDir/20180802-23.cq4 took 6.373 ms.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010e0dc549, pid=2880, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b25) (build 1.8.0_171-b25)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b25 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0xdc549]  acl_CopyRight+0x42
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#`

Stack trace 

Stack: [0x0000700009aca000,0x0000700009bca000],  sp=0x0000700009bc9618,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.dylib+0xdc549]  acl_CopyRight+0x42
j  sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V+0
j  com.CQAppenderTest2.lambda$0([BLnet/openhft/chronicle/bytes/BytesOut;)V+30
j  com.CQAppenderTest2$$Lambda$18.writeMarshallable(Lnet/openhft/chronicle/bytes/BytesOut;)V+5
j  net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeBytes(Lnet/openhft/chronicle/bytes/WriteBytesMarshallable;)V+19
j  com.CQAppenderTest2.main([Ljava/lang/String;)V+56
v  ~StubRoutines::call_stub

**Comment by anirudh-wa** [comment]
> 1/4 of your block size

Increase to how much ?  4 * size of data ?

**Comment by dpisklov** [comment]
@anirudh-wa yeah, at least.
