### ISSUE TITLE
Who cleans the cleaner?

### ISSUE THREAD

**Issue by huntc** [OpenHFT/Chronicle-Queue#489]
I've noticed that the thread associated with `WeakReferenceCleaner` stays around after shutdown hooks have been run. Should `WeakReferenceCleaner` not be cleaned up via a shutdown hook?

In addition, [queue-thread-local-cleaner-daemon](https://github.com/OpenHFT/Chronicle-Queue/blob/ff52e482c22eff0cb146b134ab244c946483c081/src/main/java/net/openhft/chronicle/queue/impl/single/StoreComponentReferenceHandler.java#L19) stays around. Shouldn't this also be cleaned up with a shutdown hook?

We are using CQ in an OSGi manner (not OSGi though) i.e. CQ is dynamically loaded and then we unload having called shutdown hooks.

**Comment by peter-lawrey** [comment]
Currently we don't have a shutdown hook as we expect all resources to be closed when the application exits.  It would be really useful to have a test which reproduces this issue otherwise we would be guessing whether any fix actually solved your problem.

**Comment by dpisklov** [comment]
This has been implemented

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.4 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.4), BOM-1.16.32 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.32)

**Comment by huntc** [comment]
Thanks!

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.4 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.4), BOM-1.16.39 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.39)
