### ISSUE TITLE
Fixed out of order messages

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#497]

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.4 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.4), BOM-1.16.32 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.32)

**Comment by JerryShea** [comment]
Believe that this was fixed by fixing the EOFException referred to in https://github.com/OpenHFT/Chronicle-Queue/issues/495

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.4 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.4), BOM-1.16.39 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.39)
