### ISSUE TITLE
Chronicle-Queue-Sample

### ISSUE THREAD

**Issue by yujg1992** [OpenHFT/Chronicle-Queue#500]
I use the programs "InputMain" and "OutputMain" in the Chronicle-Queue-Sample to test the write and read speed. But the result is much slower than 1GB/s. I read about 4 million string messages, cost about 4s. i7 cpu and SSD are used in the test.

**Comment by RobAustin** [comment]
store the chronicle queue to tmpFS and use StringBuilder ( hence reusing the same objects, to reduce GC  ) rather than Strings which are imutable.

**Comment by yujg1992** [comment]
I tried your suggestion, but the performance showed little improvement.

**Comment by RobAustin** [comment]
Are you using the latest version of chronicle queue in the sample ? if not, could you re-run it with the latest version.
