### ISSUE TITLE
Introduce writeLock to make the whole writingDocument operation atomic (including rolls)

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#504]

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.0), BOM-1.16.74 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.74)
