### ISSUE TITLE
Fixed flaky test SingleChronicleQueueTest#testAppendedBeforeToEnd

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#507]
see http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=268010&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleQueue4_Snapshot

**Comment by dpisklov** [comment]
seems fixed

**Comment by RobAustin** [comment]
thanks - fingers crossed

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.6 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.6), BOM-1.16.95 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.95)

**Comment by JerryShea** [comment]
just failed :( testAppendedBeforeToEnd
