### ISSUE TITLE
Merge chronicle queue builders

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#511]
Make the enterprise builder just extend the single queue builder.
This builder can build either kind of queue.

The builder should detect you are using an enterprise feature and error if it's not available.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.13 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.13), BOM-1.16.170 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.170)
