### ISSUE TITLE
Remove recovery and timeouts on first header after metadata is unified

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#512]
After #423 implemented, all queue operations will be guarded by either file locks or queue locks so there's no chance for concurrent access and no need for recovery/timeouts etc.

Also no need to call refreshIndex on DirectoryListing

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.10](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.10), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.10](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.10), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.10](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.10), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
