### ISSUE TITLE
Crash on ARM64 due to unaligned access

### ISSUE THREAD

**Issue by efge** [OpenHFT/Chronicle-Queue#528]
On an ARM64 machine (Ubuntu 16.04.2 LTS (GNU/Linux 4.10.0-38-generic aarch64)) we have this JVM crash due to unaligned access (BUS_ADRALN).

Any chance of doing correctly-aligned access for this architecture?

Using the latest version of the libraries (chronicle-bytes-1.16.23.jar, chronicle-wire-1.16.16.jar, chronicle-core-1.16.21.jar, chronicle-queue-5.16.11.jar).

Thanks,
Florent

> siginfo: si_signo: 7 (SIGBUS), si_code: 1 (BUS_ADRALN), si_addr: 0x0000fffe9cce3097
>
> Stack: [0x0000ffffa1788000,0x0000ffffa1988000],  sp=0x0000ffffa1982d30,  free space=2027k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
> V  [libjvm.so+0x95ed04]
> j  sun.misc.Unsafe.putOrderedInt(Ljava/lang/Object;JI)V+0
> j  net.openhft.chronicle.core.UnsafeMemory.writeOrderedInt(JI)V+6
> j  net.openhft.chronicle.bytes.MappedBytesStore.writeOrderedInt(JI)Lnet/openhft/chronicle/bytes/NativeBytesStore;+16
> j  net.openhft.chronicle.bytes.MappedBytesStore.writeOrderedInt(JI)Lnet/openhft/chronicle/bytes/RandomDataOutput;+3
> j  net.openhft.chronicle.bytes.MappedBytes.writeOrderedInt(JI)Lnet/openhft/chronicle/bytes/Bytes;+72
> j  net.openhft.chronicle.bytes.MappedBytes.writeOrderedInt(JI)Lnet/openhft/chronicle/bytes/RandomDataOutput;+3
> j  net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(Lnet/openhft/chronicle/wire/WriteMarshallable;)Lnet/openhft/chronicle/wire/WireOut;+111
> j  net.openhft.chronicle.wire.ValueOut.typedMarshallable(Lnet/openhft/chronicle/wire/WriteMarshallable;)Lnet/openhft/chronicle/wire/WireOut;+30
> j  net.openhft.chronicle.queue.impl.single.SCQMeta.writeMarshallable(Lnet/openhft/chronicle/wire/WireOut;)V+13
> j  net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(Lnet/openhft/chronicle/wire/WriteMarshallable;)Lnet/openhft/chronicle/wire/WireOut;+43
> j  net.openhft.chronicle.wire.ValueOut.typedMarshallable(Lnet/openhft/chronicle/wire/WriteMarshallable;)Lnet/openhft/chronicle/wire/WireOut;+30
> j  net.openhft.chronicle.queue.impl.table.SingleTableStore.writeMarshallable(Lnet/openhft/chronicle/wire/WireOut;)V+59
> j  net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(Lnet/openhft/chronicle/wire/WriteMarshallable;)Lnet/openhft/chronicle/wire/WireOut;+43
> j  net.openhft.chronicle.wire.ValueOut.typedMarshallable(Lnet/openhft/chronicle/wire/WriteMarshallable;)Lnet/openhft/chronicle/wire/WireOut;+30
> j  net.openhft.chronicle.wire.ValueOut.object(Ljava/lang/Object;)Lnet/openhft/chronicle/wire/WireOut;+1259
> j  net.openhft.chronicle.queue.impl.table.SingleTableBuilder.writeTableStore(Lnet/openhft/chronicle/bytes/MappedBytes;Lnet/openhft/chronicle/wire/Wire;Lnet/openhft/chronicle/queue/impl/single/StoreRecovery;)Lnet/openhft/chronicle/queue/impl/TableStore;+29
> j  net.openhft.chronicle.queue.impl.table.SingleTableBuilder.lambda$build$0(Lnet/openhft/chronicle/wire/Wire;Lnet/openhft/chronicle/bytes/MappedBytes;Lnet/openhft/chronicle/queue/impl/single/StoreRecovery;Ljava/lang/Object;)Lnet/openhft/chronicle/queue/impl/TableStore;+20
> j  net.openhft.chronicle.queue.impl.table.SingleTableBuilder$$Lambda$120.apply(Ljava/lang/Object;)Ljava/lang/Object;+17
> j  net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(Ljava/io/File;Ljava/util/function/Function;Ljava/util/function/Supplier;)Ljava/lang/Object;+60
> j  net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build()Lnet/openhft/chronicle/queue/impl/TableStore;+153
> j  net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata()V+75
> j  net.openhft.chronicle.queue.impl.AbstractChronicleQueueBuilder.preBuild()V+1
> j  net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build()Lnet/openhft/chronicle/queue/impl/single/SingleChronicleQueue;+33

**Comment by dpisklov** [comment]
@efge I just found that Nuxeo us using Chronicle, and we're glad to grow our users base. Unrelated to this issue, I see that you refer directly to particular versions of libraries. We usually discourage that, instead we recommend users to point to particular version of chronicle-bom, and use maven's `import` scope for it in dependencyManagement section. That way you can upgrade all dependencies in one shot by upgrading the bom, and also it will have more chance to work without any issues. If you just take random (even latest) versions of dependencies, you have an opportunity to pull some incompatible libraries, or miss some dependencies.

Regarding this particular issue, we don't have any customers using ARM (that is, we don't have anyone to pay for this) so we will attend to it only if we have some spare cycles. However if you are interested it support from Chronicle, please contact sales@chronicle.software I'm sure we will find a way to work together to our mutual benefit.

**Comment by efge** [comment]
@dpisklov Thanks, we'll consider using the bom import technique for dependency management to avoid trouble.

We're in the same situation, we don't have any customers using ARM yet so this is more of an exploratory nature than anything else. We would have liked to do some initial testing on ARM though but this will have to wait a bit.

**Comment by dpisklov** [comment]
This issue is now superseded by OpenHFT/OpenHFT#23

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.15 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.15), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
