### ISSUE TITLE
Move timezone and epoch-related metadata to metastore

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#529]
Blocked upon #511 this is a part of #423

**Comment by RobAustin** [comment]
@dpisklov is this still blocked

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.44 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.44)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.46 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.46)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
