### ISSUE TITLE
fixed simple reading/writing text to a chronicle queue

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#530]
added failing test see:

net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest#testTextReadWrite

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.14 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.14), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
