### ISSUE TITLE
Make checkInterrupts a builder option.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#531]
This can be surprisingly expensive.
The default is true as this is safer.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.14 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.14), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
