### ISSUE TITLE
Port Chronicle-Queue to C++

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#532]

**Comment by shuckc** [comment]
If of interest, I ported it to C - https://github.com/TeaEngineering/libchronicle

**Comment by dpisklov** [comment]
@shuckc FYI your implementation doesn't seem to be compatible with version 5 of Chronicle Queue as it does not implement the write lock (there're a few changes in protocol/file format in version 5).
Also, your project lacks license so it's by default non-free. If you are looking to share it for people to be able to use it, I suggest you choose a license for it (e.g. Chronicle uses Apache 2.0 license for all the open source software we develop)

**Comment by shuckc** [comment]
I have granted an Apache 2.0 license for libchronicle and confirmed this in the repository.

So far I have used (or plan to use) the appender busy-lock for all operations, ie. you take the writer lock in the previous queuefile, then decide to roll and write the new file whilst holding the writing lock, then release the lock with the EOF marker.

Do you have a link to the relevant commits for the scheme you are using?

**Comment by dpisklov** [comment]
We no longer use busy lock. We now use write lock which lives in separate
file (metadata.cq4), and this lock guards all write operations including
queue rolls.
There's a number of commits by me with changes to the queue format, write
lock changes are related to issue #504 end some other changes for issue
#423, we have a look.

**Comment by shuckc** [comment]
Thanks, I'd read some of those tickets before. The move to an additional write lock is a bit of a cop out, when the existing busy-lock during file-rolling ops scheme _should_ cover all cases, and to change it without pointing out the exact theoretical weakness you are trying to fix risks adding complexity for the sake of it.

In my view the appender triggering the roll should only have the ability (after clock suggests roll) to add one cycle and zero the seqnum, then retry the write. If we've slept for multiple days, this catches up progressively through the cycles by writing an eof and hitting the next file. This scheme wouldn't give you multiple open sessions like in the bug report for #491.

To handle the case where an appender starts up whilst another appender is rolling (#498), I made my appenders come up, sample the clock, and shift back by a day (actually 3) via. the [`patch_cycles`](https://github.com/TeaEngineering/libchronicle/blob/0b9835888da3077549b7862a261ea732265f1dad/native/shmipc.c#L67) variable which forces a [replay first here](https://github.com/TeaEngineering/libchronicle/blob/0b9835888da3077549b7862a261ea732265f1dad/native/shmipc.c#L900) to ensure writers have cleanly observed either an EOF in progress, or write the eof themselves.

I could support and trigger the lock support if I see the metadata file present, but there are a few more important things first to sort out in my implementation (indexes, support for layouts other than daily, empty queue init etc etc.)

**Comment by RobAustin** [comment]
I'm going to close this issue as duplicate as it has now been moved to https://github.com/ChronicleEnterprise/Chronicle-Queue-CPP

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.44 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.44)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.46 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.46)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
