### ISSUE TITLE
Improve handling of interrupts

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#533]
There are a number of issues

- checking interrupts show as a cause of jitter. The builder for queue now has an option to turn these off.
- calling a FileChannel method when interrupted closes the file by default, even though we share this resource.  https://stackoverflow.com/questions/52261086/is-there-a-way-to-prevent-closedbyinterruptexception
- change the code so it doesn't assume the fileChannel might not close without calling close()
- obtaining the size of a file will no longer get an IllegalStateException if the thread has been interrupted. It now returns the size of the file.
- when debugging MappedBytes, it is pain as the toString() or toHexString used by the debugger alter the underlying bytesStore. Now it detects this is happening and returns "Not available"

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.14 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.14), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
