### ISSUE TITLE
Documentation refers to 8-byte message headers

### ISSUE THREAD

**Issue by shuckc** [OpenHFT/Chronicle-Queue#536]
This paragraph is incorrect - the `.cq4` file format has 4 byte/32-bit headers:
https://github.com/OpenHFT/Chronicle-Queue#writing-to-a-queue

> Note | Within this 8-byte header we also reserve a few bits for a number of internal operations, such as locking, to make Chronicle Queue thread-safe across both processors and threads. The important thing to note is that because of this, you can’t strictly convert the 8 bytes to an integer to find the length of your data blob.

Perhaps the confusion is around the 64-bit index value that is conceptually associated with each queue entry. The 32-bit header is why the maximum payload size is limited to 30-bits.

**Comment by dpisklov** [comment]
Indeed, thanks

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.16.16 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.16.16), BOM-1.16.213 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.213)
