### ISSUE TITLE
Resources of appender not released

### ISSUE THREAD

**Issue by garikjan** [OpenHFT/Chronicle-Queue#539]
Hello! I found a bug: not all resources allocated by appenders are released, as it was supposed. Appenders are stored as weak references in TLS. When 'queue-thread-local-cleaner-daemon' processing thread of StoreComponentReferenceHandler processes references queue, closerJob.run() method is called, and it is supposed that StoreAppender.releaseResources() will be called to release resources, previously allocated by appender:
`            // Object is no longer reachable, check that it has not already been released
            if (storeReference != null && storeReference.refCount() > 0) {
                	queue.release(storeReference);
`
Queue tries to remove the store from **its own** WireStorePool instance.
But when an appender is created, a new dedicated WireStorePool instance is passed to its constructor:
`    protected ExcerptAppender newAppender() {
        queueLock.waitForLock();
        final WireStorePool newPool = WireStorePool.withSupplier(storeSupplier, storeFileListener);
        return new StoreAppender(this, newPool, checkInterrupts);
    }
`
So, when code above is executed, we only get warning:
_Store was not registered:_ 

I attached patched SingleChronicleQueueExcerpts.java (based on 5.16.16 version), that fixes the bug. Due to this bug, we weren't able to safely remove files, as soon as, there were still SingleChronicleQueueStore objects holding references to files: number of StoreListener.onAcquired() and StoreListener.onReleased() calls did not match.

There could be more elegant solution if SingleChronicleQueue.queue was not private - we could leave only this one constructor for ClosableResources class:
`        ClosableResources(final WireStorePool pool) {
            this.pool = pool;
        }
`
 
[SingleChronicleQueueExcerpts.java.zip](https://github.com/OpenHFT/Chronicle-Queue/files/2486327/SingleChronicleQueueExcerpts.java.zip)

**Comment by dpisklov** [comment]
@garikjan thanks, fixed

**Comment by garikjan** [comment]
Ok, great, thank you, @dpisklov!

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.0), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)
