### ISSUE TITLE
Create read/write performance test for queue 3.x and 5.x

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#540]
-Need new latency test of a 4096 byte put into Queue.  Results distributed as a histogram of P50, P95 and P99

-Need new latency test of a 4096 byte read from Queue.  Results distributed as a histogram of P50, P95 and P99

**Comment by peter-lawrey** [comment]
I have added the DTO.

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.44 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.44)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.46 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.46)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.1 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.1), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
