### ISSUE TITLE
Do not enable out of process pretoucher by default

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#542]
And add comments.

@dpisklov please review!

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.0), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)
