### ISSUE TITLE
Chronicle Queue 5.17.0 has transitive dependency issues

### ISSUE THREAD

**Issue by gity** [OpenHFT/Chronicle-Queue#546]
Queue 5.17.0 depends on threads 1.16.4 which depends on core 1.16.26 while queue depends on core 2.17.0

**Comment by RobAustin** [comment]
If you use the dependency management bom this should not be an issue, unless the API’s are not compatible.

**Comment by dpisklov** [comment]
@gity you might wanna read a bit about Maven's dependency resolution, in particular, [transitive dependencies](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html). The quote below means, in your example, that it doesn't matter what threads depend upon - as long as you don't explicitly declare dependency on threads or core (and you shouldn't really), the dependency from the queue will win.

```
* Dependency mediation - this determines what version of an artifact will be chosen when multiple versions are encountered as dependencies. Maven picks the "nearest definition". That is, it uses the version of the closest dependency to your project in the tree of dependencies. You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.
* "nearest definition" means that the version used will be the closest one to your project in the tree of dependencies. For example, if dependencies for A, B, and C are defined as A -> B -> C -> D 2.0 and A -> E -> D 1.0, then D 1.0 will be used when building A because the path from A to D through E is shorter. You could explicitly add a dependency to D 2.0 in A to force the use of D 2.0.
```
But as Rob says, to avoid any doubt we recommend people to use chronicle-bom project as an import scope, which thus will override any dependency version to the ones defined in the particular bom.
