### ISSUE TITLE
Allow user to configure the maximum disk threshold percentage( crossing that value, an exception should be thrown )

### ISSUE THREAD

**Issue by anirudh-striim** [OpenHFT/Chronicle-Queue#548]
Let the user configure the value for threshold on disk space. Once this threshold is crossed, an exception should be thrown.

For ex : A user can configure this value to be 75% of the total disk space. Once the disk crosses 75% usage, Chronicles should throw an exception to the user.

**Comment by RobAustin** [comment]
relates to https://github.com/OpenHFT/Chronicle-Queue/issues/547
