### ISSUE TITLE
Queue files could not be read after transfering them into os with different language

### ISSUE THREAD

**Issue by herkut** [OpenHFT/Chronicle-Queue#554]
Queue files could not successfully be read after transferring them into an operating system with different language pack (the issue was observed on windows). The behavior was not checked on linux distributions. Can you please help me to understand what was the reason for the issue?

You might want to check stack trace:
27/Nov/2018 09:40:21   ERROR  17236    [main] c.e.s.e.e.PersistentEventQueue(L:47) - Could not initialize PersistentEventQueue. Persistent queue files may be corrupted. 
java.lang.AssertionError: java.io.IOException: java.lang.NullPointerException
	at net.openhft.chronicle.VanillaChronicle$AbstractVanillaExcerpt.index(VanillaChronicle.java:485)
	at net.openhft.chronicle.VanillaChronicle$AbstractVanillaExcerpt.nextIndex(VanillaChronicle.java:499)
	at com.mypackage.PersistentEventQueue.countUnprocessedEvents(PersistentEventQueue.java:371)

**Comment by dpisklov** [comment]
3.X versions are unsupported except for paying clients. We suggest you upgrade to latest Chronicle Queue.
