### ISSUE TITLE
ChronicleReader creates queue too many times

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#556]
Which causes lots of "Read-only mode is not supported on Windows® platforms..." messages on Windows

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.2), [BOM-2.17.92](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.92)
