### ISSUE TITLE
After chronicle queue is closed , cannot delete chronicle files

### ISSUE THREAD

**Issue by amitavab** [OpenHFT/Chronicle-Queue#560]
After we close chronicle queue , we cannot delete chronicle files . This was possible in v3 but not in v4 . Our unit tests are failing

**Comment by JerryShea** [comment]
Which OS?

**Comment by amitavab** [comment]
Windows and linux

**Comment by dpisklov** [comment]
Can yyou provide a failing unit test?

**Comment by MartyIX** [comment]
This is my attempt to create a failing test:

```
package net.openhft.chronicle.queue;

import net.openhft.chronicle.queue.impl.single.SingleChronicleQueue;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class ChronicleQueueDataRemovalTest {

    @Test
    public void test() throws IOException {
        Path path = Files.createTempDirectory(ChronicleQueueDataRemovalTest.class.getSimpleName());

        //noinspection EmptyTryBlock,unused
        try (SingleChronicleQueue cq = SingleChronicleQueueBuilder.binary(path).build()) {
        }

        File dir = path.toFile();
        DirectoryUtils.deleteDir(dir);

        if (dir.exists()) {
            Assert.fail("Folder was not deleted: " + dir.getAbsolutePath());
        }
    }

}
```

It really fails on my Windows machine. Test output contains `java.nio.file.AccessDeniedException`.

**Comment by dpisklov** [comment]
Windows is known to be crap at concurrent access to files, that's why we
don't recommend using Windows for production (or really, we just don't
recommend using Windows, full stop)

**Comment by MartyIX** [comment]
I see. Is the test of some value for non-Windows platforms then?

**Comment by amitavab** [comment]
We do development on Windows machines

**Comment by dpisklov** [comment]
@MartyIX this test works (passes) on my Linux machine, so I guess the problem only exists for Windows.
@amitavab if you can provide a failing test which will fail on linux we will have a look. Support for Windows is on a best-effort basis, and as this is not the problem likely to affect our clients, we don't consider this as something worth investing time into.
That said, we are happy to approve PR if you (or anyone from opensource community) want to fix it and submit for merge.
For now, I'm closing this as won't fix

**Comment by mcs6502** [comment]
@amitavab @MartyIX There is the StoreComponentReferenceHandler enum in Chronicle Queue v4 and later, which asynchronously releases cached references to some Chronicle objects. Its task runs at one-second intervals, so there might be a delay between your closing of Chronicle resources and its files actually being closed/unmapped. Therefore, on Windows you might need to employ some sort of strategy when you delete Chronicle queue files.
For example, you might close all Chronicle resources on your end, then wait for two periods of the handler task, then trigger a GC and wait a bit more, then try deleting your queue files.
If that doesn't help then you might want to investigate this problem by creating a heap dump and tracing GC paths to mapped queue files (queue file descriptors) that still remain in memory after the above steps.
