### ISSUE TITLE
Created example to use a custom proxy to eliminate new args[] on every write to a queue via methodWriter 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#563]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.5](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.5), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.5](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.5), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.5](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.5), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
