### ISSUE TITLE
When writing EOF marker in the queue file, it's possible to truncate file in the background

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#580]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.149](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.149)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.9), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
