### ISSUE TITLE
jdk11 warning : illegal reflective access

### ISSUE THREAD

**Issue by whitelilis** [OpenHFT/Chronicle-Queue#600]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.openhft.compiler.MyJavaFileManager (file:/Users/xxx/.m2/repository/net/openhft/compiler/2.3.4/compiler-2.3.4.jar) to method com.sun.tools.javac.file.JavacFileManager.listLocationsForModules(javax.tools.JavaFileManager$Location)
WARNING: Please consider reporting this to the maintainers of net.openhft.compiler.MyJavaFileManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by dpisklov** [comment]
I fixed this although it doesn't belong to this project. In the future please raise issues in appropriate projects (Java-Runtime-Compiler, in this particular case)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.11), [BOM-2.17.206](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.206)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.11), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.11), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
