### ISSUE TITLE
Allow reading of chronicle queue even if metadata file is read only

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#601]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.11), [BOM-2.17.206](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.206)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.11), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.11), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
