### ISSUE TITLE
Chronicle-Queue with stream processing system

### ISSUE THREAD

**Issue by JoshBroadway** [OpenHFT/Chronicle-Queue#602]
Hi, I'm investigating using Chronicle-Queue as the mechanism to transport data from my Java application into an Apache Flink instance. Chronicle-Queue satisfies is the perfect tool for my usecase (high volumn, low latency requirement) but when I try to use a SingleChronicleQueue as a SourceFunction in Flink I get a NotSerializableException from Flink.

Is there a way to use Chronicle-Queue with Flink? If not, are there any plans to make Chronicle-Queue types Serializable so that they can be run in Flink?

Finally, are there any other stream processing systems that Chronicle-Queues does work with? Options here are: Apache Spark, Apache Storm, Kafka Streams?

Thanks,
Josh.

**Comment by JerryShea** [comment]
Hi Josh, what does Flink need to be Serializable? The SingleChronicleQueue object itself?

**Comment by JoshBroadway** [comment]
Hi Jerry, 

I'm still learning my way around Flink and Chronicle-Queue myself so what I'm asking for might not make sense. :) 

I've tried to write a customised Flink SourceFunction that uses the SingleChronicleQueue to read data into Flink but I've since found out that all objects used in Flink need to be serializable. For me right now that means SingleChronicleQueue and ExcerptTailer (and all of their contained objects). 

Some background about my project in case it helps you understand my use case...

I'm working on an application that generates large amounts of data to perform calculations on  and needs to do these calculations very quickly (think 10's of millions per second). I'm hoping to get better performance by moving the complex calculations out to a Flink cluster for parallel processing. 

I initially experimented using Kafka to transport data into Flink but I found that the cost of writing the data to the network socket was way too expensive (writing data took about 4 seconds), so I experimented with Chronicle-Queue and found that much better (about 300milliseconds). 

Queue is exactly what I need but unfortunately I can't read the data into Flink because of it's Serializable restriction. Note, I'm already using Chronicle Values and Chronicle Map so extending to use Chronicle Queue made sense.

Thanks for your help.

**Comment by RobAustin** [comment]
@JoshBroadway Have you tried making your DTO's both Serializable for Flink and Marshallable for ChronicleQueue. In other words, your DTO should be able to implement both Serializable, Marshallable

**Comment by JoshBroadway** [comment]
@RobAustin yeah, that's a good idea but that won't fix the problem that I'm currently experiencing. The exception being thrown is below.

> Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: The implementation of the SourceFunction is not serializable. The object probably contains or references non serializable fields.
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:99)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:1559)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1471)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1415)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1397)
	at au.com.consunet.prototype.ark.ArkChronicleDetectionProcessor.main(ArkChronicleDetectionProcessor.java:23)
Caused by: java.io.NotSerializableException: net.openhft.chronicle.queue.impl.single.SingleChronicleQueue
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:576)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:81)
	... 5 more

**Comment by JoshBroadway** [comment]
Here is a copy of the code that I'm using to generate the error. I'm aware that my implementation of the run() method might not work very well for what I want but at the moment I can't even construct the ChronicleQueueSource.

    package mynamespace.sources;

    import mynamespace.chronicle.MyClass;

    import net.openhft.chronicle.queue.ExcerptTailer;
    import net.openhft.chronicle.queue.impl.single.SingleChronicleQueue;
    import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
    import net.openhft.chronicle.values.Values;
    import org.apache.flink.api.common.functions.StoppableFunction;
    import org.apache.flink.streaming.api.functions.source.SourceFunction;

    import java.io.File;

    public class ChronicleQueueSource implements SourceFunction<MyClass>, StoppableFunction {

        private File queuePath;
        private boolean isRunning = true;
        SingleChronicleQueue queue;
        ExcerptTailer tailer;

        public ChronicleQueueSource(File queuePath) {
            super();

            this.queuePath = queuePath;
            this.queue = SingleChronicleQueueBuilder.binary(this.queuePath).build();
            this.tailer = this.queue.createTailer();
        }

        @Override
        public void run(SourceContext ctx) throws Exception {

            while(isRunning) {
                MyClass packet = Values.newHeapInstance(MyClass.class);
                this.tailer.readBytes(packet);

                ctx.collect(packet);
            }
        }

        @Override
        public void cancel() {
            isRunning = false;
        }

        public void close() throws Exception {
            this.queue.close();
        }

        public void stop() {
            this.isRunning = false;
        }
    }

**Comment by JerryShea** [comment]
@JoshBroadway without knowing much about Flink, I would make queue and tailer fields transient in your object and create them lazily if need be in your run method. This should work fine for the queue object as the `SingleChronicleQueue` stores all its state in the persisted memory-mapped queue files on disk. The tailer does store state - its position in the queue, and so for the tailer, you may need another mechanism to remember where the tailer has got up to. You could use persisted tailer position, which is a new feature.

**Comment by JoshBroadway** [comment]
@JerryShea thanks for the suggestion. I should have thought of that myself but that got it working!

Flink is now automatically scaling the Tailers and they're all reading from the queue. However, as you noted, they're all reading the same messages, I would like to implement the queue as a read-once queue, rather than have each Tailer read every message. I note in your documentation that you recommend creating a filter to avoid different Tailers reading the same messages. 

Is there any example code for how to do this? I assume that the queue doesn't store a state that allows me to call .getNext() or something similar?

**Comment by RobAustin** [comment]
@JoshBroadway - We don't have any example code but it's easy to implement let's assume that you have 5 tailers, and you notionally consider each trailer to be given its own unique number 1-to 5. In your DTO you add an extra field, let's call it tailer number  ( when you create the message you assign which trailer you wish to process this message ). After each tailer deserializes each message you read this number, if this number corresponds to that trailer then you process the message in FLINK, otherwise, you ignore this message and read the next message. There are a number of other ways you could do this, for example, you could also implement something similar based on the tailer.index() and you would not have to add an additional field to the DTO, for example, if you had two tailers, then messages with an odd index number could be processed by one tailer and the evens by the other.

**Comment by RobAustin** [comment]
If you have any further questions please ask these on stack-overflow, as we wish to leave git-issues for issue reporting. Thanks.
