### ISSUE TITLE
File Descriptor Leak on directory-listing.cq4t and lots of File Descriptor on deleted cq4 file

### ISSUE THREAD

**Issue by mizeng** [OpenHFT/Chronicle-Queue#603]
## Our Env
JDK: 1.8.0_111
ChronicleQueue: 4.16.0
Max Open Files Limit of Process: 65535

## Use Behavior of Chronicle Queue
In short, we create a SingleChronicleQueue with 1m RollCycle. We rely on RollCycle, so we don't close the queue.
1. We created a queue by `SingleChronicleQueue queue = SingleChronicleQueueBuilder.binary(chroniclePath).rollCycle(RollCycles.MINUTELY)
                .storeFileListener(listener).build();`
2. We use below to write to queue
```
public ExcerptAppender getAppender() {
        if (appender == null)
            appender = queue.acquireAppender();
        return appender;
}

getAppender().writeBytes(message.getBufferBytes());
```

## Issue Details
Below 2 issues caused too many open files issue
1. Lots of FD used by deleted cq4 file
```
[root@box ~]# ls -la /proc/18003/fd/ | grep deleted|wc -l
31305
[root@box ~]# ls -la /proc/18003/fd/ | grep deleted|head -n 10
lrwx------ 1 xxx 64 Apr 17 22:47 10001 -> /home/user/queue0/eventExecutorGroup-2-39/20190417-0934.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 23:01 10002 -> /home/user/queue0/eventExecutorGroup-2-12/20190417-0933.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 23:01 10003 -> /home/user/queue0/eventExecutorGroup-2-33/20190417-0933.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 22:47 10005 -> /home/user/queue0/eventExecutorGroup-2-61/20190417-0935.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 22:47 10006 -> /home/user/queue0/eventExecutorGroup-2-40/20190417-0950.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 22:47 10007 -> /home/user/queue0/eventExecutorGroup-2-21/20190417-0950.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 23:01 10010 -> /home/user/queue0/eventExecutorGroup-2-50/20190417-0933.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 22:47 10011 -> /home/user/queue0/eventExecutorGroup-2-24/20190417-0934.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 23:01 10013 -> /home/user/queue0/eventExecutorGroup-2-29/20190417-0933.cq4 (deleted)
lrwx------ 1 xxx 64 Apr 17 22:47 10014 -> /home/user/queue0/eventExecutorGroup-2-50/20190417-0934.cq4 (deleted)
``` 

2. Lots of FD used by directory-listing.cq4t file.
```
[root@box ~]# ls -la /proc/18003/fd/ |grep 'directory-listing.cq4t' |wc -l
31746
[root@box ~]# ls -la /proc/18003/fd/ |grep 'directory-listing.cq4t' |head -n 10
lrwx------ 1 user 64 Apr 17 22:47 10000 -> /home/user/queue0/eventExecutorGroup-2-49/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10004 -> /home/user/queue0/eventExecutorGroup-2-1/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10008 -> /home/user/queue0/eventExecutorGroup-2-56/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10009 -> /home/user/queue0/eventExecutorGroup-2-45/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 23:36 1001 -> /home/user/queue0/eventExecutorGroup-2-61/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10012 -> /home/user/queue0/eventExecutorGroup-2-50/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10015 -> /home/user/queue0/eventExecutorGroup-2-58/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10016 -> /home/user/queue0/eventExecutorGroup-2-9/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10019 -> /home/user/queue0/eventExecutorGroup-2-58/directory-listing.cq4t
lrwx------ 1 user 64 Apr 17 22:47 10021 -> /home/user/queue0/eventExecutorGroup-2-36/directory-listing.cq4t
```
update: Upgrade to CQ 5.17.12, now FD leak on `metadata.cq4t`.

## Reference
I've find some one met similar issue on `directory-listing.cq4t` FD leak: https://jira.nuxeo.com/browse/NXP-25231. But not sure why upgrade to "5.16.4" could fix this issue.

**Comment by dpisklov** [comment]
First of all, you should not be caching appender. The acquireAppender will reuse thread local appender for you, and your getAppender method is broken if you ever use it from multiple threads.

On (1) - are you deleting queue files? We do not recommend deleting files that are still in use. But that aside - all files are again different. We release the file handles for cq4 files lazily, not immediately after roll, so you should expect at least 2 last files' handles to be present.
Now, in issue (2) all the files are different - you seem to have a lot of queues, so this is not an issue.

So I don't really see any problem here. Do you have any descriptors really leaking (i.e. that reference the same file)?

**Comment by mizeng** [comment]
Thanks a lot. I've found the issue.
