### ISSUE TITLE
Is this Java 11 compatible ?

### ISSUE THREAD

**Issue by kant111** [OpenHFT/Chronicle-Queue#604]
Is this Java 11 compatible?

**Comment by RobAustin** [comment]
Yes, It will work in a java 11 project

**Comment by dpisklov** [comment]
Please (1) use search on the issues before posting a new one - it has been mentioned a dozen times before and (2) *do not* use github issues for asking questions - it is for reporting issues. Stackoverflow is for questions.

**Comment by JerryShea** [comment]
To build and run Chronicle products on Java 11/17 please see also https://chronicle.software/chronicle-support-java-17/ for instructions to run on Java 11/17
