### ISSUE TITLE
Is there a way to disable the disk-space check that happens by default within chronicle system

### ISSUE THREAD

**Issue by anirudh-striim** [OpenHFT/Chronicle-Queue#612]
I am using chronicles-bom with version 2.17.48 and I see that the disk-space check happens by default in the chronicles system. I am running into an issue where fileStoreCacheMap object inside DiskSpaceMonitor.java class is not cleared in memory for some reason and its bloating up my memory. 

Is there a way to disable this disk check as a quick fix ?

**Comment by anirudh-striim** [comment]
The issue here looks like the DiskSpaceMonitor thread never gets cleaned up and the fileStoreCacheMap grows too big in size overtime and its crashing the system.

**Comment by dpisklov** [comment]
@anirudh-striim I'm afraid there's no way to disable it currently

**Comment by anirudh-striim** [comment]
@dpisklov - I am planning to send a PR with the memory optimization checks for DiskSpaceMonitor. Do you have any documentation on how to build and test it locally ?

**Comment by dpisklov** [comment]
There's nothing specific really - mvn test will do.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.29), [BOM-2.17.472](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.472)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.29), [BOM-2.17.496](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.496)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.29), [BOM-2.17.537](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.537)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.29), [BOM-2.17.541](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.541)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.29), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.29](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.29), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)
