### ISSUE TITLE
unused variable `basePath` in Readme # Getting Started

### ISSUE THREAD

**Issue by leolee192** [OpenHFT/Chronicle-Queue#615]
There was the following description in the current "Getting Started" example:

```
String basePath = System.getProperty("java.io.tmpdir") + "/getting-started"
ChronicleQueue queue = SingleChronicleQueueBuilder.single("queue-dir").build();
```

seemed `"queue-dir"` should be `basePath`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.19](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.19), [BOM-2.17.364](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.364)
