### ISSUE TITLE
Changed timeout on SingleTableStore to a timeout that takes account of GC pauses

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#616]
A client reported an issue where the table store was becoming locked on a long 70 second GC pause.

the notes from the client are as follows- 

_After investigation, it doesn’t seem like there is another process running using that file. Our logs indicate that a gc occurred right before the exception. Looking at the implementation of doWithExclusiveLock, if the gc happened between line 136 and 138 (on the master branch of SingleTableStore.java https://github.com/OpenHFT/Chronicle-Queue/blob/master/src/main/java/net/openhft/chronicle/queue/impl/table/SingleTableStore.java) and lasted longer than the timeout period this could lead to an IllegalStateException being thrown because the while loop is never entered._ 

Hence, We changed the code to use net.openhft.chronicle.core.util.Time#tickTime instead as this takes account of GC pauses in its timings.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.20](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.20), [BOM-2.17.364](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.364)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.19](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.19), [BOM-2.17.364](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.364)
