### ISSUE TITLE
Added support for striding when scanning backwards.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#617]
Reading backwards is not as efficient as reading forwards and if you don't need to read every entry, it is faster to jump to the previous multiple of the indexSpacing()

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.21](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.21), [BOM-2.17.369](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.369)
