### ISSUE TITLE
Force readOnly(true) if metadata.cq4t is read only

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#618]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.22](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.22), [BOM-2.17.381](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.381)
