### ISSUE TITLE
Log output filling up log files when closing a lot of queues

### ISSUE THREAD

**Issue by NavidMitchell** [OpenHFT/Chronicle-Queue#622]
We just upgraded to 5.17.24 and now we are getting a ton of log output. We open and close a lot of queues. 
So we are seeing a ton of

net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender
Closing store append for /media/genesys-kernel-data2/stores/streams/EmberCountsJson-data 

When looking at the code this line seems to be the culprit 

SingleChronicleQueueExcerpts.java

Line 154 
            // todo remove
            Jvm.warn().on(getClass(), "Closing store append for " + queue.file().getAbsolutePath());

**Comment by RobAustin** [comment]
I agree - I think this should be a debug and not a warn.

**Comment by NavidMitchell** [comment]
Thank you for the quick response. That would be much better. :)

**Comment by JerryShea** [comment]
That was bugging me as well

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.25](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.25), [BOM-2.17.404](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.404)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.25](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.25), [BOM-2.17.407](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.407)
