### ISSUE TITLE
Fixed Issue where existing rollCycle was not maintained upon restart

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#624]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.25](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.25), [BOM-2.17.404](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.404)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.25](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.25), [BOM-2.17.407](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.407)
