### ISSUE TITLE
Allow MethodWriters to the thread safe by default.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#625]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.26](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.26), [BOM-2.17.412](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.412)
