### ISSUE TITLE
Add a yaml tests for chained services with history, setting the MessageHistory

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#626]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.42](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.42), [BOM-2.20.67](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.67)
