### ISSUE TITLE
CQ gets stuck

### ISSUE THREAD

**Issue by javasoze** [OpenHFT/Chronicle-Queue#629]
Seeing tons of such warnings:

```
WARN  [2019-11-14 12:20:28,627] net.openhft.chronicle.queue.impl.single.TableStoreWriteLock: Couldn't acquire writelock after 15000ms for the lock file:/dashbase/index/queue/metadata.cq4t, overriding the lock. Lock was held by PID 1
```

Then followed by:

```
net.openhft.chronicle.queue.impl.single.TableStoreWriteLock: Forced unlock for the lock file:/dashbase/index/queue/metadata.cq4t! net.openhft.chronicle.core.StackTrace: null! 
at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.forceUnlock(AbstractTSQueueLock.java:56)! at 

net.openhft.chronicle.queue.impl.single.TableStoreWriteLock.lock(TableStoreWriteLock.java:57)! at
 net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:368)! 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:360)! 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeBytes(SingleChronicleQueueExcerpts.java:140)

```
After a while of unlocking, then this happens:

```
Exception thrown while writing to chronicle queue. Restarting the process! 
java.io.StreamCorruptedException: Data at 588202 overwritten? Expected: 0 was 843! at 
net.openhft.chronicle.wire.AbstractWire.updateHeaderAssertions(AbstractWire.java:551)! at 
net.openhft.chronicle.wire.AbstractWire.updateHeader(AbstractWire.java:537)! at 
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:770)! ... 62 common frames omitted! 

Causing: java.lang.IllegalStateException: java.io.StreamCorruptedException: Data at 588202 overwritten? Expected: 0 was 843! at 
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:795)! at 
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:746)! at 
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeBytes(SingleChronicleQueueExcerpts.java:150)

```

The only way to move forward is to delete the queue file, but that causes data-loss.

But even so, this is happening often enough that we are stuck.

Thank you in advance for any help!

**Comment by javasoze** [comment]
Not sure if that is related, posted our code on #628

**Comment by dpisklov** [comment]
@javasoze do you have long GC pauses by a chance? Longer than 15 seconds in particular? This can happen when one writer was waiting for another to complete writing for longer than 15 seconds. 
If you have longer GC pauses I suggest you adjust the timeout for the queue builder, e.g.

```
builder.timeoutMS(60_000);
```

or whatever value will be larger than max GC pause you may experience.

Other possibility if you write so much data on a slow machine (slow disk/slow (or low) memory) that it takes too long to write data.

Finally, this can happen if you have nested writes - i.e. you initiate writing to the queue while writing to the same queue. e.g.:

```
ChronicleQueue q;
ExcerptAppender appender = q.acquireAppender();
try (DocumentContext dc = appender.writingDocument()) {
    // write something
    appender.writeBytes(...); // this will try to call writingDocument on appender - but the context is already opened
}
```

**Comment by javasoze** [comment]
@dpisklov thank you for your help. We were able to add code to protect from the "too many writers" problem.

We think the queue got corrupted in the first place is from hard shutdown, details:

* Our process that writes to CQ runs inside a container on Kubernetes
* When there the process is unhealthy (in this case, too many writers contributed to system degradation), and Kubernetes forces a shutdown on the process
* When this happens, since CQ memory maps the underlying data, the queue can get corrupted.

Do you think that is a likely scenario? Any suggestions on how to protect CQ from getting corrupted from a hard kill?
Thanks!

**Comment by dpisklov** [comment]
@javasoze how is your container set up? We use --ipc=host and bind-mounted volume to store queue files, otherwise the issues you have are quite likely, and without --ipc=host data exchange between containers would be slow.

**Comment by RobAustin** [comment]
given @javasoze mentions that - "We think the queue got corrupted in the first place is from hard shutdown," I will close this issue as won't fix. Please let me know if you fee we should reopen it.
