### ISSUE TITLE
Dump a StackTrace when when SingleTableStore.doWith*Lock times out

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#633]
Only do this if `Jvm.isDebugEnabled(SingleTableStore.class)`.

Try to find cause of occasional ""Failed to acquire lock on the table store file" at customer.

Deduplicated `SingleTableStore.doWith*Lock` methods in order to ensure that changes for #616 were applied to both.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.30), [BOM-2.17.482](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.482)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.30), [BOM-2.17.496](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.496)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.30), [BOM-2.17.537](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.537)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.30), [BOM-2.17.541](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.541)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.30), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.30](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.30), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)
