### ISSUE TITLE
Document how rolled files can be deleted

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Queue#636]
Add documentation for how files can be deleted in a proper way without causing problems.

For example, there is  a roll sequence of files A, B and C. The appender is on C and there is a tailer at C. however, a lagging tailer is at A. B is not used but cannot be removed.

**Comment by minborg** [comment]
Read about it here: https://github.com/OpenHFT/Chronicle-Queue/blob/master/docs/managing_roll_files_directly.adoc

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.34](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.34), [BOM-2.17.537](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.537)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.34](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.34), [BOM-2.17.541](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.541)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.34](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.34), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.17.34](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.34), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)
