### ISSUE TITLE
Chronicle-queues misleading error message

### ISSUE THREAD

**Issue by dprymas** [OpenHFT/Chronicle-Queue#638]
Hello
We were using chronicle-queue in version 4.6.69, which is compatible with chronicle-wire 1.10.16. Some time ago we switched to chronicle-queue in version 5.17.7 which is compatible with 2.17.7 of chronicle-wire. 
As long as mixing version is not recommended we found rather misleading error message.

In first case we saved first data with CQ in version 4.6.69 and then with 5.17.7, everythings worked correctly after upgrade, as expected.

In second case we saved with 5.17.7 at the beggining and then downgrade CQ to 4.6.69 and then save data again - as expected it causes an issue - 

```
IllegalArgumentException - no enum constant net.openhft.chronicle.wire.WireType.1 
at net.openhft.chronicle.wire.Demarshallable.newInstance(Demarshallable.java:62)
at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.demarshallable(BinaryWire.java:3307)
at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.typedMarshallable0(BinaryWire.java:3075)
at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.typedMarshallable(BinaryWire.java:3040)
```

As long as that flow is correct we would like to better understand why we got error - we compared WireType enum and field names are same, types look also correct. 
Kind regards

**Comment by dpisklov** [comment]
https://github.com/OpenHFT/Chronicle-Queue/issues/638
