### ISSUE TITLE
Add a demo for BufferMode.Copy

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#642]
`Copy` used to write to a buffer as needed to improve concurrency. The appender would try to obtain a lock, but if it couldn't immediately it would write to a buffer instead, and copy this when the DocumentContext is closer. This is obviously not suitable if you assume the DocumentContext holds a lock on the queue.

Can this be added back in with a demo/concurrent benchmark?

**Comment by peter-lawrey** [comment]
The current behaviour should be retained as the default.

**Comment by RobAustin** [comment]
I suggest using Chronicle Queue with chronicle ring to achieve this, as this is the purpose of  Chronicle Ring, in other words, this functionality has been moved from Chronicle Queue into Chronicle ring, which is a licenced product.
