### ISSUE TITLE
How to update record in chronicle queue?

### ISSUE THREAD

**Issue by longtrb** [OpenHFT/Chronicle-Queue#643]
I want to update record at specific index and I found out in README this "You will reserve a portion of memory and then put/fetch/update records using the Chronicle interface".
How could I do that? 

Many Thanks,

**Comment by andrm** [comment]
The README is a bit misleading in this area in my opinion. You can't update them. This is a conscious choice by the creators of Chronicle Queue. (I think it used to be possible with CQ 3)

**Comment by RobAustin** [comment]
I agree it misleading, so i have removed it.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.0](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.0), [BOM-2.19.4](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.4)
