### ISSUE TITLE
How to enable debug level logging for chronicle-bom 

### ISSUE THREAD

**Issue by anirudh-striim** [OpenHFT/Chronicle-Queue#644]
I am trying to debug an issue and I don't know to enable debug level logging only for my chronicle-bom dependency. Can you help me with this.

**Comment by dpisklov** [comment]
We use SLF4J for our logging, please refer to their docs on how to configure:
http://www.slf4j.org/manual.html

**Comment by anirudh-striim** [comment]
Thanks.
