### ISSUE TITLE
fixed: EOF missing due to pretouch being called on otherwise empty .cq4 file

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#647]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.2), [BOM-2.19.13](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.13)
