### ISSUE TITLE
Compatibility issues on JDK 14

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Queue#652]
Hi

 `sun.nio.ch.FileChannelImpl.map0` implementation has changed on JDK 14, requiring an additional boolean param. 

This makes CQ unusable on that version of the JDK (works fine on JDK 13).

Tested with CQ version _5.19.2_

**Comment by dpisklov** [comment]
@sheinbergon Chronicle's JDK support policy is linked to LTS versions. We support Java 8 and Java 11. So far, Oracle hasn't announced any LTS versions past Java 11 so we do not intend to support newer versions until there is an LTS version.
That said, we are happy to accept PRs.

**Comment by sheinbergon** [comment]
@dpisklov Thank you for your response. 
Next LTS version would be JDK 17 ( a year and half from now). 
When that version arrives, you're going to meet that error I just mentioned. 

I'll see if it's complicated to fix it myself or not and let you know.

**Comment by sheinbergon** [comment]
@dpisklov  Opened this [PR](https://github.com/OpenHFT/Chronicle-Core/pull/98) to provide initial support for JDK 14, tested locally and seems to be fine.

**Comment by sheinbergon** [comment]
@dpisklov any response?

**Comment by dpisklov** [comment]
@sheinbergon sorry it was a bank holiday in UK.
I merged the PR.

**Comment by dpisklov** [comment]
@sheinbergon can we close this?

**Comment by sheinbergon** [comment]
@dpisklov  any chance to release a new version for the Chronicle-Core and this project pointing to the aforementioned with that fix merged?

10x

**Comment by dpisklov** [comment]
@sheinbergon 
Done.

Chronicle-BOM : 2.19.116

chronicle-core: 2.19.4
- Improve EventHandler termination performance [#101]
- Compatibility issues on JDK 14 [#100]

chronicle-queue: 5.19.11
- Fixed ARM compatibility [#656]
- Memory leak in DiskSpaceMoniotor inside SingleChronicleQueue.java [#630]
