### ISSUE TITLE
tailer.peekDocument should return false if there is no document

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#653]
The is an issue relating peekDocument(). tailer.peekDocument should return false if there is no document, it works fine if we first write some bytes to chronicle and then read and test peekdocument().
 
It fails when consumer thread started before producer thread and calls peekDocument() on tailer. It returns true.
 
Another scenario: writer thread writes to chronicle queue and goes down and reader thread reads and does peekdocument() it returns false but if we restart reader and do again tailer.peekDocument it returns true.
 
```
public  void testWhenNoDocument(){
    SingleChronicleQueueBuilder builder = SingleChronicleQueueBuilder.single( "chronicleTestPeekDocument" );;
    SingleChronicleQueue queue = builder.build();
    ExcerptTailer tailer = queue.createTailer();
    ExcerptAppender appender = queue.acquireAppender();

    boolean peekDocumentBeforeWrite  = tailer.peekDocument();   //  peekDocumentBeforeWrite   should be false.but returns true
    assertFalse( peekDocumentBeforeWrite );

    try(DocumentContext dc = appender.writingDocument()){
        dc.wire().writeText("testString");
    }

    boolean peekDocumentAfterWrite  = tailer.peekDocument();
    assertTrue( peekDocumentAfterWrite );

    String text=null;
    try(DocumentContext dc = tailer.readingDocument()){
         text = dc.wire().readText();
    }

    assertEquals( "testString",text );

     boolean peekDocumentAfterRead  = tailer.peekDocument();
    assertFalse( peekDocumentAfterRead );
}
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.8](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.8), [BOM-2.19.98](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.98)

**Comment by JerryShea** [comment]
peekDocument was designed to be best effort, and could return false negatives. Can it still return false negatives (e.g. if queue has just rolled)? If so, we should ensure that javadoc spells this out

**Comment by RobAustin** [comment]
Please don’t change the java doc. I’ll fix the implementation to support rolling.
