### ISSUE TITLE
Path Manipulation

### ISSUE THREAD

**Issue by mr-r0w07** [OpenHFT/Chronicle-Queue#655]
Attackers are able to control the file system path argument to File() at DumpQueueMain.java line 30, which allows them to access or modify otherwise protected files.

Since the value of path comes from args whose value can be supplied by user, it is unsafe to dump it directly.

**Comment by dpisklov** [comment]
This is an admin util, used by system administrators. We don't really care how attack-prone it is

**Comment by RobAustin** [comment]
why not just restrict the access to DumpQueueMain.java ?
