### ISSUE TITLE
Fixed ARM compatibility

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#656]
see https://teamcity.chronicle.software/buildConfiguration/OpenHFT_ChronicleQueue4_SnapshotLinuxArm?mode=builds

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.11), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)
