### ISSUE TITLE
"read only" Pretoucher

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#657]
Can we give pretoucher a mode so that it doesn't try and cause any writes to the queue? I would like to run the pretoucher such that *all* it does is pretouch memory and does not cause any writes to the queue at all i.e. no writing EOF, no creating new cycle files.

I'm happy to pay the price of a bit of latency at roll time.

@RobAustin @peter-k-lawrey What do you think?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.9](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.9), [BOM-2.19.106](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.106)
