### ISSUE TITLE
Added double buffering for contended appends

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#658]
Add double buffering for contended appends, create a latency test to see if this enhancement makes a positive difference, if it does,  add the results to the queue readme.adoc. If there is no benefit then we can remove this code ( or only support this functionality via a system property )

**Comment by JerryShea** [comment]
We had this before and removed it

**Comment by dpisklov** [comment]
@JerryShea I tried arguing but we decided I waste some time to prove it won't make much difference... ;)

**Comment by RobAustin** [comment]
@JerryShea - I know, That's why we have to benchmark it to see if it really makes a difference. Then we can see if it is worth documenting and adding back in.

**Comment by RobAustin** [comment]
This is a feature that @peter-lawrey wants put back in the code.
