### ISSUE TITLE
Improved ChronicleReaderMain to take an interface

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#659]
Improved QueueReaderMain to take an interface that supports a custom readMarshable, so all messages can be decoded, even those written as raw bytes.

**Comment by peter-lawrey** [comment]
Extended an existing argument `-r {interface}` to use the interface to decode all messages in the queue. This adds support for

- methods using @MethodID to replace named methods with numbers for efficiency
- methods using DTOs which are `BytesInBinaryMarshallable` or any custom marshallable code.

NOTE: the `readMarshallable` and `writeMarshallable` code can be generated in IntelliJ using live templates.
https://github.com/OpenHFT/Chronicle-Wire#code-generation-for-marshallable

Using `BytesInBinaryMarshallable` and code generation make small but significant improvements but at the cost of flexability i.e. schema changes are handled easiest with `SelfDescribingMarshallable`
