### ISSUE TITLE
Are all writes atomic?

### ISSUE THREAD

**Issue by cemelo** [OpenHFT/Chronicle-Queue#662]
Are writes atomic even if the data size is greater than `PIPE_BUF`?

**Comment by JerryShea** [comment]
What is PIPE_BUF?

**Comment by JerryShea** [comment]
And please raise issues here, and use stackoverflow for questions

**Comment by cemelo** [comment]
My bad, I saw you guys had a `question` tag, so I though this could be a good place to ask. Will stick to SO, then.

Thank you.

**Comment by JerryShea** [comment]
no worries @cemelo
