### ISSUE TITLE
fixed AppenderFileHandleLeakTest.tailerShouldReleaseFileHandlesAsQueueRolls

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#675]
This test is currently *not* ignored and TeamCity is green 

![image](https://user-images.githubusercontent.com/6506056/92920756-b7f03d00-f42a-11ea-88a2-e04b63d97227.png)

is it looks like it has already been fixed ( had to confirm locally as I'm using a Mac and this is a Linux only test )

**Comment by RobAustin** [comment]
It is likely related to https://github.com/OpenHFT/Chronicle-Core/issues/121

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.22](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.22), [BOM-2.20.56](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.56)
