### ISSUE TITLE
tailer.moveToIndex() fails when requested index is at the end

### ISSUE THREAD

**Issue by darkamgine** [OpenHFT/Chronicle-Queue#683]
When running on the latest CQ 5.19.31, tailer.moveToIndex() fails when the index is the end of the queue.

Example test code:
```
    public void syncIndexBetweenTailersTest() throws InterruptedException {
        try (final ChronicleQueue queue = ChronicleQueue.singleBuilder("cqtest").build()) {

            final ExcerptAppender appender = queue.acquireAppender();

            for (int x = 0; x < 3; x++) {
                try (DocumentContext dc = appender.writingDocument()) {
                    dc.wire().write("test").text("testing " + x);
                }
            }
            Thread.sleep(1500);

            final ExcerptTailer tailerAhead = queue.createTailer("ahead");
            final ExcerptTailer tailerBehind = queue.createTailer("behind");

            while (true) {
                try (DocumentContext dc = tailerAhead.readingDocument()) {
                    if (dc.isPresent()) {
                        String result = dc.wire().read("test").text();
                        System.out.println(result);
                    } else {
                        break;
                    }
                }

                System.out.println("Before Move - Ahead: " + tailerAhead.index() + ", Behind: " + tailerBehind.index());
                final boolean success = tailerBehind.moveToIndex(tailerAhead.index());
                assertTrue(success);
                System.out.println("After Move  - Ahead: " + tailerAhead.index() + ", Behind: " + tailerBehind.index());
                assertEquals(tailerAhead.index(), tailerBehind.index());
            }

            tailerBehind.toEnd();
            assertEquals(tailerAhead.index(), tailerBehind.index());
        }
```

The above works until the final iteration of the read loop, where the moveToIndex call returns false and the assertTrue(success) fails.

**Comment by dpisklov** [comment]
@darkamgine this is correct behaviour.
If you read javadocs for `ExcerptTailer#index()`, you will see this:

```
If this method is invoked within a {@code try (tailer.readingDocument){ }} block, returns the index of
the current reading document. Otherwise, returns the next index to read.
```

That means, tailer's index after an attempt to read data (whether successful or not) will always point to the next index, not the current one. But moveToIndex will not move to the index that does not exist. So in your test, after you read the last existing entry in the queue, tailer's index points at the next (non-existent) entry, and when you try to moveToIndex to that index, it obviously will not be successful, and your tailerBehind will remain at the previous (existing) index, until you read data from it. If you want to go past the last entry however, you can use toEnd().

**Comment by darkamgine** [comment]
Thanks @dpisklov for the answer. In this case, what is the right way to make my "behindTailer" be at the same state (index) as my "aheadTailer", given that my "aheadTailer" may or may not be at the end and my "behindTailer" is at an unknown state?

Should I do something like this??
```
                final boolean success = tailerBehind.moveToIndex(tailerAhead.index());
                if (!success) {
                    tailerBehind.moveToIndex(tailerAhead.index() - 1); //assume that index() - 1 is legit, even across cycles?
                    DocumentContext dc = tailerBehind.readingDocument().isPresent(); //move +1
                }
```

Or 
```
                final boolean success = tailerBehind.moveToIndex(tailerAhead.index());
                if (!success) {
                    tailerBehind.toEnd(); //assume that the only way moveToIndex could fail is if tailerAhead is at the end
                }
```

**Comment by dpisklov** [comment]
@darkamgine the second option is more appropriate IMO, but why you need to do that? What is it you are trying to achieve?

**Comment by darkamgine** [comment]
@dpisklov So I am used to using Kafka, and it allows you to read a batch of records without changing the offset until you explicitly call a commitSync() function. Perhaps there's another way to do this in CQ that I haven't figured out yet.

Basically, I'm using CQ as a durable queue for incoming events. These events are then asynchronously read in a batch (a few hundred at a time) and processed, but the processing step is liable to fail, and I don't want to update the index of my tailer until I have confirmed that the processing step has completed successfully, as it's possible in the default behavior for me to skip over events if the app crashes after the tailer has read but before the processing step succeeds.

I understand there's a rollback feature in CQ, but it seemed easier to me to implement this behavior with two separate tailers, one tracking "reads that I have marked as completed processing" (confirmed reads) and one for "reads that I'm currently processing" (unconfirmed reads). I then sync the confirmed index with the unconfirmed index in a separate call once the processing has finished. If the app dies, I have set it so that when it restarts, the unconfirmed is then reset to the position of the confirmed so that it can reprocess events (at least once guarantees).

It sounds a bit convoluted but I don't know what would be a better way to achieve this.

**Comment by dpisklov** [comment]
@darkamgine I don't think using 2 tailers is a good choice here, and can thingk of a few scenarios where it will not work - e.g. if the data is written in between your "commit" (that is, batch finished) event and call to `toEnd()`, that data will be skipped. More precisely, if your commit calls moveToIndex on the "confirmed" tailer, and `moveToIndex()` returns false (as there's no more data), then you call `toEnd()`, but just between `moveToIndex()` and `toEnd()` calls there's new piece of data written to the queue - your "confirmed" will point to the index past those new entries. (I appreciate it's slightly brain-dump-style but hope you get an idea).

What I'd suggest instead is store the last processed (successfully) index in the output, or if there's no explicit output - just create an artificial queue and write last processed index to it, so that upon restart after crash you look at the last entry in that queue and moveToIndex(lastStoredIndex) (and skipping that entry).

PS the "at least once" processing is implemented in our commercial product called Chronicle Services. It is a [microservices framework ](https://chronicle.software/solutions/framework/), and sounds like a good match for what you are doing. If you're interested - please get in touch on sales@chronicle.software and it might save you quite a bit of time developing your own solution.

**Comment by darkamgine** [comment]
Yeah, that is a potential issue which is why I was trying several implementations, such as the two mentioned above and using each one by one until a check that the commit tailer index matches the read tailer's passes. Altering the output is not permitted, but I also don't want to create another entire queue as I'm doing this with a set of queues and would need 2n queues, so perhaps the right way is to use chronicle map to store the offsets instead?

Just not sure if the overhead of two tailers is lower than that of maintaining a separate chronicle map.

**Comment by dpisklov** [comment]
@darkamgine you can use single queue for all your indexes (use a queue name as a key when writing, smth like `dc.wire().write(queueName).int64(idx)`), and then read the queue backwards on restart until you find a key for the particular queue. This will be fast enough on restarts, and really quick during normal operation (write to a chronicle queue is around a microsecond), while being bullet-proof (btw calls to moveToIndex might be more expensive than writes to the separate queue).
