### ISSUE TITLE
Fix marshallability for SingleChronicleQueueBuilder

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Queue#686]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.44](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.44), [BOM-2.19.274](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.274)
