### ISSUE TITLE
fixed optimizedToEnd() which was producing the wrong result 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#689]
under certain circumstances stroreTailer. optimizedToEnd() produces the wrong result. Please fix and test with software.chronicle.enterprise.queue.replication.SimpleFailoverExampleTest#replication in the chronicle-queue demo which was where this issue was picked up in the first place.

**Comment by RobAustin** [comment]
@glukos - See note above, please also add optimizedToEnd() back into the code and add test(s)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.104](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.104), [BOM-2.20.142](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.142)
