### ISSUE TITLE
TSQueueLock should be allowed to be unlocked from a different thread

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#690]
TSQueueLock should be unlocked from a different thread, for example, when a sink queue is locked to prevent the user from modifying the queue while replication is in progress, this should later be allowed to be unlocked from the application thread once replication is stopped by the user

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.73](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.73), [BOM-2.19.349](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.349)
