### ISSUE TITLE
How do you handle page cache writeback stalls?

### ISSUE THREAD

**Issue by rigtorp** [OpenHFT/Chronicle-Queue#692]
Since file-backed mmap is used, how do you handle page cache writeback stalls? Typically for any low latency workload you want to avoid using any PROT_WRITE mmap since page cache writeback will introduce stalls when writing to memory.

**Comment by RobAustin** [comment]
We use a pretoucher.

**Comment by JerryShea** [comment]
Hi @rigtorp please use stackoverflow for questions and keep issues for issues. Thanks
