### ISSUE TITLE
StoreFileListener not called consistently appender vs tailer

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#694]
Appenders call `net.openhft.chronicle.queue.impl.StoreFileListener#onAcquired` and `#onReleased`

Tailers only call `#onAcquired`

**Comment by dimm-p** [comment]
Hello OpenHFT team,

Do you have any plans to fix this issue?
It would be great for me to have an option to remove files which were processed by tailer.

Regards,
     Dmitry.

**Comment by dpisklov** [comment]
@dimm-p we are going through the issues on a priority basis with commercial clients' issues being prioritized first. If this feature is something you need for a commercial project please contact sales@chronicle.software

**Comment by JerryShea** [comment]
#724 duplicates this

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.42](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.42), [BOM-2.20.67](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.67)
