### ISSUE TITLE
Ensure references to files released after file roll

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#695]
So that there are no file handles left pointing to them.

See https://github.com/OpenHFT/Chronicle-Queue/commit/05ab62311dc4a326e175d70c0b7c4f2b58270229

**Comment by JerryShea** [comment]
See also https://github.com/OpenHFT/Chronicle-Core/issues/121

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.75](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.75), [BOM-2.19.364](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.364)
