### ISSUE TITLE
Added disableThreadSafetyCheck for ExcerptAppender as it does for ExcerptTailer

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#704]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.20](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.20), [BOM-2.20.37](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.37)
