### ISSUE TITLE
Added support for custom replication allowing you to add any cycle, even if another appender has been used.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#705]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.20](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.20), [BOM-2.20.37](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.37)
