### ISSUE TITLE
Don't reset the cycle on a NOT_REACHED state

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#731]
Doing so add a performance penality on each missed entry

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.64](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.64), [BOM-2.20.87](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.87)
