### ISSUE TITLE
Fixed issue around NOT_REACHED_IN_CYCLE

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#733]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.64](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.64), [BOM-2.20.87](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.87)
