### ISSUE TITLE
fixed net.openhft.chronicle.queue.ChronicleQueueIndexTest.read5thMessageTest

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#734]
The problem here is with chronicle queue, not the test case. @glukos could you change chronicle queue so that the test case passes. The test was passing, but I had to revert some changes peter put into Store Tailer ( my commit was https://github.com/OpenHFT/Chronicle-Queue/commit/912cd32bbda4d4988a25d06e5d597ed1c922137c) as chronicle-queue was causing the following test in  DataGrid software.chronicle.datagrid.internal.queue.IndexAwareSubscriberTest#testIndexAwareIndices, to fail. So please don't just re-apply Peters changes, without first checking Datagrid.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.102](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
