### ISSUE TITLE
Prevent the chronicle queue reader from outputting "File released.. " when run

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#738]
I've set the chronicle queue builder store listener to NO_OP

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.85](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.85), [BOM-2.20.118](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.118)
