### ISSUE TITLE
Check the current cycle, before calling storeForCycle(..), as the code was creating too many WireStores

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#740]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.85](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.85), [BOM-2.20.118](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.118)
