### ISSUE TITLE
ensure ChronicleQueue#sourceId reflects stored sourceId

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#742]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.104](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.104), [BOM-2.20.142](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.142)
