### ISSUE TITLE
closed appender can be re-acquired

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#743]

**Comment by RobAustin** [comment]
@JerryShea please provide more detail, ideally a failing test.

**Comment by JerryShea** [comment]
See the link above but also....
If you acquire an appender, then close it, then acquire again, you get the closed appender from the 1st acquire - which is not very useful.

**Comment by glukos** [comment]
Closing an acquired appender looks like the API misuse - acquire() is designed to free a user from creating and closing an appender manually. Meanwhile, appender is closeable, which tempts to wrap acquire() in try-finally block...
I've added a simple fix that re-creates an appender if it has been closed.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.123](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.123), [BOM-2.20.226](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.226)
