### ISSUE TITLE
If we detect thread is interrupted during appender.close, throw an exception instead of silently rolling back

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#746]
Follow on from #745

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.106](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.106), [BOM-2.20.146](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.146)
