### ISSUE TITLE
Make automatic lock recovery an option

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#747]
Currently, if chronicle queue tries to acquire a lock and the lock times out, it will automatically recover from this lock.

This issue is to make this behaviour configurable i.e. we don't try and recover and instead throw `UnrecoverableTimeoutException`.

Note also that a number of methods have throws `UnrecoverableTimeoutException` in their signature, but don't actually throw it.

**Comment by JerryShea** [comment]
Have made this optional and added a test. Default behaviour is same as before.

**Comment by RobAustin** [comment]
Is the default the existing behaviour ?

**Comment by JerryShea** [comment]
Yes
