### ISSUE TITLE
Rollcycles : removed 'durationOfCycle()' as this is already provided by 'lengthInMillis()'

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#752]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.109](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.109), [BOM-2.20.158](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.158)
