### ISSUE TITLE
Ensure QueueUnlockMain always unlocks

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#757]
Also add javadoc, and remove some unused (not released yet) API methods

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.112](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.112), [BOM-2.20.171](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.171)
