### ISSUE TITLE
Reduce warnings when a queue is slow to close

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#759]
We now have a test which reliably reproduces a warning where a queue is closed but the resources are still being used in another thread. `software.chronicle.enterprise.queue.test.ReplicationFailbackTest`

This test helped determine that the warning was no longer needed and the clean up could be simplified.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.114](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.114), [BOM-2.20.178](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.178)
