### ISSUE TITLE
Deprecate QueueLock#waitForLock

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#760]
Better to use acquireLock then unlock

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.114](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.114), [BOM-2.20.178](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.178)
