### ISSUE TITLE
SingleChronicleQueueBuilder rollTime & rollTimeZone set from YAML

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#761]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.114](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.114), [BOM-2.20.178](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.178)
