### ISSUE TITLE
sharing data between two java programs

### ISSUE THREAD

**Issue by ericfoongcheesoon** [OpenHFT/Chronicle-Queue#764]
I am very new to chronicle-queue. Please answer these questions to help me get started with the chronicle-queue:
(1) How chronicle-queue exchange data between two java programs that are running in two different jvm? socket programming, or shared memory?

(2) If two java programs are running in two separate docker container, can these two programs exchange data using chronicle-queue?

**Comment by dpisklov** [comment]
Please [read](https://github.com/OpenHFT/Chronicle-Queue#overview) the [documentation](https://github.com/OpenHFT/Chronicle-Queue/blob/master/docs/FAQ.adoc#does-chronicle-queue-work-in-linux-containers) before asking questions, and please do not raise issues for questions (for questions there's stackoverflow)
