### ISSUE TITLE
Inverted evaluation for thread safety check property

### ISSUE THREAD

**Issue by Adriankusiak** [OpenHFT/Chronicle-Queue#768]
StoreAppender appears to be running a threadSafetyCheck only if the property is disabled, always returning true in the AbstractClosable parent method:

```
public DocumentContext acquireWritingDocument(boolean metaData) {
        if (!CHECK_THREAD_SAFETY)
            this.threadSafetyCheck(true);
        if (wire != null && writeContext.isOpen() && writeContext.chainedElement())
            return writeContext;
        return writingDocument(metaData);
}
```

**Comment by dpisklov** [comment]
@peter-lawrey is it intentional by any chance?

**Comment by peter-lawrey** [comment]
The problem is that the default value for CHECK_THREAD_SAFETY is also incorrect, so it works provided you set it to false to turn it on. :P

**Comment by peter-lawrey** [comment]
The problem is that the default value for CHECK_THREAD_SAFETY is also incorrect, so it works provided you set it to false to turn it on. :P
