### ISSUE TITLE
QueueFileShrinkManager#task should lock file before changing size?

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#772]
Like MappedFile.resizeRafIfTooSmall. Should MappedFile expose this mechanism for QueueFileShrinkManager to use?

**Comment by dpisklov** [comment]
why would it need to lock the file? Shrinking only ever happens after EndOfWire written to the file and hence no other appender would be able to write to it, and shrinking itself only happens in single thread.

**Comment by RobAustin** [comment]
assigning to @nicktindall, given that you are changing the file locking around queue enterprise.

**Comment by nicktindall** [comment]
Suspect this isn't an issue, closing
