### ISSUE TITLE
InterruptedException should not be ignored

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Queue#783]
In the class `StoreAppender.StoreAppenderContext.close()`, the catched `InterruptedException` does not propagate the interrupt state.

The throwing of the `InterruptedException` clears the interrupted state of the Thread, so if the exception is not handled properly the fact that the thread was interrupted will be lost. Instead, InterruptedExceptions should either be rethrown - immediately or after cleaning up the method's state - or the thread should be re-interrupted by calling `Thread.interrupt()`.

**Comment by JerryShea** [comment]
Yes good point. The `InterruptedException` can actually be thrown by `StoreAppender.StoreAppenderContext.close()` and this behaviour is exercised by net.openhft.chronicle.queue.impl.single.NotCompleteTest.

**Comment by JerryShea** [comment]
Please review attached change

**Comment by minborg** [comment]
Looks perfect to me! I am closing this issue. Thanks @JerryShea

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.123](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.123), [BOM-2.20.226](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.226)
