### ISSUE TITLE
Deprecate acquireTailer

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#790]
See also #787

**Comment by JerryShea** [comment]
Decision has been made that the queue should not be responsible for closing acquired tailers and appenders - the user is

**Comment by JerryShea** [comment]
Deprecated acquireTailer - net.openhft.chronicle.queue.impl.single.SingleChronicleQueue#exceptsPerCycle may need some work

**Comment by RobAustin** [comment]
We should not deprecate acquireAppender, at least, not at the moment, as this usage is heavily backed in.

**Comment by JerryShea** [comment]
Yes - shall we rename the issue?

**Comment by RobAustin** [comment]
> Yes - shall we rename the issue?
> […](#)

done rename of issue

**Comment by JerryShea** [comment]
@RobAustin in that case I think we can close ;)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea45](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea45), [BOM-2.21ea118](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea118)
