### ISSUE TITLE
Remove code duplication between ChronicleHistoryReader and InternalChronicleHistoryReader

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#792]
It maybe that - it is difficult to dedupe chronicle history reader because it was designed to be extensible. One option could be to leave as it was and remove the duplicated internal version. What do you think ?

**Comment by minborg** [comment]
The `ChronicleHistoryReader` is `@Depricated` for removal in x.22. Instead, users are encouraged to use the `HistoryReader.create()` method which will provide an `InternalChronicleHistoryReader` (the latter is not a part of the API commitment). The reason for this was that `ChronicleHistoryReader` (and other similar classes) carried a huge API commitment as they were non-final and contained extensible methods.

Therefore, I recommend that we leave the `ChronicleHistoryReader` and all the other deprecated classes in the `net.openhft.chronicle.queue.reader` package as they are. They will meet the ultimate deduplication faith (i.e. they will be deleted) in a near future.

**Comment by minborg** [comment]
I will take a look at deduplicating code since the actual removal of deprecated classes might take some time.

**Comment by JerryShea** [comment]
My concern is that to fix #791 I had to fix it in 2 places, and that was not obvious....

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea3](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea3), [BOM-2.21ea21](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea21)
