### ISSUE TITLE
Improve ChronicleReaderMain replacement

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Queue#794]
A customer has a custom chronicle reader for fix logs which descends from ChronicleReaderMain and overrides configureReader, fixLogRenderer, and options

We should add provisions to obtain equivalent functionality with the new implementations.

**Comment by RobAustin** [comment]
@minborg as discussed, could you revert the original change to ChronicleReaderMain ( in other words, put the code back to as it was a couple of months ago, for this class and associated classes ) and issue @JerryShea, with a pull-request. Let's start by doing this, and we can then later discuss as a team about reintroducing some, or part, of your change, back in, at a later date. Sorry that this is a bit drastic but its a lower risk approach to put stuff back as it was.

**Comment by minborg** [comment]
Looking at the non-final class `ChronicleReaderMain` we can conclude the following:

Users invoking the `main` method directly cannot override methods because the main method always creates the same class. Thus. the indicated `net.openhft.chronicle.queue.main.ReaderMain` provides a 1:1 substitute.

However, users inheriting from the class can override all of the classe's methods:

 - run(). (we could make this method final)
 - chronicleReader()
 - parseCommandLine()
 - printHelpAndExit() (we could make this method final)
 - configureReader()
 - options()

For this very reason, it would be highly desirable to remove the class from the API. The class allows subclassing but is not designed to be safely subclassed. 

Instead, a builder could be provided where one could provide similar constructs. This provides a much smaller API surface.

That said, there are no changes to the class made other than the actual deprecation so that is the only thing that needs to be rolled back, should we elect to do so. I agree that it was a bit premature to deprecate the class before a proper replacement was introduced.

**Comment by minborg** [comment]
This is how a `Builder` could be defined:

```

public final class ReaderMain {

    public static void main(@NotNull String[] args) {
        InternalReaderMain.main(args);
    }

    interface Builder {

        // These "standard" methods provide base functionality

        BiFunction<String[], Options, CommandLine> standardParser();

        Options standardOptions();

        BiConsumer<Reader, CommandLine> standardConfigurator();

        // These "withers" provide override capabilities

        Builder withReader(Reader reader);

        Builder withParser(BiFunction<? extends String[], ? extends Options, CommandLine> parser);

        Builder withOptions(Options options);

        Builder withConfigurator(BiConsumer<? super Reader, ? super CommandLine> configurator);

        /**
         * Builds and returns a runnable instance.
         *
         * @return returns a runnable instance
         */
        Consumer<String[]> build();

    }
```
