### ISSUE TITLE
Remove (or deprecate) strongAppenders config on SingleChronicleQueueBuilder

### ISSUE THREAD

**Issue by rossisandro** [OpenHFT/Chronicle-Queue#803]
Since the release of ```chronle-queue-5.19.40``` (14e27ed78946329aa2dd9b159020d84f42fffce1), the ```strongAppenders``` configuration parameter of ```SingleChronicleQueueBuilder``` has no effect on ```SingleChronicleQueue```

The methods ```public SingleChronicleQueueBuilder strongAppenders(boolean strongAppenders)``` and ```public boolean strongAppenders()``` needs to be removed from ```SingleChronicleQueueBuilder``` (or at least marked as deprecated) to signal client applications that this setting is no longer valid.

**Comment by JerryShea** [comment]
Thanks @rossisandro I have deprecated
