### ISSUE TITLE
NullPointerException in StoreTailer.inACycle

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#804]
stack trace below
```
2021-02-08 10:29:54,057 ERROR ...
java.lang.NullPointerException: null
	at net.openhft.chronicle.queue.impl.single.StoreTailer.inACycle(StoreTailer.java:419)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:191)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:126)
	at net.openhft.chronicle.wire.AbstractGeneratedMethodReader.readOne(AbstractGeneratedMethodReader.java:167)
        ...
```

The queue is configured with daily rolling so I don't think this is related to rolling.

This happened very soon after service startup so it is possible that the queue it is reading from is in the process of being created.

This is CQ 5.21ea4 so it is the line with <<<< below i.e. `wire` is null:
```
    private boolean inACycle(final boolean includeMetaData) throws EOFException {
        ...
        final Wire wire = privateWire();
        final Bytes<?> bytes = wire.bytes(); <<<<
        return inACycle2(includeMetaData, wire, bytes);
    }
```
`privateWire` ultimately calls 
```
    @Nullable
    public Wire wire() {
        return this.wire;
    }
```

**Comment by RobAustin** [comment]
it can be null if closed

![image](https://user-images.githubusercontent.com/6506056/107413844-271cab00-6b09-11eb-808d-db60aad3feb9.png)

**Comment by RobAustin** [comment]
or when it is changing its cycle

![image](https://user-images.githubusercontent.com/6506056/107413988-5501ef80-6b09-11eb-91a5-4eceda40f724.png)

**Comment by RobAustin** [comment]
Given that the code is single threaded I'm not sure how this can happen, I would ask your client to check that they have only a single thread accessing the tailer.

**Comment by RobAustin** [comment]
We could add this check, if it helps but given what you said, I don't feel they are in the process of shutting down.

![image](https://user-images.githubusercontent.com/6506056/107414504-fe48e580-6b09-11eb-823a-3dfe415b36be.png)

@JerryShea  would you be able to create a reproducible test case that can demonstrate their issue.

**Comment by JerryShea** [comment]
I don't know how to reproduce it but closing is definitely a possibility - reviewing the log file again, soon after there is
```
net.openhft.chronicle.core.io.ClosedIllegalStateException: net.openhft.chronicle.queue.impl.single.StoreTailer closed
	at net.openhft.chronicle.core.io.AbstractCloseable.throwExceptionIfClosed(AbstractCloseable.java:182)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:182)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:126)
	at net.openhft.chronicle.wire.AbstractGeneratedMethodReader.readOne(AbstractGeneratedMethodReader.java:167)
```
And while I don't know if it is referring to the same queue, I believe that in this component all queues will be closed at the same time. Given also that closing can happen in another thread, that seems the likely cause.

**Comment by JerryShea** [comment]
I think your suggested code change is a good idea and I have made that change - thanks @RobAustin
