### ISSUE TITLE
Add code to check power management on linux

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#807]
Add code to check power management on linux, in other words, raise a warning if optimal power management settings are not being used.  Please also check that the Spector patch is turn off, and check the c-states. 

Produce an automatically generated text report to the log file ( recommending possible changes ), if the machine is not running optimally then please log out warning messages accordingly. This code should be added to chronicle-core. 

How this is done is of course dependent upon the flavour of Linux, one such place that can be checked is:

```
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
```

see also https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html

**Comment by minborg** [comment]
If we could collect these methods in `core`, for example, then we could reuse them for Map too.

**Comment by RobAustin** [comment]
@JerryShea  - I see your point, I feel we should produce the report in our open source tooling, ( but perhaps not to suggest the changes ) , we can then say if you would like assistance please contact sales@chroncle.software. This way it will help drive new relationships.

**Comment by RobAustin** [comment]
@minborg, I agree -  we should add it to all our libraries, So that it is checked on startup.

**Comment by minborg** [comment]
Diagnosing potential improvements and then encouraging customers to engage with us to reap the benefits sounds like a very good idea indeed.

**Comment by minborg** [comment]
We could construct the feature akin to core's analytics which can be easily used by any library.

E.g. `PowerManagement.hints() -> Stream<String> `

**Comment by maxim-ponomarev** [comment]
Closed in the scope of OpenHFT/Chronicle-Core#405.

Added checks for scaling governors being in "performance" state, disabled C-states, spectre mitigation, audit and page table isolation.
Checks are performed in Core `Jvm`'s static initializer, so should be picked up by all our products.
