### ISSUE TITLE
map and queue cant be used in same project

### ISSUE THREAD

**Issue by deflorilemarului** [OpenHFT/Chronicle-Queue#811]
Hi, 

We have a project where we want to use both chronicle map and queue, because they are great libraries. 
However, it seems they cannot coexist in the same project ? they both seem to use totally incompatible chronicle-core versions.

implementation "net.openhft:chronicle-map:3.20.84"
implementation "net.openhft:chronicle-queue:5.17.8"

Any idea if this is possible ? Any suggestion for a solution ?

Much appreciated.

**Comment by RobAustin** [comment]
Use the Chronicle-BOM in your project this will ensure they are compatible versions.
