### ISSUE TITLE
test coverage for net.openhft.chronicle.queue.impl.single.StoreAppender#writeBytesInternal(long, net.openhft.chronicle.bytes.BytesStore, boolean)

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#820]

**Comment by nicktindall** [comment]
Added https://github.com/OpenHFT/Chronicle-Queue/blob/develop/src/test/java/net/openhft/chronicle/queue/impl/single/StoreAppenderInternalWriteBytesTest.java

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea48](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea48), [BOM-2.21ea123](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea123)
