### ISSUE TITLE
Cannot read from queue if first message is metadata

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#822]
If the 1st message written to a queue is metadata then that message can not be read from the queue. If a subsequent non-metadata message is written then that can be read. See net.openhft.chronicle.queue.ChronicleQueueIndexTest#writeReadMetadata

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea43](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea43), [BOM-2.21ea110](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea110)
