### ISSUE TITLE
toEnd().index() returns incorrect value for queues containing only metadata and empty pre-touched

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#825]
When you call `tailer.toEnd().index()` on a queue containing only metadata, or an empty queue that's been pre-touched, you get back the index of the first sequence of the empty/only-metadata cycle. This differs from the behaviour where the queue is non-empty but there are subsequent metadata-only or empty cycles. In that scenario you get back the index following the last excerpt present in the queue.

**Comment by nicktindall** [comment]
I added a PR to demonstrate the issues https://github.com/OpenHFT/Chronicle-Queue/pull/829

**Comment by rogersimmons** [comment]
@nicktindall - can you move your commits onto a branch (eg Issue825) under the chronicle repo. Thanks

**Comment by nicktindall** [comment]
Hi @rogersimmons I'm not a member of the OpenHFT org yet, if you could create that branch I'll move the target of my PR to that so we can get it over?

**Comment by nicktindall** [comment]
The PR is on the OpenHFT org now

**Comment by peter-lawrey** [comment]
#822 adds a dummy index entry for the first metadata message that can be found. This causes other methods to assume there is a real entry into the cycle when there isn't.

The fix is to support `moveToCycle` and only index `data` entries.

**Comment by peter-lawrey** [comment]
@rogersimmons Can you review so that the C++ index doesn't index meta data entries as a workaround?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea44](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea44), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
