### ISSUE TITLE
ChronicleReader -i and -m

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#831]
allow combine together of -i and -m i.e. display last X matching messages

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea44](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea44), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
