### ISSUE TITLE
Two ChronicleQueue pointing to the same underlying queue can overwrite index 0 with writeIndex

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#835]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea44](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea44), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
