### ISSUE TITLE
improve inconsistent sourceId detection

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#839]
See https://github.com/OpenHFT/Chronicle-Queue/pull/838

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea46](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea46), [BOM-2.21ea119](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea119)
