### ISSUE TITLE
failing MultiThreadedRollTest

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#842]
I have @Ignored this test for now.

It calls `net.openhft.chronicle.queue.impl.single.StoreAppender#writeEndOfCycleIfRequired` which I suspect we don't need any more. @peter-k-lawrey I think you created this function - do you have any comment?

If we remove the call to `writeEndOfCycleIfRequired` the test passes.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea46](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea46), [BOM-2.21ea119](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea119)
