### ISSUE TITLE
SingleChronicleQueueBuilder.binary(path).build() the path can use remote address?

### ISSUE THREAD

**Issue by sunbiaozj** [OpenHFT/Chronicle-Queue#845]
Hi SingleChronicleQueueBuilder.binary(path).build() 
the path can use remote address? for example remote machine
thank you

**Comment by nicktindall** [comment]
No, only local filesystems are supported, please see https://github.com/OpenHFT/Chronicle-Queue#important-note

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea46](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea46), [BOM-2.21ea119](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea119)
