### ISSUE TITLE
There appears to be a race condition when double buffering is used

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#852]

**Comment by peter-lawrey** [comment]
Disabling double buffering until it can be fixed.

**Comment by jkolobok** [comment]
@peter-lawrey is it done? Can we close the issue? A client is having a likely related issue

**Comment by glukos** [comment]
Recently fixed race condition with double buffering: https://github.com/OpenHFT/Chronicle-Wire/pull/450
Probably this issue can be closed.

**Comment by JerryShea** [comment]
@glukos This issue refers to Queue double-buffering `SingleChronicleQueueBuilder#doubleBuffer()`

**Comment by tgd** [comment]
Closing this out as no work is planned on this issue at the moment. Please comment on this issue if you would like it re-opened.
