### ISSUE TITLE
Update docs on "Dumping a Chronicle Queue, cq4 file as text to the Command Line"

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#861]
This section - see https://github.com/OpenHFT/Chronicle-Queue#dumping-a-chronicle-queue-cq4-file-as-text-to-the-command-line

Is out of date, It won't run, as chronicle-queue now requires some additional jars, for example, the SLF jars, before it can run, please update the documentation to include all the jars required. Please also update the versions of the jars in the example to the latest version.

**Comment by JerryShea** [comment]
@julgus note there is dump_queue.sh which uses the shaded jar

**Comment by RobAustin** [comment]
thanks, @JerryShea,

@julgus please also add the dump_queue.sh to the doco.

**Comment by julgus** [comment]
This is what I gathered using `mvn dependency:tree`. 

[INFO] +- net.openhft:chronicle-core:jar:2.21ea61:compile
[INFO] |  \- org.jetbrains:annotations:jar:19.0.0:compile
[INFO] +- net.openhft:chronicle-bytes:jar:2.21ea61:compile
[INFO] +- net.openhft:chronicle-wire:jar:2.21ea61:compile
[INFO] |  \- net.openhft:compiler:jar:2.21ea1:compile
[INFO] +- net.openhft:chronicle-threads:jar:2.21ea63-SNAPSHOT:compile
[INFO] +- net.openhft:affinity:jar:3.21ea2:compile
[INFO] |  +- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  \- net.java.dev.jna:jna-platform:jar:5.5.0:compile
[INFO] +- commons-cli:commons-cli:jar:1.4:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile

Does `DumpMain` require `commons-cli:commons-cli:jar`, and `net.openhft:affinity:jar`? 

Also, what SLF4j jar is required beyond `org.slf4j:slf4j-api:jar`?

**Comment by RobAustin** [comment]
> Does DumpMain require commons-cli:commons-cli:jar, and net.openhft:affinity:jar?
> 
This maybe useful for ChronicleReaderMain - The Apache Commons CLI library provides an API for parsing command line options passed to programs. It's also able to print help messages detailing the options available for a command line tool.

> Also, what SLF4j jar is required beyond org.slf4j:slf4j-api:jar?
> 
good point - org.slf4j » slf4j-simple 


It maybe worth also having docs for ChronicleReaderMain which is a very similar tool, here is a script that can run net.openhft.chronicle.queue.ChronicleReaderMain, The ChronicleReaderMain implements the same sort of thing, but gives more control to the user ( in the form of command line options ), if you could also document this ( if it is not already done ) that would be great. The script below uses an Uber (shaded ) jar, but the approach that you have taken of listing all the dependencies on the class path would also work

```
#!/bin/sh
SCRIPT_DIR=$(dirname "$0")

if [[ "$1" == "" ]]; then
    echo "Usage: $0 [chronicle-queue-directory]"
    exit 1
fi

UBER_JAR="${SCRIPT_DIR}/all.jar"
echo $UBER_JAR
if [[ ! -f $UBER_JAR ]]; then
    echo "Could not find uber-jar, please run 'mvn package' in the project root"
    exit 1
fi

java -cp "$UBER_JAR" net.openhft.chronicle.queue.ChronicleReaderMain "$@“
```

**Comment by julgus** [comment]
Thank you! There is some documentation for `ChronicleReaderMain` which I will have a look at.

**Comment by RobAustin** [comment]
great - if not already done please add a link and discuss ( in the documentation )  where it is appropriate to use one over the other.
