### ISSUE TITLE
Queues with blockSizes of 8GB+ fails.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#867]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea64](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea64), [BOM-2.21ea161](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea161)
