### ISSUE TITLE
Double-Checked Locking 

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [OpenHFT/Chronicle-Queue#884]
https://github.com/OpenHFT/Chronicle-Queue/blob/1617a4964d58cc18d42b2059bfea5304da563dc3/src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java#L922-L925

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

Modify the variable ‘longValue’ with volatile to tackle the problem.

**Comment by minborg** [comment]
Hi. The LongValue is not an instance property but rather a local variable. This local variable is only visible to the current thread and could live on the stack. I think the lock is there to prevent other threads from updating the `metaStoreMap` simultaneously.

Note: Declaring an instance variable as `volatile` in combination with DCL works fine.
