### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [OpenHFT/Chronicle-Queue#885]
https://github.com/OpenHFT/Chronicle-Queue/blob/1617a4964d58cc18d42b2059bfea5304da563dc3/load-harness/src/main/java/net/openhft/load/config/ConfigParser.java#L16

The program can potentially fail to release a system resource.

**Comment by JerryShea** [comment]
See https://github.com/OpenHFT/Chronicle-Queue/commit/e4a8072cd2709e543642757a96a9a3173bb7d7f7
