### ISSUE TITLE
LastAppendedTest fails when -DdisableProxyCodegen=true

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#889]
`LastAppendedTest` fails when `-DdisableProxyCodegen=true` because proxy method writers do not write `MessageHistory` (see also #460).

Proxy method writers will be removed in x.25.

**Comment by nicktindall** [comment]
Also some tests in ChronicleReaderTest

**Comment by RobAustin** [comment]
still fails with the latest code with the following:
![image](https://user-images.githubusercontent.com/6506056/167158235-8be9da32-8382-4d04-beea-def29acf986d.png)

**Comment by RobAustin** [comment]
see also this test - net.openhft.chronicle.wire.method.MethodWriterProxyTest

which is ignored:


![image](https://user-images.githubusercontent.com/6506056/167158465-68be282c-79bd-4392-b9b4-30f7a3315975.png)

**Comment by RobAustin** [comment]
I suggest we remove disableProxyGen as it is broken anyway, it was added in 2020

![image](https://user-images.githubusercontent.com/6506056/167158943-9b3b4639-ca7c-4f33-844e-bd0722f68666.png)

**Comment by glukos** [comment]
I see no reason to keep this property, +1 for removal.

P. S. It's enabled in `Chronicle-Queue-Demo\order-processor\pom.xml` - we should check if removal will impact the demo.

**Comment by JerryShea** [comment]
@glukos I have seen method reader/writer code generation not working when running with `mvn:exec`. I assume that is why that property is set in chronicle-queue-demo. There are other examples (e.g. chronicle-services benchmarks) where we commit the generated code to git to work around this.

Good news: I just tried removing that property from chronicle-queue-demo and ran the examples with `mvn:exec` and there were no problems.

I tried to run one of the chronicle services benchmarks without pre-generated code and it failed - but it worked once I bumped chronicle-core version in chronicle-bom (to bring in @alamar 's fix to core: https://github.com/OpenHFT/Chronicle-Core/pull/388). See also https://github.com/ChronicleEnterprise/Chronicle-Services/pull/326)

**Comment by JerryShea** [comment]
This is a very complicated area and we have some cleanup to do. As the concerns are in Wire, please see https://github.com/OpenHFT/Chronicle-Wire/issues/460

**Comment by JerryShea** [comment]
We can't just remove `disableProxyCodeGen` - we still need to support proxy method readers/writers - see https://github.com/OpenHFT/Chronicle-Wire/pull/473. 

We could fix proxy method readers/writers for this test, but I can't see the cost/benefit as they are legacy and with the above PR, generated method readers/writers support everything they need to.

I'll mark this issue as low priority and we can close once proxy method readers/writers are gone (or we can close now with wontfix now)

**Comment by JerryShea** [comment]
We can close this as wontfix when we roll to x.24 and remove the disableProxyCodegen property

**Comment by JerryShea** [comment]
Closing as we are not going to fix gaps in proxy method writers
