### ISSUE TITLE
IndexForIDTest failing consistently in TeamCity

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#897]
But not when run individually locally

See https://teamcity.chronicle.software/buildConfiguration/OpenHFT_ChronicleQueue4_Snapshot/594709?expandedTest=build%3A%28id%3A594709%29%2Cid%3A1668

**Comment by peter-lawrey** [comment]
This error occurs if the test takes 30 second.
The test takes 9 second on dev13 right now that I have enabled it again.
It takes 1.7 second on my desktop.

**Comment by peter-lawrey** [comment]
This test is more concurrent than it was previously.
On dev13 it will now use all the logical CPUs across both NUMA regions 
whereas before it was limited to a smaller thread pool.
This may explain why sometimes it has high delays.
