### ISSUE TITLE
RollCycleMultiThreadStressPretouchTest fails with SIGSEGV

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#901]
I ran until failure and got this after 84 runs (or 60-something another time)
[hs_err_pid16042.log](https://github.com/OpenHFT/Chronicle-Queue/files/6964933/hs_err_pid16042.log)

**Comment by JerryShea** [comment]
@nicktindall I improved stability of the pretoucher thread when shutting down with the above commit. I just ran this test locally 630 times with no issue. Can you re-try and hopefully you won't be able to reproduce?

**Comment by nicktindall** [comment]
Yep I can't reproduce locally. Will close.
