### ISSUE TITLE
SCQIndexing: passing newLogArrayValuesHolder as method reference triggers allocation every time the entry is indexed

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Queue#927]
Proof:
![image](https://user-images.githubusercontent.com/2736390/137534364-74de00bf-caf0-4d50-a43f-8ba22d4fca9f.png)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21.93](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21.93), [BOM-2.21.240](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.240)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22ea8](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22ea8), [BOM-2.22ea40](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea40)
