### ISSUE TITLE
Clearly mark Enterprise features

### ISSUE THREAD

**Issue by julgus** [OpenHFT/Chronicle-Queue#938]
Looking at `SingleChronicleQueueBuilder` along with the Queue documentation I find it hard to evaluate which of the fields in the builder are Enterprise features only. I recognize there is a method called `checkEnterpriseFeaturesRequested` that lists the Enterprise fields. However, it is easy to slip when using `rollTime` and set `zoneId` to something other than "UTC" and "Z" and thus receive an `IllegalArgumentException`. 

```
    private boolean checkEnterpriseFeaturesRequested() {

        boolean result = false;
        if (readBufferMode != BufferMode.None)
            result = onlyAvailableInEnterprise("Buffering");
        if (writeBufferMode != BufferMode.None)
            result = onlyAvailableInEnterprise("Buffering");
        if (rollTimeZone != null && !rollTimeZone.getId().equals("UTC") && !rollTimeZone.getId().equals("Z"))
            result = onlyAvailableInEnterprise("Non-UTC roll time zone");
        if (wireType == WireType.DELTA_BINARY)
            result = onlyAvailableInEnterprise("Wire type " + wireType.name());
        if (encodingSupplier != null)
            result = onlyAvailableInEnterprise("Encoding");
        if (key != null)
            result = onlyAvailableInEnterprise("Encryption");
        if (hasPretouchIntervalMillis())
            result = onlyAvailableInEnterprise("Out of process pretouching");

        return result;
    }
```

I would suggest that we either add an Enterprise annotation to Chronicle Core, or simply highlight the Enterprise features with clear JavaDocs. JavaDocs are present for some of the fields already, e.g. `writeBufferMode` although I do think these notes should be standardized in some way. See examples below: 

Here there is a note that only None is available for OSS. 
```
    /**
     * @return BufferMode to use for writes. Only None is available is the OSS
     */
    @NotNull
    public BufferMode writeBufferMode() {
        return wireType() == WireType.DELTA_BINARY ? BufferMode.None : (writeBufferMode == null)
                ? BufferMode.None : writeBufferMode;
    }
```

For `wireType`, there is nothing indicating OSS users cannot set this to `WireType.DELTA_BINARY`: 

```

    @NotNull
    public SingleChronicleQueueBuilder wireType(@NotNull WireType wireType) {
        if (wireType == WireType.DELTA_BINARY)
            deltaCheckpointInterval(64);
        this.wireType = wireType;
        return this;
    }
```

**Comment by minborg** [comment]
We could add `@EnterpriseFeature` in core.

In the future, we should have pluggable components and enterprise features should not be visible in open-source libraries.
