### ISSUE TITLE
Despite rolling cycle minutely deleting chronicle file after processing keeps file in open list lsof and not releasing memory

### ISSUE THREAD

**Issue by chaitas90** [OpenHFT/Chronicle-Queue#951]
I am using chronicle queue version 5.20.123 and open JDK 11 with Linux Ubuntu 20.04, when we recycle current cycle on minute rolling i am listening on StoreFileListener onRelease i am deleting file then also file remains open without releasing memory nor file gets deleted..Pls guide what is needed to be done in order to make it working..

```
Store FileListener Implemented like this:

  storeFileListener = new StoreFileListener() {
                    @Override
                    public void onReleased(int cycle, File file) {

                        file.delete();
                    }
                }

Creation of chronicle Queue as follows:

eventStore = SingleChronicleQueueBuilder.binary(GlobalConstants.CURRENT_DIR + GlobalConstants.PATH_SEPARATOR + EventBusConstants.EVENT_DIR + GlobalConstants.PATH_SEPARATOR+ eventType).rollCycle(RollCycles.MINUTELY).storeFileListener(storeFileListener).build();

tailer = eventStore.createTailer();

appender = eventStore.acquireAppender();

previousCycle = tailer.cycle();

Recycling of previous Cycle when processing completes:

 var store = eventStore.storeForCycle(previousCycle,0,false,null);

 eventStore.closeStore(store);
```
 
![Screenshot from 2021-11-16 12-40-09](https://user-images.githubusercontent.com/1193910/141937760-4213dce7-fd9d-49eb-bd19-6ed7407624f2.png)

**Comment by JerryShea** [comment]
Hi @chaitas90 can you try again with the most recent version please? There have been some improvements in this area since 5.20.123

**Comment by RobAustin** [comment]
No reply from @chaitas90, so going to close, please reopen if it's still an issue with the latest version.
