### ISSUE TITLE
Add support for listening to messages as they are appended

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#954]
This functionality is useful for adding a listener to maintain a index of entries appended

Sets an AppenderListener which is called when an Excerpt is actually written.
This is called while the writeLock is still held, after the messages has been written.
For asynchronous writes, this is called in the background thread.

**Comment by JerryShea** [comment]
Closing as I believe this has been merged. @peter-lawrey please re-open if not

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea2](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea2), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
