### ISSUE TITLE
Setting the rollTime doesn't change the epoch.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#956]
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilderTest#testReadMarshallable assumes the rollCycle sets the epoch.

**Comment by alamar** [comment]
Looks like it's not needed in the light of https://github.com/OpenHFT/Chronicle-Wire/pull/362

**Comment by alamar** [comment]
Issue no longer manifests.
