### ISSUE TITLE
Allow named tailers to be used concurrently to split work

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#964]

**Comment by RobAustin** [comment]
I'm going to close this, please reopen if not complete

**Comment by JerryShea** [comment]
The PR is still open #965

**Comment by minborg** [comment]
This is interesting and would be very useful for parallel `java.util.stream.Stream` wrappers.

**Comment by tgd** [comment]
Closing this out as no work is planned on this issue at the moment. Please comment on this issue if you would like it re-opened.
