### ISSUE TITLE
chronicle-queue 5.21.91 does not properly work with java.util.Date

### ISSUE THREAD

**Issue by olegs1993** [OpenHFT/Chronicle-Queue#969]
Hi, when I am trying to write the java.util.Date object looks like it is cutting off milliseconds.
![telegram-cloud-photo-size-2-5312265708224231521-y](https://user-images.githubusercontent.com/23138783/145799264-e303b5f6-72f7-41f0-8250-f94f77f10f50.jpg)

There is no such problem in 5.17.0. Could someone help with it?

**Comment by olegs1993** [comment]
looks like the issue is more related to the chronicle-wire project https://github.com/OpenHFT/Chronicle-Wire/issues/367

**Comment by minborg** [comment]
Are you able to run a more recent version of Chronicle Queue (perhaps the latest .22 version?) The way LocalTime is handled has indeed changed in Wire.

**Comment by olegs1993** [comment]
> Are you able to run a more recent version of Chronicle Queue (perhaps the latest .22 version?) The way LocalTime is handled has indeed changed in Wire.

probably yes, just wanted to confirm whether that behavior is a bug or not. Actually, the problem is only with java.util.Date.  I checked with LocalDateTime and it works as expected, i guess LocalTime and LocalDate also. I described the code difference here: https://github.com/OpenHFT/Chronicle-Wire/issues/367

**Comment by minborg** [comment]
in a recent Wire release, we made sure that a large number of types (similar to Data and the likes) were serialized correctly and added many new tests.

**Comment by olegs1993** [comment]
I used 5.22.ea12 and the issue is resolved there :)

**Comment by JerryShea** [comment]
Thanks @olegs1993 - are you happy to close the issue?

**Comment by olegs1993** [comment]
@JerryShea @minborg by the way, do you know the date when a non ea version will be available?
