### ISSUE TITLE
SingleChronicleQueue#exceptsPerCycle returning obsolete value

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#975]
When doing a lot of background writing to Queue, the `queue.exceptsPerCycle(cycle)` invocation may return a value that is smaller by `1` than the last actual written entry index.

The underlying problem is that `tailer.store.lastSequenceNumber(tailer)` returns incorrect value in its memory lookup loop, whereas the fallback `tailer.store.sequenceForPosition(tailer, Long.MAX_VALUE, false)` will return correct value.

The method name is semantically problematic (it does not return value 'per' cycle, excerpts are pull-based so counting them is confusing, and there's a typo) and it is the last user of obsolete `acquireTailer()` so maybe we should rethink this method over.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22ea16](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22ea16), [BOM-2.22ea106](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea106)
