### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by CaymanTurtleBeach** [OpenHFT/Chronicle-Queue#985]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on net.openhft.chronicle.core.Jvm (file:XXXX/.m2/repository/net/openhft/chronicle-core/2.22ea19/chronicle-core-2.22ea19.jar) to class java.lang.reflect.AccessibleObject
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm

Consider it reported!

Error occurred with the following in local pom for **hello world** app
``` 

                 <dependency>

			<groupId>net.openhft</groupId>

			<artifactId>chronicle-queue</artifactId>

			<version>5.22ea14</version>

	  	</dependency>

 ```

The same error also occurred when I used what appears to be the last full release (**5.21.94**)

The toy application **did** actually run, and input/output appeared to be correct.

**Comment by JerryShea** [comment]
Thanks @CaymanTurtleBeach. There are still some reflection warnings in Chronicle's libraries. Please see [this article](https://chronicle.software/chronicle-support-java-17/) for command line args to run Chronicle libraries under Java 17

**Comment by CaymanTurtleBeach** [comment]
Thanks for the information. I am actually using Java 11 at present; I will explore applying the Java 17 suggestions, and soon migrate to 17.


Cheers,

Jack

____________________________

Jack Copper
Managing Director
NeuralStudio SEZC

Cayman Enterprise City
PO Box 10315, 90 N Church St
Grand Cayman KY1-1003
Cayman Islands

https://neuralstudio.ai<https://neuralstudio.ai/>

Direct:  +1 (345) 815-3930
Mobile: +1 (345) 925-8459

Mobile: +1 (412) 801-2715 (US and International)

SKYPE:  jack-copper
____________________________
This communication is for use by the intended recipient(s) only and contains
information that may be privileged, confidential or copyrighted under
applicable law.  If you are not an intended recipient, you are hereby
formally notified that any use, copying or distribution of this e-mail,
in whole or in part, is strictly prohibited.  Please notify the sender
by return e-mail and delete this e-mail from your system.  This e-mail
does not constitute a consent to the use of sender's contact information
for marketing purposes or for transfers of data to third parties.
**************************************************************************

________________________________

**Comment by JerryShea** [comment]
@CaymanTurtleBeach I believe those same instructions should work just as well on Java 11
