### ISSUE TITLE
Remove exception-suppressing code from SCQIndexing#moveToIndex0

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#996]
```
        } catch (IllegalStateException e) {
            return linearScan(ec.wire(), index, -1, 0);
        }
````
It was introduced in #334 to support lazy indexing, which was in turn removed in 5.x
Removing this clause does not seem to affect any tests in Queue and dependent projects, but we have observed in thread dumps and have suspicion that it may be masking problems (such as accessing closed queue) and make Queue hang instead of throwing an exception.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22ea16](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22ea16), [BOM-2.22ea106](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea106)
